#ifndef _MOTORSPEED_CONFIG_H
#define _MOTORSPEED_CONFIG_H

#define HMOTORSPEED_PORT (GPIO_PORTB)
#define HMOTORSPEED_PIN (GPIOx_PIN10)
#define HMOTORSPEED_DISC_HOLES_NUM  (20)

#endif //_MOTORSPEED_CONFIG_H
