COTS/APP/ACC/ACC_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `../../HAL/Bluetooth/Bluetooth_interface.h`
#include `../../HAL/DCMOTOR/DCM_interface.h`
#include `../../HAL/Car_Movement/Car_Movement_interface.h`
#include `../../HAL/UltraSonic/UltraSonic_interface.h`
#include `../Mob_APP/Mob_APP_interface.h`
#include `ACC_interface.h`
#include `ACC_private.h`
#include `ACC_config.h`
Functions
void AACC_vModeON (void)
Variables
u32_t L_u32SpeedValue = (0)
f32_t L_f32Distance = (0)
c8_t volatile G_c8ACCRecievedButton = (0)
u8_t volatile Gv_u8InISR = (0)
Function Documentation
AACC_vModeON()
void AACC_vModeON (void)
Definition at line 55 of file ACC_program.c.
{
    G_c8ACCRecievedButton = INITIAL_ZERO ;
    Gv_u8InISR = FALSE ;
    HBluetooth_vSendString("\nACC Mode ON\n") ;
    HBluetooth_vEnableAsynchReceive() ;
    HBluetooth_u8AsynchReceiveByte(&Button_vCurrentData) ;
    do
    {
        HULTSNC_vTrigger(&TRIG) ;
        L_f32Distance = HULTSNC_f32GetDistance() ;
        if(L_f32Distance < ACC_SAFE_DIST)
        {
            HCarMove_vStop() ;
            HBluetooth_vSendString(SPEED0_STR) ;
        }
        else if(L_f32Distance >= ACC_SAFE_DIST + HYSTRS_VALUE)
        {
            HCarMove_vForward() ;
            L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
            AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
        }
        else
        {
            /* Do Nothing */
        }
        if(Gv_u8InISR == TRUE)
        {
            Gv_u8InISR = FALSE ;
            switch(G_c8ACCRecievedButton)
            {
                case EXIT_MODE_CHAR:
                    HCarMove_vStop() ;
                    HBluetooth_vSendString(SPEED0_STR) ;
                    HBluetooth_vSendString("\nACC Mode Off\n") ;
                    HBluetooth_u8AsynchReceiveByte(NULL) ;
                break ;
                case INC_SPEED_CHAR:
                    L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                    if(L_u32SpeedValue >= SPEED_100_PERCENT)
                    {
                        L_u32SpeedValue = SPEED_100_PERCENT ;
                        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                    }
                    else
                    {
                        L_u32SpeedValue += SPEED_10_PERCENT ;
                        HCarMove_vSpeedRatio(L_u32SpeedValue) ;
                        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                    }
                break ;
                case DEC_SPEED_CHAR:
                    L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                    if(L_u32SpeedValue <= SPEED_0_PERCENT)
                    {
                        L_u32SpeedValue = SPEED_0_PERCENT ;
                        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                    }
                    else
                    {
                        L_u32SpeedValue -= SPEED_10_PERCENT ;
                        HCarMove_vSpeedRatio(L_u32SpeedValue) ;
                        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                    }
                break ;
                default: /* Do Nothing */ break ;
            }
        }
        else
        {
            /* Do nothing */
        }
    }while(G_c8ACCRecievedButton != EXIT_MODE_CHAR) ;
}
References ACC_SAFE_DIST, AMobApp_vSendSpeedValue(), DEC_SPEED_CHAR, EXIT_MODE_CHAR, FALSE, G_c8ACCRecievedButton, Gv_u8InISR, HBluetooth_u8AsynchReceiveByte(), HBluetooth_vEnableAsynchReceive(), HBluetooth_vSendString(), HCarMove_u32GetCarSpeed(), HCarMove_vForward(), HCarMove_vSpeedRatio(), HCarMove_vStop(), HULTSNC_f32GetDistance(), HULTSNC_vTrigger(), HYSTRS_VALUE, INC_SPEED_CHAR, INITIAL_ZERO, L_f32Distance, L_u32SpeedValue, NULL, SPEED0_STR, SPEED_0_PERCENT, SPEED_100_PERCENT, SPEED_10_PERCENT, and TRUE.
Referenced by AMobApp_vCntrlCar().
Variable Documentation
L_u32SpeedValue
u32_t L_u32SpeedValue = (0)
Definition at line 29 of file ACC_program.c.
Referenced by AACC_vModeON(), AFCW_vModeON(), ANCC_vModeON(), ATraditional_vModeON(), HCarMove_u32GetCarSpeed(), and HDCM_vGetSpeedValue().
L_f32Distance
f32_t L_f32Distance = (0)
Definition at line 30 of file ACC_program.c.
Referenced by AACC_vModeON(), AFCW_vModeON(), and HULTSNC_f32GetDistance().
G_c8ACCRecievedButton
c8_t volatile G_c8ACCRecievedButton = (0)
Definition at line 31 of file ACC_program.c.
Referenced by AACC_vModeON().
Gv_u8InISR
u8_t volatile Gv_u8InISR = (0)
Definition at line 32 of file ACC_program.c.
Referenced by AACC_vModeON().