COTS/MCAL/ADC/ADC_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../RCC/MRCC_interface.h`
#include `ADC_interface.h`
#include `ADC_private.h`
#include `ADC_config.h`
Functions
void MADC_vInit (void)
void MADC_vSelectChannel (u8_t A_u8ChannelNum)
u16_t MADC_u16ConvertToDigital (u8_t A_u8ChannelNum)
void MADC_vDisable (void)
void MADC_vEnable (void)
void MADC_vRegINT_Disable (void)
void MADC_vRegINTEnable (void)
void MADC_vSetCallBack (void(*MEXTI_vpPointerTo_ISR_function)(void))
void ADC_IRQHandler (void)
Variables
void(* MADC_vpPointerToFunction)(void) = ((void*)0)
Function Documentation
MADC_vInit()
void MADC_vInit (void)
Definition at line 30 of file ADC_program.c.
{
    // EN CLK on APB2 bus to be able to operate ADC peripheral:
    MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_ADC1EN) ;
    // EN/DIS power for ADC to be turned on/off:
    #if ADC_ON == ENABLE
    SET_BIT(ADC->CR2, ADON) ;
    #elif ADC_ON == DISABLE
    CLR_BIT(ADC->CR2, ADON) ;
    #endif
    // Select ADC prescalers(2/4/6/8):
    #if ADC_PRESCALER == DIV_BY_2
    CLR_BIT(ADC->CCR, ADCPRE0) ;
    CLR_BIT(ADC->CCR, ADCPRE0) ;
    #elif ADC_PRESCALER == DIV_BY_4
    SET_BIT(ADC->CCR, ADCPRE0) ;
    CLR_BIT(ADC->CCR, ADCPRE0) ;
    #elif ADC_PRESCALER == DIV_BY_6
    CLR_BIT(ADC->CCR, ADCPRE0) ;
    SET_BIT(ADC->CCR, ADCPRE0) ;
    #elif ADC_PRESCALER == DIV_BY_8
    SET_BIT(ADC->CCR, ADCPRE0) ;
    SET_BIT(ADC->CCR, ADCPRE0) ;
    #endif
    // Select ADC Resolution(12/10/8/6):
    #if RESOLUTION == _12_BITS
    CLR_BIT(ADC->CR1, RES0) ;
    CLR_BIT(ADC->CR1, RES1) ;
    #elif RESOLUTION == _10_BITS
    SET_BIT(ADC->CR1, RES0) ;
    CLR_BIT(ADC->CR1, RES1) ;
    #elif RESOLUTION == _8_BITS
    CLR_BIT(ADC->CR1, RES0) ;
    SET_BIT(ADC->CR1, RES1) ;
    #elif RESOLUTION == _6_BITS
    SET_BIT(ADC->CR1, RES0) ;
    SET_BIT(ADC->CR1, RES1) ;
    #endif
    // ADC Data Alignment(Right/Left):
    #if DATA_ALIGN == RIGHT
    CLR_BIT(ADC->CR2, ALIGN) ;
    #elif DATA_ALIGN == LEFT
    SET_BIT(ADC->CR2, ALIGN) ;
    #endif
    // EN/DIS Injected INT:
    #if JEOCIE_MODE == ENABLE
    SET_BIT(ADC->CR1, JEOCIE) ;
    #elif JEOCIE_MODE == DISABLE
    CLR_BIT(ADC->CR1, JEOCIE) ;
    #endif
    // EN/DIS Regular INT:
    #if EOCIE_MODE == ENABLE
    SET_BIT(ADC->CR1, EOCIE) ;
    #elif EOCIE_MODE == DISABLE
    CLR_BIT(ADC->CR1, EOCIE) ;
    #endif
    // EN/DIS Overrun interrupt:
    #if OVERRUN_INT == ENABLE
    SET_BIT(ADC->CR1, OVRIE) ;
    #elif OVERRUN_INT == DISABLE
    CLR_BIT(ADC->CR1, OVRIE) ;
    #endif
    // Select Regular channel sequence length(1/2/3/.../16):
    #if REG_SQ_LENGTH == _1_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _2_CONV
    SET_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _3_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _4_CONV
    SET_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _5_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _6_CONV
    SET_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _7_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _8_CONV
    SET_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _9_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _10_CONV
    SET_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _11_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _12_CONV
    SET_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _13_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _14_CONV
    SET_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _15_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _16_CONV
    SET_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #endif
    // EN/DIS SCAN MODE:
    #if SCAN_MODE == ENABLE
    SET_BIT(ADC->CR1, SCAN) ;
    #elif SCAN_MODE == DISABLE
    CLR_BIT(ADC->CR1, SCAN) ;
    #endif
    // EN/DIS Discontinuous mode on Regular:
    #if DISC_MODE == ENABLE
    SET_BIT(ADC->CR1, DISCEN) ;
    #elif DISC_MODE == DISABLE
    CLR_BIT(ADC->CR1, DISCEN) ;
    #endif
    // Discontinuous mode channel count(1/2/3/4/.../8):
    #if DISC_CHANNEL_NUM == _1_CHANNEL
    CLR_BIT(ADC->CR1, DISCNUM0) ;
    CLR_BIT(ADC->CR1, DISCNUM1) ;
    CLR_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _2_CHANNELS
    SET_BIT(ADC->CR1, DISCNUM0) ;
    CLR_BIT(ADC->CR1, DISCNUM1) ;
    CLR_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _3_CHANNELS
    CLR_BIT(ADC->CR1, DISCNUM0) ;
    SET_BIT(ADC->CR1, DISCNUM1) ;
    CLR_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _4_CHANNELS
    SET_BIT(ADC->CR1, DISCNUM0) ;
    SET_BIT(ADC->CR1, DISCNUM1) ;
    CLR_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _5_CHANNELS
    CLR_BIT(ADC->CR1, DISCNUM0) ;
    CLR_BIT(ADC->CR1, DISCNUM1) ;
    SET_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _6_CHANNELS
    SET_BIT(ADC->CR1, DISCNUM0) ;
    CLR_BIT(ADC->CR1, DISCNUM1) ;
    SET_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _7_CHANNELS
    CLR_BIT(ADC->CR1, DISCNUM0) ;
    SET_BIT(ADC->CR1, DISCNUM1) ;
    SET_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _8_CHANNELS
    SET_BIT(ADC->CR1, DISCNUM0) ;
    SET_BIT(ADC->CR1, DISCNUM1) ;
    SET_BIT(ADC->CR1, DISCNUM2) ;
    #endif
    // EN/DIS Continuous mode:
    #if CONT_CONV == ENABLE
    SET_BIT(ADC->CR2, CONT) ;
    #elif CONT_CONV == DISABLE
    CLR_BIT(ADC->CR2, CONT) ;
    #endif
}
References ADC, ADCPRE0, ADON, ALIGN, APB2ENR_ADC1EN, CLR_BIT, CONT, DISCEN, DISCNUM0, DISCNUM1, DISCNUM2, EOCIE, JEOCIE, L0, L1, L2, L3, MRCC_vEnablePeriphralCLK(), OVRIE, RCC_APB2, RES0, RES1, SCAN, and SET_BIT.
Referenced by HLDR_vInit().
MADC_vSelectChannel()
void MADC_vSelectChannel (u8_t A_u8ChannelNum)
Definition at line 345 of file ADC_program.c.
{
    // Select Regular channel(1/2/3/.../16)
    ADC->SQR3 = (ADC->SQR3 & SQ1_BIT_MANIPULATION) | (A_u8ChannelNum) ;
}
References ADC, and SQ1_BIT_MANIPULATION.
MADC_u16ConvertToDigital()
u16_t MADC_u16ConvertToDigital (u8_t A_u8ChannelNum)
Definition at line 356 of file ADC_program.c.
{
    // Select Regular channel(1/2/3/.../16)
    ADC->SQR3 = (ADC->SQR3 & SQ1_BIT_MANIPULATION) | (A_u8ChannelNum) ;
    // Start conversion of regular channels:
    SET_BIT(ADC->CR2, SWSTART) ;
    // Poll on the end of coversion flag until it's raised:
    while(GET_BIT(ADC->SR, EOC) != FLAG_SET) ;
    // Clear the flag:
    CLR_BIT(ADC->SR, EOC) ;
    // Return ADC Data:
    return ADC->DR ;
}
References ADC, CLR_BIT, EOC, FLAG_SET, GET_BIT, SET_BIT, SQ1_BIT_MANIPULATION, and SWSTART.
MADC_vDisable()
void MADC_vDisable (void)
Definition at line 379 of file ADC_program.c.
{
    // DIS CLK on APB2 bus to be able to operate ADC peripheral:
    MRCC_vDisablePeriphralCLK(RCC_APB2, APB2ENR_ADC1EN) ;
    // Power off ADC:
    CLR_BIT(ADC->CR2, ADON) ;
}
References ADC, ADON, APB2ENR_ADC1EN, CLR_BIT, MRCC_vDisablePeriphralCLK(), and RCC_APB2.
MADC_vEnable()
void MADC_vEnable (void)
Definition at line 393 of file ADC_program.c.
{
    // EN CLK on APB2 bus to be able to operate ADC peripheral:
    MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_ADC1EN) ;
    // Power on ADC:
    SET_BIT(ADC->CR2, ADON) ;
}
References ADC, ADON, APB2ENR_ADC1EN, MRCC_vEnablePeriphralCLK(), RCC_APB2, and SET_BIT.
MADC_vRegINT_Disable()
void MADC_vRegINT_Disable (void)
Definition at line 407 of file ADC_program.c.
{
    CLR_BIT(ADC->CR1, EOCIE) ;
}
References ADC, CLR_BIT, and EOCIE.
MADC_vRegINTEnable()
void MADC_vRegINTEnable (void)
Definition at line 415 of file ADC_program.c.
{
    SET_BIT(ADC->CR1, EOCIE) ;
}
References ADC, EOCIE, and SET_BIT.
MADC_vSetCallBack()
void MADC_vSetCallBack (void(*)(void) MEXTI_vpPointerTo_ISR_function)
Definition at line 423 of file ADC_program.c.
{
    if(MEXTI_vpPointerTo_ISR_function != NULL)
    {
        MADC_vpPointerToFunction = MEXTI_vpPointerTo_ISR_function ;
    }
}
References MADC_vpPointerToFunction, and NULL.
ADC_IRQHandler()
void ADC_IRQHandler (void)
Definition at line 438 of file ADC_program.c.
{
    if(MADC_vpPointerToFunction != NULL)
    {
        MADC_vpPointerToFunction() ;
    }
    // Clear the flags.
    CLR_BIT(ADC->SR, EOC) ;
    CLR_BIT(ADC->SR, JEOC) ;
}
References ADC, CLR_BIT, EOC, JEOC, MADC_vpPointerToFunction, and NULL.
Variable Documentation
MADC_vpPointerToFunction
void(* MADC_vpPointerToFunction) (void) (void) = ((void*)0)
Definition at line 23 of file ADC_program.c.
Referenced by ADC_IRQHandler(), and MADC_vSetCallBack().