COTS/MCAL/ADC/ADC_interface.h File Reference
This file contains the interfacing information of ADC Module in STM32F103C8 ARM Microcontroller.
Macros
#define CHANNEL0 0
Channel 0.
#define CHANNEL1 1
Channel 1.
#define CHANNEL2 2
Channel 2.
#define CHANNEL3 3
Channel 3.
#define CHANNEL4 4
Channel 4.
#define CHANNEL5 5
Channel 5.
#define CHANNEL6 6
Channel 6.
#define CHANNEL7 7
Channel 7.
#define CHANNEL8 8
Channel 8.
#define CHANNEL9 9
Channel 9.
#define CHANNEL10 10
Channel 10.
#define CHANNEL11 11
Channel 11.
#define CHANNEL12 12
Channel 12.
#define CHANNEL13 13
Channel 13.
#define CHANNEL14 14
Channel 14.
#define CHANNEL15 15
Channel 15.
#define CHANNEL16 16
Channel 16.
#define CHANNEL17 17
Channel 17.
#define CHANNEL18 18
Channel 18.
Functions
void MADC_vInit (void)
This function is responsible for initializing the ADC module.
u16_t MADC_u16ConvertToDigital (u8_t A_u8ChannelNum)
This function is responsible for converting the analog value to digital value.
void MADC_vDisable (void)
This function is responsible for disabling the ADC module.
void MADC_vEnable (void)
This function is responsible for enabling the ADC module.
void MADC_vRegINT_Disable (void)
This function is responsible for disabling the ADC module interrupt.
void MADC_vRegINTEnable (void)
This function is responsible for enabling the ADC module interrupt.
void MADC_vSelectChannel (u8_t A_u8ChannelNum)
This function is responsible for selecting the channel of the ADC module.
void MADC_vSetCallBack (void(*MEXTI_vpPointerTo_ISR_function)(void))
This function is responsible for setting the callback function of the ADC module.
Detailed Description
This file contains the interfacing information of ADC Module in STM32F103C8 ARM Microcontroller.
This file contains the prototyping of the APIs of ADC Module in STM32F103C8 ARM Microcontroller
Author
Ali El Bana
Version
1.0
Date
12/14/2022
Definition in file ADC_interface.h.
Function Documentation
MADC_vInit()
void MADC_vInit (void)
This function is responsible for initializing the ADC module.
Definition at line 30 of file ADC_program.c.
{
    // EN CLK on APB2 bus to be able to operate ADC peripheral:
    MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_ADC1EN) ;
    // EN/DIS power for ADC to be turned on/off:
    #if ADC_ON == ENABLE
    SET_BIT(ADC->CR2, ADON) ;
    #elif ADC_ON == DISABLE
    CLR_BIT(ADC->CR2, ADON) ;
    #endif
    // Select ADC prescalers(2/4/6/8):
    #if ADC_PRESCALER == DIV_BY_2
    CLR_BIT(ADC->CCR, ADCPRE0) ;
    CLR_BIT(ADC->CCR, ADCPRE0) ;
    #elif ADC_PRESCALER == DIV_BY_4
    SET_BIT(ADC->CCR, ADCPRE0) ;
    CLR_BIT(ADC->CCR, ADCPRE0) ;
    #elif ADC_PRESCALER == DIV_BY_6
    CLR_BIT(ADC->CCR, ADCPRE0) ;
    SET_BIT(ADC->CCR, ADCPRE0) ;
    #elif ADC_PRESCALER == DIV_BY_8
    SET_BIT(ADC->CCR, ADCPRE0) ;
    SET_BIT(ADC->CCR, ADCPRE0) ;
    #endif
    // Select ADC Resolution(12/10/8/6):
    #if RESOLUTION == _12_BITS
    CLR_BIT(ADC->CR1, RES0) ;
    CLR_BIT(ADC->CR1, RES1) ;
    #elif RESOLUTION == _10_BITS
    SET_BIT(ADC->CR1, RES0) ;
    CLR_BIT(ADC->CR1, RES1) ;
    #elif RESOLUTION == _8_BITS
    CLR_BIT(ADC->CR1, RES0) ;
    SET_BIT(ADC->CR1, RES1) ;
    #elif RESOLUTION == _6_BITS
    SET_BIT(ADC->CR1, RES0) ;
    SET_BIT(ADC->CR1, RES1) ;
    #endif
    // ADC Data Alignment(Right/Left):
    #if DATA_ALIGN == RIGHT
    CLR_BIT(ADC->CR2, ALIGN) ;
    #elif DATA_ALIGN == LEFT
    SET_BIT(ADC->CR2, ALIGN) ;
    #endif
    // EN/DIS Injected INT:
    #if JEOCIE_MODE == ENABLE
    SET_BIT(ADC->CR1, JEOCIE) ;
    #elif JEOCIE_MODE == DISABLE
    CLR_BIT(ADC->CR1, JEOCIE) ;
    #endif
    // EN/DIS Regular INT:
    #if EOCIE_MODE == ENABLE
    SET_BIT(ADC->CR1, EOCIE) ;
    #elif EOCIE_MODE == DISABLE
    CLR_BIT(ADC->CR1, EOCIE) ;
    #endif
    // EN/DIS Overrun interrupt:
    #if OVERRUN_INT == ENABLE
    SET_BIT(ADC->CR1, OVRIE) ;
    #elif OVERRUN_INT == DISABLE
    CLR_BIT(ADC->CR1, OVRIE) ;
    #endif
    // Select Regular channel sequence length(1/2/3/.../16):
    #if REG_SQ_LENGTH == _1_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _2_CONV
    SET_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _3_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _4_CONV
    SET_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _5_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _6_CONV
    SET_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _7_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _8_CONV
    SET_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    CLR_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _9_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _10_CONV
    SET_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _11_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _12_CONV
    SET_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    CLR_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _13_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _14_CONV
    SET_BIT(ADC->SQR1, L0) ;
    CLR_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _15_CONV
    CLR_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #elif REG_SQ_LENGTH == _16_CONV
    SET_BIT(ADC->SQR1, L0) ;
    SET_BIT(ADC->SQR1, L1) ;
    SET_BIT(ADC->SQR1, L2) ;
    SET_BIT(ADC->SQR1, L3) ;
    #endif
    // EN/DIS SCAN MODE:
    #if SCAN_MODE == ENABLE
    SET_BIT(ADC->CR1, SCAN) ;
    #elif SCAN_MODE == DISABLE
    CLR_BIT(ADC->CR1, SCAN) ;
    #endif
    // EN/DIS Discontinuous mode on Regular:
    #if DISC_MODE == ENABLE
    SET_BIT(ADC->CR1, DISCEN) ;
    #elif DISC_MODE == DISABLE
    CLR_BIT(ADC->CR1, DISCEN) ;
    #endif
    // Discontinuous mode channel count(1/2/3/4/.../8):
    #if DISC_CHANNEL_NUM == _1_CHANNEL
    CLR_BIT(ADC->CR1, DISCNUM0) ;
    CLR_BIT(ADC->CR1, DISCNUM1) ;
    CLR_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _2_CHANNELS
    SET_BIT(ADC->CR1, DISCNUM0) ;
    CLR_BIT(ADC->CR1, DISCNUM1) ;
    CLR_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _3_CHANNELS
    CLR_BIT(ADC->CR1, DISCNUM0) ;
    SET_BIT(ADC->CR1, DISCNUM1) ;
    CLR_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _4_CHANNELS
    SET_BIT(ADC->CR1, DISCNUM0) ;
    SET_BIT(ADC->CR1, DISCNUM1) ;
    CLR_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _5_CHANNELS
    CLR_BIT(ADC->CR1, DISCNUM0) ;
    CLR_BIT(ADC->CR1, DISCNUM1) ;
    SET_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _6_CHANNELS
    SET_BIT(ADC->CR1, DISCNUM0) ;
    CLR_BIT(ADC->CR1, DISCNUM1) ;
    SET_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _7_CHANNELS
    CLR_BIT(ADC->CR1, DISCNUM0) ;
    SET_BIT(ADC->CR1, DISCNUM1) ;
    SET_BIT(ADC->CR1, DISCNUM2) ;
    #elif DISC_CHANNEL_NUM == _8_CHANNELS
    SET_BIT(ADC->CR1, DISCNUM0) ;
    SET_BIT(ADC->CR1, DISCNUM1) ;
    SET_BIT(ADC->CR1, DISCNUM2) ;
    #endif
    // EN/DIS Continuous mode:
    #if CONT_CONV == ENABLE
    SET_BIT(ADC->CR2, CONT) ;
    #elif CONT_CONV == DISABLE
    CLR_BIT(ADC->CR2, CONT) ;
    #endif
}
References APB2ENR_ADC1EN, CLR_BIT, MADC_vInit(), MRCC_vEnablePeriphralCLK(), RCC_APB2, and SET_BIT.
Referenced by MADC_vInit().
MADC_u16ConvertToDigital()
u16_t MADC_u16ConvertToDigital (u8_t A_u8ChannelNum)
This function is responsible for converting the analog value to digital value.
Returns
u16_t The digital value of the analog value
Definition at line 356 of file ADC_program.c.
{
    // Select Regular channel(1/2/3/.../16)
    ADC->SQR3 = (ADC->SQR3 & SQ1_BIT_MANIPULATION) | (A_u8ChannelNum) ;
    // Start conversion of regular channels:
    SET_BIT(ADC->CR2, SWSTART) ;
    // Poll on the end of coversion flag until it's raised:
    while(GET_BIT(ADC->SR, EOC) != FLAG_SET) ;
    // Clear the flag:
    CLR_BIT(ADC->SR, EOC) ;
    // Return ADC Data:
    return ADC->DR ;
}
References CLR_BIT, FLAG_SET, GET_BIT, MADC_u16ConvertToDigital(), and SET_BIT.
Referenced by MADC_u16ConvertToDigital().
MADC_vDisable()
void MADC_vDisable (void)
This function is responsible for disabling the ADC module.
Definition at line 379 of file ADC_program.c.
{
    // DIS CLK on APB2 bus to be able to operate ADC peripheral:
    MRCC_vDisablePeriphralCLK(RCC_APB2, APB2ENR_ADC1EN) ;
    // Power off ADC:
    CLR_BIT(ADC->CR2, ADON) ;
}
References APB2ENR_ADC1EN, CLR_BIT, MADC_vDisable(), MRCC_vDisablePeriphralCLK(), and RCC_APB2.
Referenced by MADC_vDisable().
MADC_vEnable()
void MADC_vEnable (void)
This function is responsible for enabling the ADC module.
Definition at line 393 of file ADC_program.c.
{
    // EN CLK on APB2 bus to be able to operate ADC peripheral:
    MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_ADC1EN) ;
    // Power on ADC:
    SET_BIT(ADC->CR2, ADON) ;
}
References APB2ENR_ADC1EN, MADC_vEnable(), MRCC_vEnablePeriphralCLK(), RCC_APB2, and SET_BIT.
Referenced by MADC_vEnable().
MADC_vRegINT_Disable()
void MADC_vRegINT_Disable (void)
This function is responsible for disabling the ADC module interrupt.
Definition at line 407 of file ADC_program.c.
{
    CLR_BIT(ADC->CR1, EOCIE) ;
}
References CLR_BIT, and MADC_vRegINT_Disable().
Referenced by MADC_vRegINT_Disable().
MADC_vRegINTEnable()
void MADC_vRegINTEnable (void)
This function is responsible for enabling the ADC module interrupt.
Definition at line 415 of file ADC_program.c.
{
    SET_BIT(ADC->CR1, EOCIE) ;
}
References MADC_vRegINTEnable(), and SET_BIT.
Referenced by MADC_vRegINTEnable().
MADC_vSelectChannel()
void MADC_vSelectChannel (u8_t A_u8ChannelNum)
This function is responsible for selecting the channel of the ADC module.
Definition at line 345 of file ADC_program.c.
{
    // Select Regular channel(1/2/3/.../16)
    ADC->SQR3 = (ADC->SQR3 & SQ1_BIT_MANIPULATION) | (A_u8ChannelNum) ;
}
References MADC_vSelectChannel().
Referenced by MADC_vSelectChannel().
MADC_vSetCallBack()
void MADC_vSetCallBack (void(*)(void) MEXTI_vpPointerTo_ISR_function)
This function is responsible for setting the callback function of the ADC module.
Parameters
 in MEXTI_vpPointerTo_ISR_function A pointer to the callback function
Definition at line 423 of file ADC_program.c.
{
    if(MEXTI_vpPointerTo_ISR_function != NULL)
    {
        MADC_vpPointerToFunction = MEXTI_vpPointerTo_ISR_function ;
    }
}
References MADC_vSetCallBack(), and NULL.
Referenced by MADC_vSetCallBack().