COTS/HAL/BUZZER/BUZZER_interface.h File Reference
Data Structures
struct BUZZER_BuzzerConfiguration
Buzzer configuration structure for Buzzer initialization.
Functions
void HBUZZER_vInit (P2VAR(BUZZER_BuzzerConfiguration) pBuzzer_Cfg)
This function is used to initialize the Buzzer.
void HBUZZER_vSoundOn (P2VAR(BUZZER_BuzzerConfiguration) pBuzzer_Cfg)
This function is used to sound the Buzzer on.
void HBUZZER_vSoundOff (P2VAR(BUZZER_BuzzerConfiguration) pBuzzer_Cfg)
This function is used to sound the Buzzer off.
void HBUZZER_vToggleSound (P2VAR(BUZZER_BuzzerConfiguration) pBuzzer_Cfg)
This function is used to toggle the sound of the buzzer.
Function Documentation
HBUZZER_vInit()
void HBUZZER_vInit (P2VAR(BUZZER_BuzzerConfiguration) pBuzzer_Cfg)
This function is used to initialize the Buzzer.
Parameters
 in pBuzzer_Cfg Pointer to Buzzer configuration structure to initialize the Buzzer with a certain port and pin
Referenced by AFCW_vModeON().
HBUZZER_vSoundOn()
void HBUZZER_vSoundOn (P2VAR(BUZZER_BuzzerConfiguration) pBuzzer_Cfg)
This function is used to sound the Buzzer on.
Parameters
 in pBuzzer_Cfg Pointer to Buzzer configuration to sound on the Buzzer
Referenced by AFCW_vModeON().
HBUZZER_vSoundOff()
void HBUZZER_vSoundOff (P2VAR(BUZZER_BuzzerConfiguration) pBuzzer_Cfg)
This function is used to sound the Buzzer off.
Parameters
 in pBuzzer_Cfg Pointer to Buzzer configuration to sound off the Buzzer
Referenced by AExit_vCriteriaON(), and AFCW_vModeON().
HBUZZER_vToggleSound()
void HBUZZER_vToggleSound (P2VAR(BUZZER_BuzzerConfiguration) pBuzzer_Cfg)
This function is used to toggle the sound of the buzzer.
Parameters
 in pBuzzer_Cfg Pointer to Buzzer configuration to toggle the sound of the Buzzer