COTS/HAL/BUZZER/BUZZER_program.c File Reference
This file contains the logical operations of the buzzer module.
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `BUZZER_private.h`
#include `BUZZER_interface.h`
#include `BUZZER_config.h`
Functions
void HBUZZER_vInit (BUZZER_BuzzerConfiguration *pBuzzer_Cfg)
This function is used to initialize the Buzzer.
void HBUZZER_vSoundOn (BUZZER_BuzzerConfiguration *pBuzzer_Cfg)
This function is used to sound the Buzzer on.
void HBUZZER_vSoundOff (BUZZER_BuzzerConfiguration *pBuzzer_Cfg)
This function is used to sound the Buzzer off.
void HBUZZER_vToggleSound (BUZZER_BuzzerConfiguration *pBuzzer_Cfg)
This function is used to toggle the sound of the buzzer.
Detailed Description
This file contains the logical operations of the buzzer module.
Author
Mohamed Alaa
Version
1.0
Date
12/22/2022
Definition in file BUZZER_program.c.
Function Documentation
HBUZZER_vInit()
void HBUZZER_vInit (BUZZER_BuzzerConfiguration * pBuzzer_Cfg)
This function is used to initialize the Buzzer.
Parameters
 in pBuzzer_Cfg Pointer to Buzzer configuration structure to initialize the Buzzer with a certain port and pin
Definition at line 26 of file BUZZER_program.c.
{
    VAR(MGPIOx_ConfigType) Buzzer_Cfg =
        {
            .Port = pBuzzer_Cfg->u8Port,
            .Pin = pBuzzer_Cfg->u8Pin,
            .Mode = GPIOx_MODE_OUTPUT,
            .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_LowSpeed,
            .InputType = GPIOx_NoPull};
    MGPIOx_vInit(&Buzzer_Cfg);
}
References GPIOx_LowSpeed, GPIOx_MODE_OUTPUT, GPIOx_NoPull, GPIOx_PUSHPULL, MGPIOx_vInit(), BUZZER_BuzzerConfiguration::u8Pin, BUZZER_BuzzerConfiguration::u8Port, and VAR.
HBUZZER_vSoundOn()
void HBUZZER_vSoundOn (BUZZER_BuzzerConfiguration * pBuzzer_Cfg)
This function is used to sound the Buzzer on.
Parameters
 in pBuzzer_Cfg Pointer to Buzzer configuration to sound on the Buzzer
Definition at line 43 of file BUZZER_program.c.
{
    MGPIOx_vSetPinValue(pBuzzer_Cfg->u8Port, pBuzzer_Cfg->u8Pin, GPIOx_HIGH);
}
References GPIOx_HIGH, MGPIOx_vSetPinValue(), BUZZER_BuzzerConfiguration::u8Pin, and BUZZER_BuzzerConfiguration::u8Port.
HBUZZER_vSoundOff()
void HBUZZER_vSoundOff (BUZZER_BuzzerConfiguration * pBuzzer_Cfg)
This function is used to sound the Buzzer off.
Parameters
 in pBuzzer_Cfg Pointer to Buzzer configuration to sound off the Buzzer
Definition at line 51 of file BUZZER_program.c.
{
    MGPIOx_vSetPinValue(pBuzzer_Cfg->u8Port, pBuzzer_Cfg->u8Pin, GPIOx_LOW);
}
References GPIOx_LOW, MGPIOx_vSetPinValue(), BUZZER_BuzzerConfiguration::u8Pin, and BUZZER_BuzzerConfiguration::u8Port.
HBUZZER_vToggleSound()
void HBUZZER_vToggleSound (BUZZER_BuzzerConfiguration * pBuzzer_Cfg)
This function is used to toggle the sound of the buzzer.
Parameters
 in pBuzzer_Cfg Pointer to Buzzer configuration to toggle the sound of the Buzzer
Definition at line 59 of file BUZZER_program.c.
{
    MGPIOx_vTogglePinValue(pBuzzer_Cfg->u8Port, pBuzzer_Cfg->u8Pin);
}
References MGPIOx_vTogglePinValue(), BUZZER_BuzzerConfiguration::u8Pin, and BUZZER_BuzzerConfiguration::u8Port.