COTS/HAL/Bluetooth/Bluetooth_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../../MCAL/RCC/MRCC_interface.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `../../MCAL/UART/UART_interface.h`
#include `Bluetooth_interface.h`
#include `Bluetooth_private.h`
#include `Bluetooth_config.h`
Functions
void HBluetooth_vInit (void)
void HBluetooth_vSendByte (u8_t A_u8Byte)
u8_t HBluetooth_u8ReceiveByte (void)
void HBluetooth_vSendString (c8_t *A_ptrc8String)
void HBluetooth_vReceiveString (c8_t *A_c8YourString)
u8_t HBluetooth_u8CompStrings (c8_t *String1, c8_t *String2)
void HBluetooth_vEnable (void)
void HBluetooth_vDisable (void)
void HBluetooth_ExchangeString (c8_t *L_strMessagePlaceholder, c8_t *L_strInfo)
u8_t HBluetooth_ExchangeByte (c8_t *L_strMessagePlaceholder)
Variables
USART_InitType Bluetooth_Config
USART_ClockInitTypeDef Bluetooth_CLK
USART_MemoryMapType * Bluetooth_UART_ID
Function Documentation
HBluetooth_vInit()
void HBluetooth_vInit (void)
Definition at line 38 of file Bluetooth_program.c.
{
    MUSART_vInit(&Bluetooth_Config, &Bluetooth_CLK, Bluetooth_UART_ID) ;
}
References Bluetooth_CLK, Bluetooth_Config, Bluetooth_UART_ID, and MUSART_vInit().
HBluetooth_vSendByte()
void HBluetooth_vSendByte (u8_t A_u8Byte)
Definition at line 48 of file Bluetooth_program.c.
{
    MUSART_vTransmitByte(Bluetooth_UART_ID, A_u8Byte) ;
}
References Bluetooth_UART_ID, and MUSART_vTransmitByte().
HBluetooth_u8ReceiveByte()
u8_t HBluetooth_u8ReceiveByte (void)
Definition at line 58 of file Bluetooth_program.c.
{
    u8_t L_u8ReceivedByte = INITIAL_ZERO ;
    L_u8ReceivedByte = MUSART_u8ReceiveByteSynchBlocking(Bluetooth_UART_ID) ;
    return L_u8ReceivedByte ;
}
References Bluetooth_UART_ID, INITIAL_ZERO, and MUSART_u8ReceiveByteSynchBlocking().
Referenced by HBluetooth_ExchangeByte().
HBluetooth_vSendString()
void HBluetooth_vSendString (c8_t * A_ptrc8String)
Definition at line 72 of file Bluetooth_program.c.
{
    MUSART_vTransmitString(Bluetooth_UART_ID, A_ptrc8String) ;
}
References Bluetooth_UART_ID, and MUSART_vTransmitString().
Referenced by HBluetooth_ExchangeByte(), and HBluetooth_ExchangeString().
HBluetooth_vReceiveString()
void HBluetooth_vReceiveString (c8_t * A_c8YourString)
Definition at line 82 of file Bluetooth_program.c.
{
    MUSART_vRecieveString(Bluetooth_UART_ID, A_c8YourString) ;
}
References Bluetooth_UART_ID, and MUSART_vRecieveString().
Referenced by HBluetooth_ExchangeString().
HBluetooth_u8CompStrings()
u8_t HBluetooth_u8CompStrings (c8_t * String1, c8_t * String2)
Definition at line 92 of file Bluetooth_program.c.
{
    u8_t L_u8Result = INITIAL_ZERO ;
    L_u8Result = MUSART_u8CompareString(String1, String2) ;
    return L_u8Result ;
}
References INITIAL_ZERO, and MUSART_u8CompareString().
HBluetooth_vEnable()
void HBluetooth_vEnable (void)
Definition at line 106 of file Bluetooth_program.c.
{
    MUSART_vEnable(Bluetooth_UART_ID) ;
}
References Bluetooth_UART_ID, and MUSART_vEnable().
HBluetooth_vDisable()
void HBluetooth_vDisable (void)
Definition at line 116 of file Bluetooth_program.c.
{
    MUSART_vDisable(Bluetooth_UART_ID) ;
}
References Bluetooth_UART_ID, and MUSART_vDisable().
HBluetooth_ExchangeString()
void HBluetooth_ExchangeString (c8_t * L_strMessagePlaceholder, c8_t * L_strInfo)
Definition at line 126 of file Bluetooth_program.c.
{
    HBluetooth_vSendString(L_strMessagePlaceholder);
    HBluetooth_vReceiveString(L_strInfo);
}
References HBluetooth_vReceiveString(), and HBluetooth_vSendString().
HBluetooth_ExchangeByte()
u8_t HBluetooth_ExchangeByte (c8_t * L_strMessagePlaceholder)
Definition at line 134 of file Bluetooth_program.c.
{
    HBluetooth_vSendString(L_strMessagePlaceholder);
    return HBluetooth_u8ReceiveByte();
}
References HBluetooth_u8ReceiveByte(), and HBluetooth_vSendString().
Variable Documentation
Bluetooth_Config
USART_InitType Bluetooth_Config [extern]
Definition at line 26 of file Bluetooth_config.c.
Referenced by HBluetooth_vInit().
Bluetooth_CLK
USART_ClockInitTypeDef Bluetooth_CLK [extern]
Definition at line 37 of file Bluetooth_config.c.
Referenced by HBluetooth_vInit().
Bluetooth_UART_ID
USART_MemoryMapType* Bluetooth_UART_ID [extern]
Definition at line 42 of file Bluetooth_config.c.
Referenced by HBluetooth_u8ReceiveByte(), HBluetooth_vDisable(), HBluetooth_vEnable(), HBluetooth_vInit(), HBluetooth_vReceiveString(), HBluetooth_vSendByte(), and HBluetooth_vSendString().