COTS/HAL/Bluetooth/Bluetooth_interface.h File Reference
Functions
void HBluetooth_vInit (void)
void HBluetooth_vSendByte (u8_t A_u8Byte)
u8_t HBluetooth_u8ReceiveByte (void)
void HBluetooth_u8AsynchReceiveByte (void(*Fptr)(void))
void HBluetooth_vSendString (c8_t *A_ptrc8String)
void HBluetooth_vReceiveString (c8_t A_c8YourString[])
u8_t HBluetooth_u8CompStrings (c8_t *String1, c8_t *String2)
void HBluetooth_vEnable (void)
void HBluetooth_vDisable (void)
void HBluetooth_vEnableAsynchReceive (void)
void HBluetooth_vDisableAsynchReceive (void)
u8_t HBluetooth_u8GetDataRegister (void)
Function Documentation
HBluetooth_vInit()
void HBluetooth_vInit (void)
Definition at line 45 of file Bluetooth_program.c.
{
    // Initialization of USART1:
    MUSART_vInit(&Bluetooth_Config, &Bluetooth_CLK, Bluetooth_UART_ID) ;
}
References Bluetooth_CLK, Bluetooth_Config, Bluetooth_UART_ID, and MUSART_vInit().
Referenced by AMobApp_vInit().
HBluetooth_vSendByte()
void HBluetooth_vSendByte (u8_t A_u8Byte)
Definition at line 56 of file Bluetooth_program.c.
{
    MUSART_vTransmitByte(Bluetooth_UART_ID, A_u8Byte) ;
}
References Bluetooth_UART_ID, and MUSART_vTransmitByte().
HBluetooth_u8ReceiveByte()
u8_t HBluetooth_u8ReceiveByte (void)
Definition at line 66 of file Bluetooth_program.c.
{
    u8_t L_u8ReceivedByte = INITIAL_ZERO ;
    L_u8ReceivedByte = MUSART_u8ReceiveByteSynchBlocking(Bluetooth_UART_ID) ;
    return L_u8ReceivedByte ;
}
References Bluetooth_UART_ID, INITIAL_ZERO, and MUSART_u8ReceiveByteSynchBlocking().
Referenced by AMobApp_vCntrlCar(), ANCC_vModeON(), and ATraditional_vModeON().
HBluetooth_u8AsynchReceiveByte()
void HBluetooth_u8AsynchReceiveByte (void(*)(void) Fptr)
Definition at line 80 of file Bluetooth_program.c.
{
    MUSART1_vSetCallBack(Fptr) ;
}
References MUSART1_vSetCallBack().
Referenced by AACC_vModeON(), and AFCW_vModeON().
HBluetooth_vSendString()
void HBluetooth_vSendString (c8_t * A_ptrc8String)
Definition at line 90 of file Bluetooth_program.c.
{
    MUSART_vTransmitString(Bluetooth_UART_ID, A_ptrc8String) ;
}
References Bluetooth_UART_ID, and MUSART_vTransmitString().
Referenced by AACC_vModeON(), AExit_vCriteriaON(), AFCW_vModeON(), AMobApp_vCntrlCar(), AMobApp_vInit(), AMobApp_vSendSpeedValue(), ANCC_vModeON(), and ATraditional_vModeON().
HBluetooth_vReceiveString()
void HBluetooth_vReceiveString (c8_t A_c8YourString[])
Definition at line 100 of file Bluetooth_program.c.
{
    MUSART_vRecieveString(Bluetooth_UART_ID, A_c8YourString) ;
}
References Bluetooth_UART_ID, and MUSART_vRecieveString().
HBluetooth_u8CompStrings()
u8_t HBluetooth_u8CompStrings (c8_t * String1, c8_t * String2)
Definition at line 110 of file Bluetooth_program.c.
{
    u8_t L_u8Result = INITIAL_ZERO ;
    L_u8Result = MUSART_u8CompareString(String1, String2) ;
    return L_u8Result ;
}
References INITIAL_ZERO, and MUSART_u8CompareString().
HBluetooth_vEnable()
void HBluetooth_vEnable (void)
Definition at line 124 of file Bluetooth_program.c.
{
    MUSART_vEnable(Bluetooth_UART_ID) ;
}
References Bluetooth_UART_ID, and MUSART_vEnable().
HBluetooth_vDisable()
void HBluetooth_vDisable (void)
Definition at line 134 of file Bluetooth_program.c.
{
    MUSART_vDisable(Bluetooth_UART_ID) ;
}
References Bluetooth_UART_ID, and MUSART_vDisable().
HBluetooth_vEnableAsynchReceive()
void HBluetooth_vEnableAsynchReceive (void)
Definition at line 158 of file Bluetooth_program.c.
{
    // RXNEIE Pending Flag Enabled:
    MUSART_vRxIntSetStatus(Bluetooth_UART_ID, ENABLE) ;
    // USART1 IRQ Active Flag Enabled:
    MNVIC_vEnablePeriphral(USART1) ;
}
References Bluetooth_UART_ID, ENABLE, MNVIC_vEnablePeriphral(), MUSART_vRxIntSetStatus(), and USART1.
Referenced by AACC_vModeON(), and AFCW_vModeON().
HBluetooth_vDisableAsynchReceive()
void HBluetooth_vDisableAsynchReceive (void)
Definition at line 172 of file Bluetooth_program.c.
{
    // RXNEIE Pending Flag Disabled:
    MUSART_vRxIntSetStatus(Bluetooth_UART_ID, DISABLE) ;
    // USART1 IRQ Active Flag Disabled:
    MNVIC_vDisablePeriphral(USART1) ;
}
References Bluetooth_UART_ID, DISABLE, MNVIC_vDisablePeriphral(), MUSART_vRxIntSetStatus(), and USART1.
Referenced by AMobApp_vCntrlCar().
HBluetooth_u8GetDataRegister()
u8_t HBluetooth_u8GetDataRegister (void)
Definition at line 144 of file Bluetooth_program.c.
{
    u8_t volatile L_u8ReceivedByte = INITIAL_ZERO ;
    L_u8ReceivedByte = MUSART_u8ReadDataRegister(USART1_REG) ;
    return L_u8ReceivedByte ;
}
References INITIAL_ZERO, MUSART_u8ReadDataRegister(), and USART1_REG.