COTS/HAL/CarControl/CarControl_interface.h File Reference
Functions
void HCarControl_vInitCar (void)
void HCarControl_vMoveForward (void)
void HCarControl_vMoveBackward (void)
void HCarControl_vTurnRight (void)
void HCarControl_vTurnLeft (void)
void HCarControl_vStopCar (void)
Function Documentation
HCarControl_vInitCar()
void HCarControl_vInitCar (void)
Definition at line 61 of file CarControl_program.c.
{
    HDCM_vInitMotor(&dcmMotor1);
    HDCM_vInitMotor(&dcmMotor2);
    HDCM_vInitMotor(&dcmMotor3);
    HDCM_vInitMotor(&dcmMotor4);
}
References dcmMotor1, dcmMotor2, dcmMotor3, dcmMotor4, and HDCM_vInitMotor().
HCarControl_vMoveForward()
void HCarControl_vMoveForward (void)
Definition at line 69 of file CarControl_program.c.
{
    HDCM_vMoveForward(&dcmMotor1);
    HDCM_vMoveForward(&dcmMotor2);
    HDCM_vMoveForward(&dcmMotor3);
    HDCM_vMoveForward(&dcmMotor4);
}
References dcmMotor1, dcmMotor2, dcmMotor3, dcmMotor4, and HDCM_vMoveForward().
HCarControl_vMoveBackward()
void HCarControl_vMoveBackward (void)
Definition at line 77 of file CarControl_program.c.
{
    HDCM_vMoveBackward(&dcmMotor1);
    HDCM_vMoveBackward(&dcmMotor2);
    HDCM_vMoveBackward(&dcmMotor3);
    HDCM_vMoveBackward(&dcmMotor4);
}
References dcmMotor1, dcmMotor2, dcmMotor3, dcmMotor4, and HDCM_vMoveBackward().
HCarControl_vTurnRight()
void HCarControl_vTurnRight (void)
Definition at line 85 of file CarControl_program.c.
{
    HDCM_vMoveForward(&dcmMotor1);
    HDCM_vMoveBackward(&dcmMotor2);
    HDCM_vMoveForward(&dcmMotor3);
    HDCM_vMoveBackward(&dcmMotor4);
}
References dcmMotor1, dcmMotor2, dcmMotor3, dcmMotor4, HDCM_vMoveBackward(), and HDCM_vMoveForward().
HCarControl_vTurnLeft()
void HCarControl_vTurnLeft (void)
Definition at line 93 of file CarControl_program.c.
{
    HDCM_vMoveBackward(&dcmMotor1);
    HDCM_vMoveForward(&dcmMotor2);
    HDCM_vMoveBackward(&dcmMotor3);
    HDCM_vMoveForward(&dcmMotor4);
}
References dcmMotor1, dcmMotor2, dcmMotor3, dcmMotor4, HDCM_vMoveBackward(), and HDCM_vMoveForward().
HCarControl_vStopCar()
void HCarControl_vStopCar (void)
Definition at line 101 of file CarControl_program.c.
{
    HDCM_vStopMotor(&dcmMotor1);
    HDCM_vStopMotor(&dcmMotor2);
    HDCM_vStopMotor(&dcmMotor3);
    HDCM_vStopMotor(&dcmMotor4);
}
References dcmMotor1, dcmMotor2, dcmMotor3, dcmMotor4, and HDCM_vStopMotor().