COTS/HAL/Car_Movement/Car_Movement_interface.h File Reference
Functions
void HCarMove_vInit (void)
void HCarMove_vSpeedRatio (VAR(u16_t) A_u16SpeedRatio)
void HCarMove_vForward (void)
void HCarMove_vBackward (void)
void HCarMove_vRight (void)
void HCarMove_vLeft (void)
void HCarMove_vStop (void)
u32_t HCarMove_u32GetCarSpeed (void)
Function Documentation
HCarMove_vInit()
void HCarMove_vInit (void)
Definition at line 30 of file Car_Movement_program.c.
{
    HDCM_vInitMotor(&Motor1) ;
    HDCM_vInitMotor(&Motor3) ;
}
References HDCM_vInitMotor().
HCarMove_vSpeedRatio()
void HCarMove_vSpeedRatio (VAR(u16_t) A_u16SpeedRatio)
Referenced by AACC_vModeON(), AFCW_vModeON(), ANCC_vModeON(), and ATraditional_vModeON().
HCarMove_vForward()
void HCarMove_vForward (void)
Definition at line 52 of file Car_Movement_program.c.
{
    /* IN1 = 1, IN2 = 0, IN3 = 1, IN4 = 0 */
    HDCM_vMoveForward(&Motor1) ;
    HDCM_vMoveForward(&Motor3) ;
}
References HDCM_vMoveForward().
Referenced by AACC_vModeON(), AFCW_vModeON(), ANCC_vModeON(), and ATraditional_vModeON().
HCarMove_vBackward()
void HCarMove_vBackward (void)
Definition at line 65 of file Car_Movement_program.c.
{
    /* IN1 = 0, IN2 = 1, IN3 = 0, IN4 = 1 */
    HDCM_vMoveBackward(&Motor1) ;
    HDCM_vMoveBackward(&Motor3) ;
}
References HDCM_vMoveBackward().
Referenced by AFCW_vModeON(), and ATraditional_vModeON().
HCarMove_vRight()
void HCarMove_vRight (void)
Definition at line 78 of file Car_Movement_program.c.
{
    /* IN1 = 1, IN2 = 0, IN3 = 0, IN4 = 0 */
    HDCM_vMoveForward(&Motor1) ;
    HDCM_vStopMotor (&Motor3) ;
}
References HDCM_vMoveForward(), and HDCM_vStopMotor().
Referenced by AFCW_vModeON(), and ATraditional_vModeON().
HCarMove_vLeft()
void HCarMove_vLeft (void)
Definition at line 91 of file Car_Movement_program.c.
{
    /* IN1 = 0, IN2 = 0, IN3 = 1, IN4 = 0 */
    HDCM_vStopMotor (&Motor1) ;
    HDCM_vMoveForward(&Motor3) ;
}
References HDCM_vMoveForward(), and HDCM_vStopMotor().
Referenced by AFCW_vModeON(), and ATraditional_vModeON().
HCarMove_vStop()
void HCarMove_vStop (void)
Definition at line 104 of file Car_Movement_program.c.
{
    /* IN1 = 0, IN2 = 0, IN3 = 0, IN4 = 0 */
    HDCM_vStopMotor(&Motor1) ;
    HDCM_vStopMotor(&Motor3) ;
}
References HDCM_vStopMotor().
Referenced by AACC_vModeON(), AExit_vCriteriaON(), AFCW_vModeON(), ANCC_vModeON(), and ATraditional_vModeON().
HCarMove_u32GetCarSpeed()
u32_t HCarMove_u32GetCarSpeed (void)
Definition at line 117 of file Car_Movement_program.c.
{
    u32_t L_u32SpeedValue = INITIAL_ZERO ;
    L_u32SpeedValue = HDCM_vGetSpeedValue(&Motor1) ;
    return L_u32SpeedValue ;
}
References HDCM_vGetSpeedValue(), INITIAL_ZERO, and L_u32SpeedValue.
Referenced by AACC_vModeON(), AFCW_vModeON(), ANCC_vModeON(), and ATraditional_vModeON().