COTS/HAL/DCMOTOR/DCM_program.c File Reference
This file contains the source code of the interfacing information for the DC Motor module.
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `../../MCAL/SysTick/SysTick_interface.h`
#include `../../MCAL/TIM1/TIM1_interface.h`
#include `../../HAL/UltraSonic/UltraSonic_interface.h`
#include `DCM_interface.h`
#include `DCM_private.h`
#include `DCM_config.h`
Functions
void HDCM_vInitMotor (DCM_MotorConfiguration *pMotorConfiguration)
Initialize a motor Initialize a motor with a certain GPIO Port & Pin based on the passed motor configuration.
void HDCM_vMoveForward (DCM_MotorConfiguration *pMotorConfiguration)
Move a certain motor forward.
void HDCM_vMoveBackward (DCM_MotorConfiguration *pMotorConfiguration)
Move a certain motor backward.
void HDCM_vStopMotor (DCM_MotorConfiguration *pMotorConfiguration)
Stop a certain motor's movement completely.
void HDCM_vMotorSpeedCntrl (DCM_MotorConfiguration *pMotorConfiguration, u16_t A_u16SpeedValue)
Set a certain motor's speed.
u32_t HDCM_vGetSpeedValue (DCM_MotorConfiguration *pMotorConfiguration)
Get a certain motor's speed.
Detailed Description
This file contains the source code of the interfacing information for the DC Motor module.
Author
Mohamed Alaa
Version
1.0
Date
8/12/2022
Definition in file DCM_program.c.
Function Documentation
HDCM_vInitMotor()
void HDCM_vInitMotor (DCM_MotorConfiguration * pMotorConfiguration)
Initialize a motor Initialize a motor with a certain GPIO Port & Pin based on the passed motor configuration.
Parameters
 in pMotorConfiguration The motor configuration to be initialized
See also
DCM_MotorConfiguration
Definition at line 32 of file DCM_program.c.
{
    VAR(MGPIOx_ConfigType) DCMotorPin1Init =
        {
            .Port = pMotorConfiguration->u8Port,
            .Pin = pMotorConfiguration->u8Pin1,
            .Mode = GPIOx_MODE_OUTPUT,
            .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_LowSpeed,
            .InputType = GPIOx_NoPull};
    VAR(MGPIOx_ConfigType) DCMotorPin2Init =
        {
            .Port = pMotorConfiguration->u8Port,
            .Pin = pMotorConfiguration->u8Pin2,
            .Mode = GPIOx_MODE_OUTPUT,
            .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_LowSpeed,
            .InputType = GPIOx_NoPull};
    MGPIOx_vInit(&DCMotorPin1Init);
    MGPIOx_vInit(&DCMotorPin2Init);
    // Give an initial direction to the DC Motor:
    switch (pMotorConfiguration->u8Direction)
    {
    case FORWARD:
        HDCM_vMoveForward(pMotorConfiguration);
        break;
    case BACKWARD:
        HDCM_vMoveBackward(pMotorConfiguration);
        break;
    /* Default case: stop the motor */
    default:
        HDCM_vStopMotor(pMotorConfiguration);
        break;
    }
    // Give an initial speed to the DC Motor:
    HDCM_vMotorSpeedCntrl(pMotorConfiguration, pMotorConfiguration->u32SpeedRatio);
}
References BACKWARD, FORWARD, GPIOx_LowSpeed, GPIOx_MODE_OUTPUT, GPIOx_NoPull, GPIOx_PUSHPULL, HDCM_vMotorSpeedCntrl(), HDCM_vMoveBackward(), HDCM_vMoveForward(), HDCM_vStopMotor(), MGPIOx_vInit(), DCM_MotorConfiguration::u32SpeedRatio, DCM_MotorConfiguration::u8Direction, DCM_MotorConfiguration::u8Pin1, DCM_MotorConfiguration::u8Pin2, DCM_MotorConfiguration::u8Port, and VAR.
HDCM_vMoveForward()
void HDCM_vMoveForward (DCM_MotorConfiguration * pMotorConfiguration)
Move a certain motor forward.
Parameters
 in pMotorConfiguration The motor's configuration to move forward
Definition at line 81 of file DCM_program.c.
{
    MGPIOx_vSetPinValue(pMotorConfiguration->u8Port, pMotorConfiguration->u8Pin1, GPIOx_HIGH);
    MGPIOx_vSetPinValue(pMotorConfiguration->u8Port, pMotorConfiguration->u8Pin2, GPIOx_LOW);
}
References GPIOx_HIGH, GPIOx_LOW, MGPIOx_vSetPinValue(), DCM_MotorConfiguration::u8Pin1, DCM_MotorConfiguration::u8Pin2, and DCM_MotorConfiguration::u8Port.
Referenced by HDCM_vInitMotor().
HDCM_vMoveBackward()
void HDCM_vMoveBackward (DCM_MotorConfiguration * pMotorConfiguration)
Move a certain motor backward.
Parameters
 in pMotorConfiguration The motor's configuration to move backward
Definition at line 90 of file DCM_program.c.
{
    MGPIOx_vSetPinValue(pMotorConfiguration->u8Port, pMotorConfiguration->u8Pin1, GPIOx_LOW);
    MGPIOx_vSetPinValue(pMotorConfiguration->u8Port, pMotorConfiguration->u8Pin2, GPIOx_HIGH);
}
References GPIOx_HIGH, GPIOx_LOW, MGPIOx_vSetPinValue(), DCM_MotorConfiguration::u8Pin1, DCM_MotorConfiguration::u8Pin2, and DCM_MotorConfiguration::u8Port.
Referenced by HDCM_vInitMotor().
HDCM_vStopMotor()
void HDCM_vStopMotor (DCM_MotorConfiguration * pMotorConfiguration)
Stop a certain motor's movement completely.
Parameters
 in pMotorConfiguration The motor's configuration to stop
Definition at line 99 of file DCM_program.c.
{
    MGPIOx_vSetPinValue(pMotorConfiguration->u8Port, pMotorConfiguration->u8Pin1, GPIOx_LOW);
    MGPIOx_vSetPinValue(pMotorConfiguration->u8Port, pMotorConfiguration->u8Pin2, GPIOx_LOW);
}
References GPIOx_LOW, MGPIOx_vSetPinValue(), DCM_MotorConfiguration::u8Pin1, DCM_MotorConfiguration::u8Pin2, and DCM_MotorConfiguration::u8Port.
Referenced by HDCM_vInitMotor().
HDCM_vMotorSpeedCntrl()
void HDCM_vMotorSpeedCntrl (DCM_MotorConfiguration * pMotorConfiguration, u16_t A_u16SpeedValue)
Set a certain motor's speed.
Parameters
 in pMotorConfiguration The motor's configuration to set its speed
 in A_u16SpeedValue The speed value to set the motor to
Definition at line 108 of file DCM_program.c.
{
    VAR(HULTSNC_ConfigType) TRIG =
        {
            .u8Port = GPIO_PORTB,
            .u8Pin = GPIOx_PIN8};
    MTIM1_vGeneratePWM(pMotorConfiguration->u8SpeedPin, PWM1, CENTER1,
                       PSC_VALUE, MAX_SPEED, CR_VALUE);
    HULTSNC_vInit(&TRIG);
    switch (pMotorConfiguration->u8SpeedPin)
    {
    case TIM1_CH1:
        MTIM1_vSetCompareReg1Value(A_u16SpeedValue);
        break;
    case TIM1_CH2:
        MTIM1_vSetCompareReg2Value(A_u16SpeedValue);
        break;
    case TIM1_CH3:
        MTIM1_vSetCompareReg3Value(A_u16SpeedValue);
        break;
    case TIM1_CH4:
        MTIM1_vSetCompareReg4Value(A_u16SpeedValue);
        break;
    default:
        break;
    }
}
References GPIO_PORTB, GPIOx_PIN8, HULTSNC_vInit(), MAX_SPEED, DCM_MotorConfiguration::u8SpeedPin, and VAR.
Referenced by HDCM_vInitMotor().
HDCM_vGetSpeedValue()
u32_t HDCM_vGetSpeedValue (DCM_MotorConfiguration * pMotorConfiguration)
Get a certain motor's speed.
Parameters
 in pMotorConfiguration The motor's configuration to get its speed
Returns
The speed value of the motor
Definition at line 148 of file DCM_program.c.
{
    u32_t L_u32SpeedValue = INITIAL_ZERO;
    switch (pMotorConfiguration->u8SpeedPin)
    {
    case TIM1_CH1:
        L_u32SpeedValue = MTIM1_u16GetCaptureReg1Value();
        break;
    case TIM1_CH2:
        L_u32SpeedValue = MTIM1_u16GetCaptureReg2Value();
        break;
    case TIM1_CH3:
        L_u32SpeedValue = MTIM1_u16GetCaptureReg3Value();
        break;
    case TIM1_CH4:
        L_u32SpeedValue = MTIM1_u16GetCaptureReg4Value();
        break;
    default: /* Do nothing */
        break;
    }
    return L_u32SpeedValue;
}
References INITIAL_ZERO, and DCM_MotorConfiguration::u8SpeedPin.