COTS/MCAL/EXTI/EXTI_program.c File Reference
This file contains the source code of the interfacing for the EXTI module.
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `EXTI_interface.h`
#include `EXTI_private.h`
#include `EXTI_config.h`
#include `SYSCFG_private.h`
Functions
void MSYSCFG_vSetEXTIPort (u8_t A_u8LineID, u8_t A_u8PortID)
Enable the interrupt on a certain line in a certain port.
void MEXTI_vInit (void)
Initialize the EXTI module.
void MEXTI_vInit_WithStruct (EXTI_ConfigType *A_xINTConfig)
Initialize the EXTI module with a certain configuration.
void MEXTI_vEnableLine (u8_t A_u8LineID, u8_t A_u8TriggerStatus)
Enable the interrupt on a certain line ID with a certain trigger status.
void MEXTI_vDisableLine (u8_t A_u8LineID)
Disable the interrupt on a certain line ID.
void MEXTI_vSWITrigger (u8_t A_u8LineID)
perform a software event interrupt on a certain line
void MEXTI_vSetTrigger (u8_t A_u8LineID, u8_t A_u8TriggerStatus)
Set the trigger status interrupt on a certain line ID.
void MEXTI_vSetCallback (u8_t A_u8LineID, void(*A_vFptr)(void))
Set the callback when an interrupt occurs on a certain line ID.
void EXTI0_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 0 module.
void EXTI1_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 1 module.
void EXTI2_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 2 module.
void EXTI3_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 3 module.
void EXTI4_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 4 module.
void EXTI9_5_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 5-9 module.
void EXTI15_10_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 10-15 module.
Detailed Description
This file contains the source code of the interfacing for the EXTI module.
Author
Ali El Bana
Version
1.0
Date
09/02/2022
Definition in file EXTI_program.c.
Function Documentation
MSYSCFG_vSetEXTIPort()
void MSYSCFG_vSetEXTIPort (u8_t A_u8LineID, u8_t A_u8PortID)
Enable the interrupt on a certain line in a certain port.
Parameters
 in A_u8LineID The line ID to to enable the interrupt onto
 in A_u8PortID Port that the line belongs to
Definition at line 28 of file EXTI_program.c.
{
    u8_t L_u8Index = A_u8LineID / 4;
    u8_t L_u8ShiftAmount = A_u8LineID % 4;
    CLR_BITs(MSYSCFG->EXTICR[L_u8Index], 0b1111, L_u8ShiftAmount, 4);
    SET_BITs(MSYSCFG->EXTICR[L_u8Index], A_u8PortID, L_u8ShiftAmount, 4);
}
References CLR_BITs, MSYSCFG, and SET_BITs.
Referenced by MEXTI_vInit_WithStruct().
MEXTI_vInit()
void MEXTI_vInit (void)
Initialize the EXTI module.
Definition at line 40 of file EXTI_program.c.
{
    u8_t L_u8ShiftedOffset = INITIAL_ZERO;
#if EXTI_LINE0_EN == ENABLE
    L_u8ShiftedOffset = 0;
#elif EXTI_LINE1_EN == ENABLE
    L_u8ShiftedOffset = 1;
#elif EXTI_LINE2_EN == ENABLE
    L_u8ShiftedOffset = 2;
#elif EXTI_LINE3_EN == ENABLE
    L_u8ShiftedOffset = 3;
#elif EXTI_LINE4_EN == ENABLE
    L_u8ShiftedOffset = 4;
#elif EXTI_LINE5_EN == ENABLE
    L_u8ShiftedOffset = 5;
#elif EXTI_LINE6_EN == ENABLE
    L_u8ShiftedOffset = 6;
#elif EXTI_LINE7_EN == ENABLE
    L_u8ShiftedOffset = 7;
#elif EXTI_LINE8_EN == ENABLE
    L_u8ShiftedOffset = 8;
#elif EXTI_LINE9_EN == ENABLE
    L_u8ShiftedOffset = 9;
#elif EXTI_LINE10_EN == ENABLE
    L_u8ShiftedOffset = 10;
#elif EXTI_LINE11_EN == ENABLE
    L_u8ShiftedOffset = 11;
#elif EXTI_LINE12_EN == ENABLE
    L_u8ShiftedOffset = 12;
#elif EXTI_LINE13_EN == ENABLE
    L_u8ShiftedOffset = 13;
#elif EXTI_LINE14_EN == ENABLE
    L_u8ShiftedOffset = 14;
#elif EXTI_LINE15_EN == ENABLE
    L_u8ShiftedOffset = 15;
#endif
    // Get the enabled line ID.
    // GS_u8EXTI_EnabledLine_ID = L_u8ShiftedOffset;
    // Clear all flags.
    MEXTI->PR = 0xffffffff;
    // Enable EXTI on a line.
    MEXTI->IMR = 0;
    MEXTI->IMR |= (ENABLE << L_u8ShiftedOffset);
// Set EXTI Triggered status on a line.
#if EXTI_LINE0_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE0_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE0_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE1_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE1_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE1_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE2_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE2_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE2_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE3_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE3_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE3_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE4_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE4_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE4_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE5_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE5_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE5_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE6_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE6_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE6_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE7_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE7_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE7_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE8_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE8_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE8_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE9_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE9_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE9_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE10_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE10_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE10_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE11_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE11_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE11_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE12_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE12_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE12_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE13_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE13_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE13_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE14_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE14_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE14_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE15_TRIGGER == EXTI_RisingEdge
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
#elif EXTI_LINE15_TRIGGER == EXTI_FallingEdge
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#elif EXTI_LINE15_TRIGGER == EXTI_OnChange
    SET_BIT(MEXTI->RTSR, L_u8ShiftedOffset);
    SET_BIT(MEXTI->FTSR, L_u8ShiftedOffset);
#endif
}
References INITIAL_ZERO, MEXTI, and SET_BIT.
MEXTI_vInit_WithStruct()
void MEXTI_vInit_WithStruct (EXTI_ConfigType * A_xINTConfig)
Initialize the EXTI module with a certain configuration.
Parameters
 in A_xINTConfig The configuration structure to initialize the interrupt with
Definition at line 273 of file EXTI_program.c.
{
    MEXTI_vEnableLine(A_xINTConfig->LineNum, A_xINTConfig->TriggerStatus);
    MSYSCFG_vSetEXTIPort(A_xINTConfig->LineNum, A_xINTConfig->PortNum);
}
References EXTI_ConfigType::LineNum, MEXTI_vEnableLine(), MSYSCFG_vSetEXTIPort(), EXTI_ConfigType::PortNum, and EXTI_ConfigType::TriggerStatus.
MEXTI_vEnableLine()
void MEXTI_vEnableLine (u8_t A_u8LineID, u8_t A_u8TriggerStatus)
Enable the interrupt on a certain line ID with a certain trigger status.
Parameters
 in A_u8LineID The line ID to enable the interrupt on
 in A_u8TriggerStatus The trigger status to trigger when the interrupt occurs
Definition at line 284 of file EXTI_program.c.
{
    if (A_u8LineID < EXTI_MAX_EXTI_NUM)
    {
        SET_BIT(MEXTI->IMR, A_u8LineID);
        MEXTI_vSetTrigger(A_u8LineID, A_u8TriggerStatus);
    }
}
References EXTI_MAX_EXTI_NUM, MEXTI, MEXTI_vSetTrigger(), and SET_BIT.
Referenced by MEXTI_vInit_WithStruct().
MEXTI_vDisableLine()
void MEXTI_vDisableLine (u8_t A_u8LineID)
Disable the interrupt on a certain line ID.
Parameters
 in A_u8LineID Which line to disable the interrupt on
Definition at line 299 of file EXTI_program.c.
{
    if (A_u8LineID < EXTI_MAX_EXTI_NUM)
    {
        CLR_BIT(MEXTI->IMR, A_u8LineID);
    }
}
References CLR_BIT, EXTI_MAX_EXTI_NUM, and MEXTI.
MEXTI_vSWITrigger()
void MEXTI_vSWITrigger (u8_t A_u8LineID)
perform a software event interrupt on a certain line
Parameters
 in A_u8LineID The line ID to perform the software event interrupt on
Definition at line 311 of file EXTI_program.c.
{
    if (A_u8LineID < EXTI_MAX_EXTI_NUM)
    {
        SET_BIT(MEXTI->SWIER, A_u8LineID);
    }
}
References EXTI_MAX_EXTI_NUM, MEXTI, and SET_BIT.
MEXTI_vSetTrigger()
void MEXTI_vSetTrigger (u8_t A_u8LineID, u8_t A_u8TriggerStatus)
Set the trigger status interrupt on a certain line ID.
Parameters
 in A_u8LineID The line ID to enable the interrupt on
 in A_u8TriggerStatus The trigger status to trigger when the interrupt occurs
Definition at line 323 of file EXTI_program.c.
{
    if (A_u8LineID < EXTI_MAX_EXTI_NUM)
    {
        switch (A_u8TriggerStatus)
        {
        case EXTI_RisingEdge:
            SET_BIT(MEXTI->RTSR, A_u8LineID);
            CLR_BIT(MEXTI->FTSR, A_u8LineID);
            break;
        case EXTI_FallingEdge:
            SET_BIT(MEXTI->FTSR, A_u8LineID);
            CLR_BIT(MEXTI->RTSR, A_u8LineID);
            break;
        case EXTI_OnChange:
            SET_BIT(MEXTI->RTSR, A_u8LineID);
            SET_BIT(MEXTI->FTSR, A_u8LineID);
            break;
        }
    }
}
References CLR_BIT, EXTI_FallingEdge, EXTI_MAX_EXTI_NUM, EXTI_OnChange, EXTI_RisingEdge, MEXTI, and SET_BIT.
Referenced by MEXTI_vEnableLine().
MEXTI_vSetCallback()
void MEXTI_vSetCallback (u8_t A_u8LineID, void(*)(void) A_vFptr)
Set the callback when an interrupt occurs on a certain line ID.
Parameters
 in A_u8LineID The line ID to set the callback on
 in A_vFptr The callback to call when the interrupt occurs on a certain line
Definition at line 355 of file EXTI_program.c.
{
    if (A_u8LineID < EXTI_MAX_EXTI_NUM)
    {
        GS_vEXTI_Callback[A_u8LineID] = A_vFptr;
    }
}
References EXTI_MAX_EXTI_NUM.
EXTI0_IRQHandler()
void EXTI0_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 0 module.
Definition at line 371 of file EXTI_program.c.
{
    if (GS_vEXTI_Callback[EXTI_LINE0] != NULL)
    {
        GS_vEXTI_Callback[EXTI_LINE0]();
    }
    // Clear the flag.
    SET_BIT(MEXTI->PR, EXTI_LINE0);
}
References EXTI_LINE0, MEXTI, NULL, and SET_BIT.
EXTI1_IRQHandler()
void EXTI1_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 1 module.
Definition at line 390 of file EXTI_program.c.
{
    if (GS_vEXTI_Callback[EXTI_LINE1] != NULL)
    {
        GS_vEXTI_Callback[EXTI_LINE1]();
    }
    // Clear the flag.
    SET_BIT(MEXTI->PR, EXTI_LINE1);
}
References EXTI_LINE1, MEXTI, NULL, and SET_BIT.
EXTI2_IRQHandler()
void EXTI2_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 2 module.
Definition at line 409 of file EXTI_program.c.
{
    if (GS_vEXTI_Callback[EXTI_LINE2] != NULL)
    {
        GS_vEXTI_Callback[EXTI_LINE2]();
    }
    // Clear the flag.
    SET_BIT(MEXTI->PR, EXTI_LINE2);
}
References EXTI_LINE2, MEXTI, NULL, and SET_BIT.
EXTI3_IRQHandler()
void EXTI3_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 3 module.
Definition at line 428 of file EXTI_program.c.
{
    if (GS_vEXTI_Callback[EXTI_LINE3] != NULL)
    {
        GS_vEXTI_Callback[EXTI_LINE3]();
    }
    // Clear the flag.
    SET_BIT(MEXTI->PR, EXTI_LINE3);
}
References EXTI_LINE3, MEXTI, NULL, and SET_BIT.
EXTI4_IRQHandler()
void EXTI4_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 4 module.
Definition at line 447 of file EXTI_program.c.
{
    if (GS_vEXTI_Callback[EXTI_LINE4] != NULL)
    {
        GS_vEXTI_Callback[EXTI_LINE4]();
    }
    // Clear the flag.
    SET_BIT(MEXTI->PR, EXTI_LINE4);
}
References EXTI_LINE4, MEXTI, NULL, and SET_BIT.
EXTI9_5_IRQHandler()
void EXTI9_5_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 5-9 module.
Definition at line 466 of file EXTI_program.c.
{
}
EXTI15_10_IRQHandler()
void EXTI15_10_IRQHandler (void)
This function is responsible for clearing the pending flag of the External interrupt 10-15 module.
Definition at line 477 of file EXTI_program.c.
{
}