COTS/APP/Exit_State/Exit_State_interface.h File Reference
Functions
void AExit_vCriteriaON (void)
Function Documentation
AExit_vCriteriaON()
void AExit_vCriteriaON (void)
Definition at line 37 of file Exit_State_program.c.
{
    HBluetooth_vSendString("\nActivate Exit Criteria\n") ;
    HCarMove_vStop() ;
    HBUZZER_vSoundOff(&Buzzer) ;
}
References HBluetooth_vSendString(), HBUZZER_vSoundOff(), and HCarMove_vStop().