COTS/APP/FCW/FCW_interface.h File Reference
Functions
void AFCW_vModeON (void)
Function Documentation
AFCW_vModeON()
void AFCW_vModeON (void)
Definition at line 61 of file FCW_program.c.
{
    u32_t L_u32SpeedValue = INITIAL_ZERO ;
    f32_t L_f32Distance = INITIAL_ZERO ;
    G_c8RecievedButton = INITIAL_ZERO ;
    GV_u8InISR = FALSE ;
    HBUZZER_vInit(&Buzzer) ;
    HBluetooth_vEnableAsynchReceive() ;
    HBluetooth_u8AsynchReceiveByte(&Button_vCurrentData) ;
    HBluetooth_vSendString("\nFCW Mode ON\n") ;
    do
    {
        HULTSNC_vTrigger(&TRIG) ;
        L_f32Distance = HULTSNC_f32GetDistance() ;
        if(L_f32Distance < FCW_SAFE_DIST)
        {
            HBUZZER_vSoundOn(&Buzzer) ;
        }
        else if(L_f32Distance >= FCW_SAFE_DIST + HYSTRS_VALUE)
        {
            HBUZZER_vSoundOff(&Buzzer) ;
        }
        else
        {
            /* Do Nothing */
        }
        if(GV_u8InISR == TRUE)
        {
            GV_u8InISR = FALSE ;
            switch(G_c8RecievedButton)
            {
                case FORW_CHAR:
                    HCarMove_vForward() ;
                    L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                    AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                break ;
                case BACKW_CHAR:
                    HCarMove_vBackward() ;
                    L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                    AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                break ;
                case RIGHT_CHAR:
                    HCarMove_vRight() ;
                    L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                    AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                break ;
                case LEFT_CHAR:
                    HCarMove_vLeft() ;
                    L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                    AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                break ;
                case STOP_CHAR:
                    HCarMove_vStop() ;
                    HBluetooth_vSendString(SPEED0_STR) ;
                break ;
                case EXIT_MODE_CHAR:
                    HBUZZER_vSoundOff(&Buzzer) ;
                    HCarMove_vStop() ;
                    HBluetooth_vSendString(SPEED0_STR) ;
                    HBluetooth_u8AsynchReceiveByte(NULL) ;
                break ;
                case INC_SPEED_CHAR:
                    L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                    if(L_u32SpeedValue >= SPEED_100_PERCENT)
                    {
                        L_u32SpeedValue = SPEED_100_PERCENT ;
                        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                    }
                    else
                    {
                        L_u32SpeedValue += SPEED_10_PERCENT ;
                        HCarMove_vSpeedRatio(L_u32SpeedValue) ;
                        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                    }
                break ;
                case DEC_SPEED_CHAR:
                    L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                    if(L_u32SpeedValue <= SPEED_0_PERCENT)
                    {
                        L_u32SpeedValue = SPEED_0_PERCENT ;
                        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                    }
                    else
                    {
                        L_u32SpeedValue -= SPEED_10_PERCENT ;
                        HCarMove_vSpeedRatio(L_u32SpeedValue) ;
                        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                    }
                break ;
                default: /* Do Nothing */ break ;
            }
        }
        else
        {
            /* Do nothing */
        }
    }while(G_c8RecievedButton != EXIT_MODE_CHAR) ;
}
References AMobApp_vSendSpeedValue(), BACKW_CHAR, DEC_SPEED_CHAR, EXIT_MODE_CHAR, FALSE, FCW_SAFE_DIST, FORW_CHAR, G_c8RecievedButton, GV_u8InISR, HBluetooth_u8AsynchReceiveByte(), HBluetooth_vEnableAsynchReceive(), HBluetooth_vSendString(), HBUZZER_vInit(), HBUZZER_vSoundOff(), HBUZZER_vSoundOn(), HCarMove_u32GetCarSpeed(), HCarMove_vBackward(), HCarMove_vForward(), HCarMove_vLeft(), HCarMove_vRight(), HCarMove_vSpeedRatio(), HCarMove_vStop(), HULTSNC_f32GetDistance(), HULTSNC_vTrigger(), HYSTRS_VALUE, INC_SPEED_CHAR, INITIAL_ZERO, L_f32Distance, L_u32SpeedValue, LEFT_CHAR, NULL, RIGHT_CHAR, SPEED0_STR, SPEED_0_PERCENT, SPEED_100_PERCENT, SPEED_10_PERCENT, STOP_CHAR, and TRUE.
Referenced by AMobApp_vCntrlCar().