COTS/HAL/LCD/LCD_interface.h File Reference
Macros
#define MIN_IDX_OF_ROWS 0
#define MAX_IDX_OF_ROWS 1
#define MIN_IDX_OF_COL 0
#define MAX_IDX_OF_COL 15
#define HLCD_LINE1 0
#define HLCD_LINE2 1
#define HLCD_Square1 0
#define HLCD_Square2 1
#define HLCD_Square3 2
#define HLCD_Square4 3
#define HLCD_Square5 4
#define HLCD_Square6 5
#define HLCD_Square7 6
#define HLCD_Square8 7
#define HLCD_Square9 8
#define HLCD_Square10 9
#define HLCD_Square11 10
#define HLCD_Square12 11
#define HLCD_Square13 12
#define HLCD_Square14 13
#define HLCD_Square15 14
#define HLCD_Square16 15
#define CGRAM_AddressOfPattern0 0
#define CGRAM_AddressOfPattern1 1
#define CGRAM_AddressOfPattern2 2
#define CGRAM_AddressOfPattern3 3
#define CGRAM_AddressOfPattern4 4
#define CGRAM_AddressOfPattern5 5
#define CGRAM_AddressOfPattern7 6
#define CGRAM_AddressOfPattern8 7
Functions
void HLCD_vInit (void)
void HLCD_vSendCommand (VAR(u8_t) A_u8Cmd)
void HLCD_vSendData (VAR(u8_t) A_u8Data)
void HLCD_vClear (void)
void HLCD_vDispString (P2VAR(c8_t) A_c8Char)
void HLCD_vDispNumber (VAR(s32_t) A_s32Num)
void HLCD_vSaveCustomChar (VAR(u8_t) A_u8Address, P2VAR(u8_t) A_u8CustomChar)
void HLCD_vSaveDispChar (VAR(u8_t) A_u8Address, P2VAR(u8_t) A_u8CustomChar)
void HLCD_vGoTo (VAR(u8_t) A_u8Row, VAR(u8_t) A_u8Col)
void HLCD_vSetShiftLeftOn (void)
void HLCD_vSetDispOFF (void)
void HLCD_vDispCursorWithBlinking (void)
void HLCD_vSetCursorBlinkingOFF (void)
void HLCD_vDispShiftLeftString (P2VAR(c8_t) A_c8Char)
void HLCD_vClearChar (VAR(u8_t) A_u8Row, VAR(u8_t) A_u8Col)
Macro Definition Documentation
MIN_IDX_OF_ROWS
#define MIN_IDX_OF_ROWS 0
Definition at line 50 of file LCD_interface.h.
MAX_IDX_OF_ROWS
#define MAX_IDX_OF_ROWS 1
Definition at line 52 of file LCD_interface.h.
MIN_IDX_OF_COL
#define MIN_IDX_OF_COL 0
Definition at line 54 of file LCD_interface.h.
MAX_IDX_OF_COL
#define MAX_IDX_OF_COL 15
Definition at line 56 of file LCD_interface.h.
HLCD_LINE1
#define HLCD_LINE1 0
Definition at line 59 of file LCD_interface.h.
HLCD_LINE2
#define HLCD_LINE2 1
Definition at line 61 of file LCD_interface.h.
HLCD_Square1
#define HLCD_Square1 0
Definition at line 64 of file LCD_interface.h.
HLCD_Square2
#define HLCD_Square2 1
Definition at line 66 of file LCD_interface.h.
HLCD_Square3
#define HLCD_Square3 2
Definition at line 68 of file LCD_interface.h.
HLCD_Square4
#define HLCD_Square4 3
Definition at line 70 of file LCD_interface.h.
HLCD_Square5
#define HLCD_Square5 4
Definition at line 72 of file LCD_interface.h.
HLCD_Square6
#define HLCD_Square6 5
Definition at line 74 of file LCD_interface.h.
HLCD_Square7
#define HLCD_Square7 6
Definition at line 76 of file LCD_interface.h.
HLCD_Square8
#define HLCD_Square8 7
Definition at line 78 of file LCD_interface.h.
HLCD_Square9
#define HLCD_Square9 8
Definition at line 80 of file LCD_interface.h.
HLCD_Square10
#define HLCD_Square10 9
Definition at line 82 of file LCD_interface.h.
HLCD_Square11
#define HLCD_Square11 10
Definition at line 84 of file LCD_interface.h.
HLCD_Square12
#define HLCD_Square12 11
Definition at line 86 of file LCD_interface.h.
HLCD_Square13
#define HLCD_Square13 12
Definition at line 88 of file LCD_interface.h.
HLCD_Square14
#define HLCD_Square14 13
Definition at line 90 of file LCD_interface.h.
HLCD_Square15
#define HLCD_Square15 14
Definition at line 92 of file LCD_interface.h.
HLCD_Square16
#define HLCD_Square16 15
Definition at line 94 of file LCD_interface.h.
CGRAM_AddressOfPattern0
#define CGRAM_AddressOfPattern0 0
Definition at line 97 of file LCD_interface.h.
CGRAM_AddressOfPattern1
#define CGRAM_AddressOfPattern1 1
Definition at line 99 of file LCD_interface.h.
CGRAM_AddressOfPattern2
#define CGRAM_AddressOfPattern2 2
Definition at line 101 of file LCD_interface.h.
CGRAM_AddressOfPattern3
#define CGRAM_AddressOfPattern3 3
Definition at line 103 of file LCD_interface.h.
CGRAM_AddressOfPattern4
#define CGRAM_AddressOfPattern4 4
Definition at line 105 of file LCD_interface.h.
CGRAM_AddressOfPattern5
#define CGRAM_AddressOfPattern5 5
Definition at line 107 of file LCD_interface.h.
CGRAM_AddressOfPattern7
#define CGRAM_AddressOfPattern7 6
Definition at line 109 of file LCD_interface.h.
CGRAM_AddressOfPattern8
#define CGRAM_AddressOfPattern8 7
Definition at line 111 of file LCD_interface.h.
Function Documentation
HLCD_vInit()
void HLCD_vInit (void)
Definition at line 30 of file LCD_program.c.
{
    MSysTick_vInit() ;
    MSysTick_vDelayMilliSec(1000) ;
    // Set your pin directions:
    MGPIOx_ConfigType RS =
    {
        .Port = HLCD_CTRL_PORT, .Pin = HLCD_RS_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType RW =
    {
        .Port = HLCD_CTRL_PORT, .Pin = HLCD_RW_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType EN =
    {
        .Port = HLCD_CTRL_PORT, .Pin = HLCD_EN_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D0 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D0_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D1 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D1_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D2 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D2_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D3 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D3_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D4 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D4_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D5 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D5_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D6 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D6_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D7 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D7_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_vInit(&RS) ;
    MGPIOx_vInit(&RW) ;
    MGPIOx_vInit(&EN) ;
    MGPIOx_vInit(&D0) ;
    MGPIOx_vInit(&D1) ;
    MGPIOx_vInit(&D2) ;
    MGPIOx_vInit(&D3) ;
    MGPIOx_vInit(&D4) ;
    MGPIOx_vInit(&D5) ;
    MGPIOx_vInit(&D6) ;
    MGPIOx_vInit(&D7) ;
    // Start initialization sequence.
    MSysTick_vDelayMilliSec(50) ;
    HLCD_vSendCommand(HLCD_FuctionSet_Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
    HLCD_vSendCommand(HLCD_DispOnOffCTRL_Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
    HLCD_vSendCommand(HLCD_DispClear_Cmd) ;
    MSysTick_vDelayMilliSec(3) ;
    HLCD_vSendCommand(HLCD_EntryModeSet_Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
}
References D0_PIN, D1_PIN, D2_PIN, D3_PIN, D4_PIN, D5_PIN, D6_PIN, D7_PIN, GPIOx_LowSpeed, GPIOx_MODE_OUTPUT, GPIOx_NoPull, GPIOx_PUSHPULL, HLCD_CTRL_PORT, HLCD_DATA_PORT, HLCD_DispClear_Cmd, HLCD_DispOnOffCTRL_Cmd, HLCD_EN_PIN, HLCD_EntryModeSet_Cmd, HLCD_FuctionSet_Cmd, HLCD_RS_PIN, HLCD_RW_PIN, HLCD_vSendCommand(), MGPIOx_vInit(), MSysTick_vDelayMilliSec(), MSysTick_vInit(), and MGPIOx_ConfigType::Port.
HLCD_vSendCommand()
void HLCD_vSendCommand (VAR(u8_t) A_u8Cmd)
HLCD_vSendData()
void HLCD_vSendData (VAR(u8_t) A_u8Data)
HLCD_vClear()
void HLCD_vClear (void)
Definition at line 224 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(1) ;
    HLCD_vSendCommand(HLCD_DispClear_Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
}
References HLCD_DispClear_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
HLCD_vDispString()
void HLCD_vDispString (P2VAR(c8_t) A_c8Char)
HLCD_vDispNumber()
void HLCD_vDispNumber (VAR(s32_t) A_s32Num)
HLCD_vSaveCustomChar()
void HLCD_vSaveCustomChar (VAR(u8_t) A_u8Address, P2VAR(u8_t) A_u8CustomChar)
HLCD_vSaveDispChar()
void HLCD_vSaveDispChar (VAR(u8_t) A_u8Address, P2VAR(u8_t) A_u8CustomChar)
HLCD_vGoTo()
void HLCD_vGoTo (VAR(u8_t) A_u8Row, VAR(u8_t) A_u8Col)
HLCD_vSetShiftLeftOn()
void HLCD_vSetShiftLeftOn (void)
Definition at line 385 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(500) ;
    HLCD_vSendCommand(HLCD_EntryModeSet_ShiftLeftOn_Cmd) ;
    MSysTick_vDelayMilliSec(500) ;
}
References HLCD_EntryModeSet_ShiftLeftOn_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
Referenced by HLCD_vDispShiftLeftString().
HLCD_vSetDispOFF()
void HLCD_vSetDispOFF (void)
Definition at line 400 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(500) ;
    HLCD_vSendCommand(HLCD_DispOff_Cmd) ;
    MSysTick_vDelayMilliSec(500) ;
}
References HLCD_DispOff_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
HLCD_vDispCursorWithBlinking()
void HLCD_vDispCursorWithBlinking (void)
Definition at line 415 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(500) ;
    HLCD_vSendCommand(HLCD_DispCursorWithBlinking_Cmd) ;
    MSysTick_vDelayMilliSec(500) ;
}
References HLCD_DispCursorWithBlinking_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
HLCD_vSetCursorBlinkingOFF()
void HLCD_vSetCursorBlinkingOFF (void)
Definition at line 429 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(500) ;
    HLCD_vSendCommand(HLCD_SetCursorBlinkingOFF_Cmd) ;
    MSysTick_vDelayMilliSec(500) ;
}
References HLCD_SetCursorBlinkingOFF_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
HLCD_vDispShiftLeftString()
void HLCD_vDispShiftLeftString (P2VAR(c8_t) A_c8Char)
HLCD_vClearChar()
void HLCD_vClearChar (VAR(u8_t) A_u8Row, VAR(u8_t) A_u8Col)