COTS/HAL/LCD/LCD_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../../MCAL/RCC/MRCC_interface.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `../../MCAL/SysTick/SysTick_interface.h`
#include `LCD_config.h`
#include `LCD_interface.h`
#include `LCD_private.h`
Functions
void HLCD_vInit (void)
void HLCD_vSendCommand (u8_t A_u8Cmd)
void HLCD_vSendData (u8_t A_u8Data)
void HLCD_vClear (void)
void HLCD_vDispString (c8_t *A_c8Char)
void HLCD_vDispNumber (s32_t A_s32Num)
void HLCD_vSaveCustomChar (u8_t A_u8Address, u8_t *A_u8CustomChar)
void HLCD_vGoTo (u8_t A_u8Row, u8_t A_u8Col)
void HLCD_vSetShiftLeftOn (void)
void HLCD_vSetDispOFF (void)
void HLCD_vDispCursorWithBlinking (void)
void HLCD_vSetCursorBlinkingOFF (void)
void HLCD_vDispShiftLeftString (c8_t *A_c8Char)
void HLCD_vClearChar (u8_t A_u8Row, u8_t A_u8Col)
Function Documentation
HLCD_vInit()
void HLCD_vInit (void)
Definition at line 30 of file LCD_program.c.
{
    MSysTick_vInit() ;
    MSysTick_vDelayMilliSec(1000) ;
    // Set your pin directions:
    MGPIOx_ConfigType RS =
    {
        .Port = HLCD_CTRL_PORT, .Pin = HLCD_RS_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType RW =
    {
        .Port = HLCD_CTRL_PORT, .Pin = HLCD_RW_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType EN =
    {
        .Port = HLCD_CTRL_PORT, .Pin = HLCD_EN_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D0 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D0_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D1 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D1_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D2 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D2_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D3 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D3_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D4 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D4_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D5 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D5_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D6 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D6_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_ConfigType D7 =
    {
        .Port = HLCD_DATA_PORT, .Pin = D7_PIN, .Mode = GPIOx_MODE_OUTPUT, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_LowSpeed,
        .InputType = GPIOx_NoPull
    } ;
    MGPIOx_vInit(&RS) ;
    MGPIOx_vInit(&RW) ;
    MGPIOx_vInit(&EN) ;
    MGPIOx_vInit(&D0) ;
    MGPIOx_vInit(&D1) ;
    MGPIOx_vInit(&D2) ;
    MGPIOx_vInit(&D3) ;
    MGPIOx_vInit(&D4) ;
    MGPIOx_vInit(&D5) ;
    MGPIOx_vInit(&D6) ;
    MGPIOx_vInit(&D7) ;
    // Start initialization sequence.
    MSysTick_vDelayMilliSec(50) ;
    HLCD_vSendCommand(HLCD_FuctionSet_Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
    HLCD_vSendCommand(HLCD_DispOnOffCTRL_Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
    HLCD_vSendCommand(HLCD_DispClear_Cmd) ;
    MSysTick_vDelayMilliSec(3) ;
    HLCD_vSendCommand(HLCD_EntryModeSet_Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
}
References D0_PIN, D1_PIN, D2_PIN, D3_PIN, D4_PIN, D5_PIN, D6_PIN, D7_PIN, GPIOx_LowSpeed, GPIOx_MODE_OUTPUT, GPIOx_NoPull, GPIOx_PUSHPULL, HLCD_CTRL_PORT, HLCD_DATA_PORT, HLCD_DispClear_Cmd, HLCD_DispOnOffCTRL_Cmd, HLCD_EN_PIN, HLCD_EntryModeSet_Cmd, HLCD_FuctionSet_Cmd, HLCD_RS_PIN, HLCD_RW_PIN, HLCD_vSendCommand(), MGPIOx_vInit(), MSysTick_vDelayMilliSec(), MSysTick_vInit(), and MGPIOx_ConfigType::Port.
HLCD_vSendCommand()
void HLCD_vSendCommand (u8_t A_u8Cmd)
Definition at line 162 of file LCD_program.c.
{
    // Set RS pin low to send a command.
    MGPIOx_vSetPinValue(HLCD_CTRL_PORT, HLCD_RS_PIN, GPIOx_LOW) ;
    // Set RW pin low to write the command.
    MGPIOx_vSetPinValue(HLCD_CTRL_PORT, HLCD_RW_PIN, GPIOx_LOW) ;
    MSysTick_vDelayMilliSec(1) ;
    // Put the command on the data bus.
    GPIO_vSetNibbleLowValue(HLCD_DATA_PORT, A_u8Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
    // Set the enable pin high.
    MGPIOx_vSetPinValue(HLCD_CTRL_PORT, HLCD_EN_PIN, GPIOx_HIGH) ;
    MSysTick_vDelayMilliSec(1) ;
    // Set the enable pin low.
    MGPIOx_vSetPinValue(HLCD_CTRL_PORT, HLCD_EN_PIN, GPIOx_LOW) ;
    MSysTick_vDelayMilliSec(1) ;
}
References GPIO_vSetNibbleLowValue(), GPIOx_HIGH, GPIOx_LOW, HLCD_CTRL_PORT, HLCD_DATA_PORT, HLCD_EN_PIN, HLCD_RS_PIN, HLCD_RW_PIN, MGPIOx_vSetPinValue(), and MSysTick_vDelayMilliSec().
Referenced by HLCD_vClear(), HLCD_vDispCursorWithBlinking(), HLCD_vGoTo(), HLCD_vInit(), HLCD_vSaveCustomChar(), HLCD_vSetCursorBlinkingOFF(), HLCD_vSetDispOFF(), and HLCD_vSetShiftLeftOn().
HLCD_vSendData()
void HLCD_vSendData (u8_t A_u8Data)
Definition at line 193 of file LCD_program.c.
{
    // Set RS pin high to send data.
    MGPIOx_vSetPinValue(HLCD_CTRL_PORT, HLCD_RS_PIN, GPIOx_HIGH) ;
    // Set RW pin low to write the data.
    MGPIOx_vSetPinValue(HLCD_CTRL_PORT, HLCD_RW_PIN, GPIOx_LOW) ;
    MSysTick_vDelayMilliSec(1) ;
    // Put the data on the data bus.
    GPIO_vSetNibbleLowValue(HLCD_DATA_PORT, A_u8Data) ;
    MSysTick_vDelayMilliSec(1) ;
    // Set the enable pin high.
    MGPIOx_vSetPinValue(HLCD_CTRL_PORT, HLCD_EN_PIN, GPIOx_HIGH) ;
    MSysTick_vDelayMilliSec(1) ;
    // Set the enable pin low.
    MGPIOx_vSetPinValue(HLCD_CTRL_PORT, HLCD_EN_PIN, GPIOx_LOW) ;
    MSysTick_vDelayMilliSec(1) ;
}
References GPIO_vSetNibbleLowValue(), GPIOx_HIGH, GPIOx_LOW, HLCD_CTRL_PORT, HLCD_DATA_PORT, HLCD_EN_PIN, HLCD_RS_PIN, HLCD_RW_PIN, MGPIOx_vSetPinValue(), and MSysTick_vDelayMilliSec().
Referenced by HLCD_vClearChar(), HLCD_vDispNumber(), HLCD_vDispShiftLeftString(), HLCD_vDispString(), and HLCD_vSaveCustomChar().
HLCD_vClear()
void HLCD_vClear (void)
Definition at line 224 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(1) ;
    HLCD_vSendCommand(HLCD_DispClear_Cmd) ;
    MSysTick_vDelayMilliSec(1) ;
}
References HLCD_DispClear_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
HLCD_vDispString()
void HLCD_vDispString (c8_t * A_c8Char)
Definition at line 238 of file LCD_program.c.
{
    for(VAR(u8_t) L_u8I = 0 ; A_c8Char[L_u8I] != '\0' ; L_u8I++)
    {
        HLCD_vSendData(A_c8Char[L_u8I]) ;
    }
}
References HLCD_vSendData(), and VAR.
HLCD_vDispNumber()
void HLCD_vDispNumber (s32_t A_s32Num)
Definition at line 253 of file LCD_program.c.
{
    VAR(u8_t) L_u8Counter = 0 ;
    VAR(u8_t) LR_u8Digits[10] = {0} ;
    // In case the number is signed.
    if (A_s32Num < 0)
    {
        HLCD_vSendData('-') ;
        A_s32Num = A_s32Num * (-1) ;
    }
    // In case the number the number contains zeros.
    if(A_s32Num == 0)
    {
        HLCD_vSendData('0') ;
    }
    // Save reversed digits in the array.
    for(L_u8Counter = 0 ; A_s32Num != 0 ; L_u8Counter++)
    {
        LR_u8Digits[L_u8Counter] = A_s32Num % 10 ;
        A_s32Num /= 10 ;
    }
    // For arrangement the digits.
    for (VAR(s8_t) L_s8ArrangedNums = (L_u8Counter-1) ; L_s8ArrangedNums >= 0 ; L_s8ArrangedNums--)
    {
        HLCD_vSendData('0' + LR_u8Digits[ L_s8ArrangedNums ]) ;
    }
}
References HLCD_vSendData(), and VAR.
HLCD_vSaveCustomChar()
void HLCD_vSaveCustomChar (u8_t A_u8Address, u8_t * A_u8CustomChar)
Definition at line 333 of file LCD_program.c.
{
    // 1-Set CGRAM Address.
    HLCD_vSendCommand(SET_CGRAM_AC_MASK + (NumOf_CGRAM_Patterns * A_u8Address)) ;
    // 2- Send custom char data.
    for(VAR(u8_t) L_u8I = FirstByteInCGRAM_Pattern ; L_u8I < LastByteInCGRAM_Pattern ; L_u8I++)
    {
        HLCD_vSendData(A_u8CustomChar[L_u8I]) ;
    }
    // 3-Set DDRAM address
    HLCD_vSendCommand(SET_DDRAM_AC_MASK) ;
}
References FirstByteInCGRAM_Pattern, HLCD_vSendCommand(), HLCD_vSendData(), LastByteInCGRAM_Pattern, NumOf_CGRAM_Patterns, SET_CGRAM_AC_MASK, SET_DDRAM_AC_MASK, and VAR.
HLCD_vGoTo()
void HLCD_vGoTo (u8_t A_u8Row, u8_t A_u8Col)
Definition at line 355 of file LCD_program.c.
{
    // Valid Range.
    if ((A_u8Row <= MAX_IDX_OF_ROWS) && (A_u8Col <= MAX_IDX_OF_COL))
    {
        switch(A_u8Row)
        {
            case 0: HLCD_vSendCommand(SET_DDRAM_AC_MASK + A_u8Col + FIRST_ROW_START) ; break;
            case 1: HLCD_vSendCommand(SET_DDRAM_AC_MASK + A_u8Col + SEC_ROW_START) ; break;
        }
    }
    else
    {
        // Do Nothing
    }
}
References FIRST_ROW_START, HLCD_vSendCommand(), MAX_IDX_OF_COL, MAX_IDX_OF_ROWS, SEC_ROW_START, and SET_DDRAM_AC_MASK.
Referenced by HLCD_vClearChar().
HLCD_vSetShiftLeftOn()
void HLCD_vSetShiftLeftOn (void)
Definition at line 385 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(500) ;
    HLCD_vSendCommand(HLCD_EntryModeSet_ShiftLeftOn_Cmd) ;
    MSysTick_vDelayMilliSec(500) ;
}
References HLCD_EntryModeSet_ShiftLeftOn_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
Referenced by HLCD_vDispShiftLeftString().
HLCD_vSetDispOFF()
void HLCD_vSetDispOFF (void)
Definition at line 400 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(500) ;
    HLCD_vSendCommand(HLCD_DispOff_Cmd) ;
    MSysTick_vDelayMilliSec(500) ;
}
References HLCD_DispOff_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
HLCD_vDispCursorWithBlinking()
void HLCD_vDispCursorWithBlinking (void)
Definition at line 415 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(500) ;
    HLCD_vSendCommand(HLCD_DispCursorWithBlinking_Cmd) ;
    MSysTick_vDelayMilliSec(500) ;
}
References HLCD_DispCursorWithBlinking_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
HLCD_vSetCursorBlinkingOFF()
void HLCD_vSetCursorBlinkingOFF (void)
Definition at line 429 of file LCD_program.c.
{
    MSysTick_vDelayMilliSec(500) ;
    HLCD_vSendCommand(HLCD_SetCursorBlinkingOFF_Cmd) ;
    MSysTick_vDelayMilliSec(500) ;
}
References HLCD_SetCursorBlinkingOFF_Cmd, HLCD_vSendCommand(), and MSysTick_vDelayMilliSec().
HLCD_vDispShiftLeftString()
void HLCD_vDispShiftLeftString (c8_t * A_c8Char)
Definition at line 443 of file LCD_program.c.
{
    VAR(u8_t) L_u8I = 0 ;
    for(L_u8I = 0 ; A_c8Char[L_u8I] != '\0' ; L_u8I++)
    {
        HLCD_vSendData(A_c8Char[L_u8I]) ;
    }
    MSysTick_vDelayMilliSec(500) ;
    if(L_u8I > HLCD_CharactersNums)
    {
        for(VAR(u8_t) i = 0 ; i < L_u8I - HLCD_CharactersNums ; i++)
        {
            HLCD_vSetShiftLeftOn() ;
        }
    }
}
References HLCD_CharactersNums, HLCD_vSendData(), HLCD_vSetShiftLeftOn(), MSysTick_vDelayMilliSec(), and VAR.
HLCD_vClearChar()
void HLCD_vClearChar (u8_t A_u8Row, u8_t A_u8Col)
Definition at line 474 of file LCD_program.c.
{
    HLCD_vGoTo(A_u8Row, A_u8Col) ;
    HLCD_vSendData(' ') ;
}
References HLCD_vGoTo(), and HLCD_vSendData().