COTS/HAL/LDR/LDR_interface.h File Reference
Macros
#define DARK 3500
#define VERY_DIM 3000
#define MODERATE 2000
#define OVERCAST 1500
#define VERY_BRIGHT 1000
Functions
void HLDR_vInit (void)
u16_t HLDR_u16DigitalOutputValue (void)
Macro Definition Documentation
DARK
#define DARK 3500
Definition at line 14 of file LDR_interface.h.
VERY_DIM
#define VERY_DIM 3000
Definition at line 16 of file LDR_interface.h.
MODERATE
#define MODERATE 2000
Definition at line 18 of file LDR_interface.h.
OVERCAST
#define OVERCAST 1500
Definition at line 20 of file LDR_interface.h.
VERY_BRIGHT
#define VERY_BRIGHT 1000
Definition at line 22 of file LDR_interface.h.
Function Documentation
HLDR_vInit()
void HLDR_vInit (void)
Definition at line 36 of file LDR_program.c.
{
    MGPIOx_vInit(&LDR_Vo) ;
    MADC_vInit() ;
}
References LDR_Vo, MADC_vInit(), and MGPIOx_vInit().
HLDR_u16DigitalOutputValue()
u16_t HLDR_u16DigitalOutputValue (void)
Definition at line 48 of file LDR_program.c.
{
    VAR(u16_t) L_u16DigitalResult = INITIAL_ZERO ;
    L_u16DigitalResult = MADC_u16ConvertToDigital(LDR_CHANNEL) ;
    return L_u16DigitalResult ;
}
References INITIAL_ZERO, LDR_CHANNEL, MADC_u16ConvertToDigital(), and VAR.