COTS/HAL/LDR/LDR_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../../MCAL/RCC/MRCC_interface.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `../../MCAL/ADC/ADC_interface.h`
#include `LDR_interface.h`
#include `LDR_private.h`
#include `LDR_config.h`
Functions
void HLDR_vInit (void)
u16_t HLDR_u16DigitalOutputValue (void)
Variables
MGPIOx_ConfigType LDR_Vo
u8_t LDR_CHANNEL
Function Documentation
HLDR_vInit()
void HLDR_vInit (void)
Definition at line 36 of file LDR_program.c.
{
    MGPIOx_vInit(&LDR_Vo) ;
    MADC_vInit() ;
}
References LDR_Vo, MADC_vInit(), and MGPIOx_vInit().
HLDR_u16DigitalOutputValue()
u16_t HLDR_u16DigitalOutputValue (void)
Definition at line 48 of file LDR_program.c.
{
    VAR(u16_t) L_u16DigitalResult = INITIAL_ZERO ;
    L_u16DigitalResult = MADC_u16ConvertToDigital(LDR_CHANNEL) ;
    return L_u16DigitalResult ;
}
References INITIAL_ZERO, LDR_CHANNEL, MADC_u16ConvertToDigital(), and VAR.
Variable Documentation
LDR_Vo
MGPIOx_ConfigType LDR_Vo [extern]
Definition at line 26 of file LDR_config.c.
Referenced by HLDR_vInit().
LDR_CHANNEL
u8_t LDR_CHANNEL [extern]
Definition at line 41 of file LDR_config.c.
Referenced by HLDR_u16DigitalOutputValue().