COTS/HAL/LED/LED_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `../../MCAL/SysTick/SysTick_interface.h`
#include `LED_private.h`
#include `LED_interface.h`
#include `LED_config.h`
Functions
void HLED_vInit (LED_LEDConfiguration *pLED_Cfg)
void HLED_vTurnLightOn (LED_LEDConfiguration *pLED_Cfg)
void HLED_vTurnLightOff (LED_LEDConfiguration *pLED_Cfg)
void HLED_vToggleLight (LED_LEDConfiguration *pLED_Cfg)
void HLED_vBlinkLED (LED_LEDConfiguration *pLED_Cfg, u32_t A_u32MilliSecs)
Function Documentation
HLED_vInit()
void HLED_vInit (LED_LEDConfiguration * pLED_Cfg)
Definition at line 25 of file LED_program.c.
{
    VAR(MGPIOx_ConfigType) LED_Cfg =
        {
            .Port = pLED_Cfg->u8Port,
            .Pin = pLED_Cfg->u8Pin,
            .Mode = GPIOx_MODE_OUTPUT,
            .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_LowSpeed,
            .InputType = GPIOx_NoPull};
    MGPIOx_vInit(&LED_Cfg);
}
References GPIOx_LowSpeed, GPIOx_MODE_OUTPUT, GPIOx_NoPull, GPIOx_PUSHPULL, MGPIOx_vInit(), LED_LEDConfiguration::u8Pin, LED_LEDConfiguration::u8Port, and VAR.
HLED_vTurnLightOn()
void HLED_vTurnLightOn (LED_LEDConfiguration * pLED_Cfg)
Definition at line 42 of file LED_program.c.
{
    MGPIOx_vSetPinValue(pLED_Cfg->u8Port, pLED_Cfg->u8Pin, GPIOx_HIGH);
}
References GPIOx_HIGH, MGPIOx_vSetPinValue(), LED_LEDConfiguration::u8Pin, and LED_LEDConfiguration::u8Port.
HLED_vTurnLightOff()
void HLED_vTurnLightOff (LED_LEDConfiguration * pLED_Cfg)
Definition at line 50 of file LED_program.c.
{
    MGPIOx_vSetPinValue(pLED_Cfg->u8Port, pLED_Cfg->u8Pin, GPIOx_LOW);
}
References GPIOx_LOW, MGPIOx_vSetPinValue(), LED_LEDConfiguration::u8Pin, and LED_LEDConfiguration::u8Port.
HLED_vToggleLight()
void HLED_vToggleLight (LED_LEDConfiguration * pLED_Cfg)
Definition at line 58 of file LED_program.c.
{
    MGPIOx_vTogglePinValue(pLED_Cfg->u8Port, pLED_Cfg->u8Pin);
}
References MGPIOx_vTogglePinValue(), LED_LEDConfiguration::u8Pin, and LED_LEDConfiguration::u8Port.
HLED_vBlinkLED()
void HLED_vBlinkLED (LED_LEDConfiguration * pLED_Cfg, u32_t A_u32MilliSecs)
Definition at line 66 of file LED_program.c.
{
    MGPIOx_vSetPinValue(pLED_Cfg->u8Port, pLED_Cfg->u8Pin, GPIOx_HIGH);
    MSysTick_vDelayMilliSec(A_u32MilliSecs) ;
    MGPIOx_vSetPinValue(pLED_Cfg->u8Port, pLED_Cfg->u8Pin, GPIOx_LOW);
    MSysTick_vDelayMilliSec(A_u32MilliSecs) ;
}
References GPIOx_HIGH, GPIOx_LOW, MGPIOx_vSetPinValue(), MSysTick_vDelayMilliSec(), LED_LEDConfiguration::u8Pin, and LED_LEDConfiguration::u8Port.