COTS/MCAL/RCC/MRCC_interface.h File Reference
This file contains the interfacing information for the RCC module.
Macros
#define RCC_AHB1 1
AHB1 Bus.
#define RCC_AHB2 2
AHB2 Bus.
#define RCC_APB1 3
APB1 Bus.
#define RCC_APB2 4
APB2 Bus.
#define RCC_AHB1LPENR 5
peripheral clock enable in low power mode register
#define AHB1ENR_DMA2EN 22
Enable CLK on DMA2 peripheral.
#define AHB1ENR_DMA1EN 21
Enable CLK on DMA1 peripheral.
#define AHB1ENR_CRCEN 12
Enable CLK on CRC peripheral.
#define AHB1ENR_GPIOHEN 7
Enable CLK on GPIOH peripheral.
#define AHB1ENR_GPIOEEN 4
Enable CLK on GPIOE peripheral.
#define AHB1ENR_GPIODEN 3
Enable CLK on GPIOD peripheral.
#define AHB1ENR_GPIOCEN 2
Enable CLK on GPIOC peripheral.
#define AHB1ENR_GPIOBEN 1
Enable CLK on GPIOB peripheral.
#define AHB1ENR_GPIOAEN 0
Enable CLK on GPIOA peripheral.
#define AHB2ENR_OTGFSEN 7
Enable CLK on OTGFS peripheral.
#define APB1ENR_PWREN 28
Enable CLK on PWR peripheral.
#define APB1ENR_I2C3EN 23
Enable CLK on I2C3 peripheral.
#define APB1ENR_I2C2EN 22
Enable CLK on I2C2 peripheral.
#define APB1ENR_I2C1EN 21
Enable CLK on I2C1 peripheral.
#define APB1ENR_USART2EN 17
Enable CLK on USART2 peripheral.
#define APB1ENR_SPI3EN 15
Enable CLK on SPI3 peripheral.
#define APB1ENR_SPI2EN 14
Enable CLK on SPI2 peripheral.
#define APB1ENR_WWDGEN 11
Enable CLK on WWD peripheral.
#define APB1ENR_TIM5EN 3
Enable CLK on TIM5 peripheral.
#define APB1ENR_TIM4EN 2
Enable CLK on TIM4 peripheral.
#define APB1ENR_TIM3EN 1
Enable CLK on TIM3 peripheral.
#define APB1ENR_TIM2EN 0
Enable CLK on TIM2 peripheral.
#define APB2ENR_TIM11EN 18
Enable CLK on TIM11 peripheral.
#define APB2ENR_TIM10EN 17
Enable CLK on TIM10 peripheral.
#define APB2ENR_TIM9EN 16
Enable CLK on TIM9 peripheral.
#define APB2ENR_SYSCFGEN 14
Enable CLK on SYSCFG peripheral.
#define APB2ENR_SPI4EN 13
Enable CLK on SPI4 peripheral.
#define APB2ENR_SPI1EN 12
Enable CLK on SPI1 peripheral.
#define APB2ENR_SDIOEN 11
Enable CLK on SDIO peripheral.
#define APB2ENR_ADC1EN 8
Enable CLK on ADC1 peripheral.
#define APB2ENR_USART6EN 5
Enable CLK on USART6 peripheral.
#define APB2ENR_USART1EN 4
Enable CLK on USART1 peripheral.
#define APB2ENR_TIM1EN 0
Enable CLK on TIM1 peripheral.
#define AHB1LPENR_FLITFLPEN 15
Enable CLK on FLITFLP peripheral.
Functions
void MRCC_vInit (void)
Initialize the RCC with a certain configurations.
void MRCC_vEnablePeriphralCLK (VAR(u32_t) A_u32BusID, VAR(u32_t) A_u32PeriphralID)
Enabling the CLK on a specific Peripheral.
void MRCC_vDisablePeriphralCLK (VAR(u32_t) A_u32BusID, VAR(u32_t) A_u32PeriphralID)
Disabling the CLK on a specific Peripheral.
Detailed Description
This file contains the interfacing information for the RCC module.
Author
Ali El Bana & Mo Alaa
Version
2.0
Date
11/9/2022
Definition in file MRCC_interface.h.
Function Documentation
MRCC_vInit()
void MRCC_vInit (void)
Initialize the RCC with a certain configurations.
Definition at line 29 of file MRCC_program.c.
{
    // PLLI2S (ON/OFF).
    #if PLLI2S == ENABLE
        SET_BIT(RCC->CR, RCC_CR_PLLI2SON) ;
    #elif PLLI2S == DISABLE
        CLR_BIT(RCC->CR, RCC_CR_PLLI2SON) ;
    #endif
    // PLL (ON/OFF).
    #if PLL == ENABLE
        SET_BIT(RCC->CR, RCC_CR_PLLON) ;
    #elif PLL == DISABLE
        CLR_BIT(RCC->CR, RCC_CR_PLLON) ;
    #endif
    // CSS (ON/OFF).
    #if CSS == ENABLE
        SET_BIT(RCC->CR, RCC_CR_CSSON) ;
    #elif CSS == DISABLE
        CLR_BIT(RCC->CR, RCC_CR_CSSON) ;
    #endif
    // HSEBYP.
    #if HSEBYP == BYBASED
        SET_BIT(RCC->CR, RCC_CR_HSEBYP) ;
    #elif HSEBYP == NOTBYBASED
        CLR_BIT(RCC->CR, RCC_CR_HSEBYP) ;
    #endif
    // Select CLK switch (HSI/HSE/PLL).
    #if SW == HSI
        CLR_BIT(RCC->CFGR, RCC_CFGR_SW_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_SW_b1) ;
    #elif SW == HSE
        SET_BIT(RCC->CFGR, RCC_CFGR_SW_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_SW_b1) ;
    #elif SW == PLLCLK
        CLR_BIT(RCC->CFGR, RCC_CFGR_SW_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_SW_b1) ;
    #endif
        // Select CLK switch status (HSI/HSE/PLL).
        #if SWS == HSI
            CLR_BIT(RCC->CFGR, RCC_CFGR_SWS_b0) ;
            CLR_BIT(RCC->CFGR, RCC_CFGR_SWS_b1) ;
        #elif SWS == HSE
            SET_BIT(RCC->CFGR, RCC_CFGR_SWS_b0) ;
            CLR_BIT(RCC->CFGR, RCC_CFGR_SWS_b1) ;
        #elif SWS == PLLCLK
            CLR_BIT(RCC->CFGR, RCC_CFGR_SWS_b0) ;
            SET_BIT(RCC->CFGR, RCC_CFGR_SWS_b1) ;
        #endif
    // MCO2 selection:
    #if MCO2 == SYSCLK
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2_b1) ;
    #elif MCO2 == PLLI2SCLK
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2_b1) ;
    #elif MCO2 == HSE
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2_b1) ;
    #elif MCO2 == PLLCLK
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2_b1) ;
    #endif
    // MCO2 prescaler:
    #if MCO2PRE == NoDivision
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b2) ;
    #elif MCO2PRE == DivisionBy2
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b2) ;
    #elif MCO2PRE == DivisionBy3
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b2) ;
    #elif MCO2PRE == DivisionBy4
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b2) ;
    #elif MCO2PRE == DivisionBy5
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC2PRE_b2) ;
    #endif
    // MCO1 selection:
    #if MCO1 == HSI
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1_b1) ;
    #elif MCO1 == LSE
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1_b1) ;
    #elif MCO1 == HSE
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1_b1) ;
    #elif MCO1 == PLLCLK
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1_b1) ;
    #endif
    // MCO1 prescaler:
    #if MCO1PRE == NoDivision
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b2) ;
    #elif MCO1PRE == DivisionBy2
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b2) ;
    #elif MCO1PRE == DivisionBy3
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b2) ;
    #elif MCO1PRE == DivisionBy4
        CLR_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b2) ;
    #elif MCO1PRE == DivisionBy5
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_MOC1PRE_b2) ;
    #endif
    // AHB prescalers:
    #if HPRE == NoDivision
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #elif HPRE == SYSCLKby2
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #elif HPRE == SYSCLKby4
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #elif HPRE == SYSCLKby8
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #elif HPRE == SYSCLKby16
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #elif HPRE == SYSCLKby64
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #elif HPRE == SYSCLKby128
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #elif HPRE == SYSCLKby256
        CLR_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #elif HPRE == SYSCLKby512
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b2) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_HPRE_b3) ;
    #endif
    // APB1 prescalers:
    #if PPRE1 == NoDivision
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b2) ;
    #elif PPRE1 == AHBby2
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b2) ;
    #elif PPRE1 == AHBby4
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b2) ;
    #elif PPRE1 == AHBby8
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b2) ;
    #elif PPRE1 == AHBby16
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE1_b2) ;
    #endif
    // APB2 prescalers:
    #if PPRE2 == NoDivision
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b1) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b2) ;
    #elif PPRE2 == AHBby2
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b2) ;
    #elif PPRE2 == AHBby4
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b0) ;
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b2) ;
    #elif PPRE2 == AHBby8
        CLR_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b2) ;
    #elif PPRE2 == AHBby16
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b0) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b1) ;
        SET_BIT(RCC->CFGR, RCC_CFGR_PPRE2_b2) ;
#endif
    // PLL configurations:
    // Enable the selected CLK (HSI ON/HSE ON/PLL ON): //
    // HSE (ON/OFF).
    #if HSE_EN == ENABLE
        SET_BIT(RCC->CR, RCC_CR_HSEON) ;
    #elif HSE_EN == DISABLE
        CLR_BIT(RCC->CR, RCC_CR_HSEON) ;
    #endif
    // HSI (ON/OFF).
    #if HSI_EN == ENABLE
        SET_BIT(RCC->CR, RCC_CR_HSION) ;
    #elif HSI_EN == DISABLE
        CLR_BIT(RCC->CR, RCC_CR_HSION) ;
    #endif
}
References CLR_BIT, RCC, RCC_CFGR_HPRE_b0, RCC_CFGR_HPRE_b1, RCC_CFGR_HPRE_b2, RCC_CFGR_HPRE_b3, RCC_CFGR_MOC1_b0, RCC_CFGR_MOC1_b1, RCC_CFGR_MOC1PRE_b0, RCC_CFGR_MOC1PRE_b1, RCC_CFGR_MOC1PRE_b2, RCC_CFGR_MOC2_b0, RCC_CFGR_MOC2_b1, RCC_CFGR_MOC2PRE_b0, RCC_CFGR_MOC2PRE_b1, RCC_CFGR_MOC2PRE_b2, RCC_CFGR_PPRE1_b0, RCC_CFGR_PPRE1_b1, RCC_CFGR_PPRE1_b2, RCC_CFGR_PPRE2_b0, RCC_CFGR_PPRE2_b1, RCC_CFGR_PPRE2_b2, RCC_CFGR_SW_b0, RCC_CFGR_SW_b1, RCC_CFGR_SWS_b0, RCC_CFGR_SWS_b1, RCC_CR_CSSON, RCC_CR_HSEBYP, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLLI2SON, RCC_CR_PLLON, and SET_BIT.
MRCC_vEnablePeriphralCLK()
void MRCC_vEnablePeriphralCLK (VAR(u32_t) A_u32BusID, VAR(u32_t) A_u32PeriphralID)
Enabling the CLK on a specific Peripheral.
Parameters
 in A_u32BusID Bus ID.
 in A_u32PeriphralID Peripheral ID.
Referenced by MADC_vEnable(), MADC_vInit(), MSPI_vInit(), and MUSART_vInit().
MRCC_vDisablePeriphralCLK()
void MRCC_vDisablePeriphralCLK (VAR(u32_t) A_u32BusID, VAR(u32_t) A_u32PeriphralID)
Disabling the CLK on a specific Peripheral.
Parameters
 in A_u32BusID Bus ID.
 in A_u32PeriphralID Peripheral ID.
Referenced by MADC_vDisable(), and MSPI_vDISABLE().