COTS/APP/Mob_APP/Mob_APP_interface.h File Reference
Macros
#define DECIMAL 10
#define SPEED0_STR `*S0*`
#define TRAD_MODE_CHAR 'T'
#define NCC_MODE_CHAR 'N'
#define ACC_MODE_CHAR 'A'
#define FCW_MODE_CHAR 'F'
#define EXIT_SYS_CHAR 'E'
#define FORW_CHAR 'f'
#define BACKW_CHAR 'b'
#define RIGHT_CHAR 'r'
#define LEFT_CHAR 'l'
#define STOP_CHAR 's'
#define EXIT_MODE_CHAR 'e'
#define INC_SPEED_CHAR '+'
#define DEC_SPEED_CHAR '-'
#define HYSTRS_VALUE 3
Functions
void AMobApp_vInit (void)
void AMobApp_vSendSpeedValue (u32_t A_u32SpeedValue)
void AMobApp_vCntrlCar (void)
Macro Definition Documentation
DECIMAL
#define DECIMAL 10
Definition at line 10 of file Mob_APP_interface.h.
SPEED0_STR
#define SPEED0_STR `*S0*`
Definition at line 11 of file Mob_APP_interface.h.
TRAD_MODE_CHAR
#define TRAD_MODE_CHAR 'T'
Definition at line 13 of file Mob_APP_interface.h.
NCC_MODE_CHAR
#define NCC_MODE_CHAR 'N'
Definition at line 14 of file Mob_APP_interface.h.
ACC_MODE_CHAR
#define ACC_MODE_CHAR 'A'
Definition at line 15 of file Mob_APP_interface.h.
FCW_MODE_CHAR
#define FCW_MODE_CHAR 'F'
Definition at line 16 of file Mob_APP_interface.h.
EXIT_SYS_CHAR
#define EXIT_SYS_CHAR 'E'
Definition at line 17 of file Mob_APP_interface.h.
FORW_CHAR
#define FORW_CHAR 'f'
Definition at line 19 of file Mob_APP_interface.h.
BACKW_CHAR
#define BACKW_CHAR 'b'
Definition at line 20 of file Mob_APP_interface.h.
RIGHT_CHAR
#define RIGHT_CHAR 'r'
Definition at line 21 of file Mob_APP_interface.h.
LEFT_CHAR
#define LEFT_CHAR 'l'
Definition at line 22 of file Mob_APP_interface.h.
STOP_CHAR
#define STOP_CHAR 's'
Definition at line 23 of file Mob_APP_interface.h.
EXIT_MODE_CHAR
#define EXIT_MODE_CHAR 'e'
Definition at line 24 of file Mob_APP_interface.h.
INC_SPEED_CHAR
#define INC_SPEED_CHAR '+'
Definition at line 25 of file Mob_APP_interface.h.
DEC_SPEED_CHAR
#define DEC_SPEED_CHAR '-'
Definition at line 26 of file Mob_APP_interface.h.
HYSTRS_VALUE
#define HYSTRS_VALUE 3
Definition at line 28 of file Mob_APP_interface.h.
Function Documentation
AMobApp_vInit()
void AMobApp_vInit (void)
Definition at line 41 of file Mob_APP_program.c.
{
    // Initialization of Bluetooth Module
    HBluetooth_vInit() ;
    HBluetooth_vSendString("\nSuccessfully connected\n") ;
}
References HBluetooth_vInit(), and HBluetooth_vSendString().
AMobApp_vSendSpeedValue()
void AMobApp_vSendSpeedValue (u32_t A_u32SpeedValue)
Definition at line 53 of file Mob_APP_program.c.
{
    char L_strSpeedIndc[9] = "*S" ;
    char L_strSpeedStr[6] ;
    // Convert the speed value from integer to string and store it in speedStr.
    itoa(A_u32SpeedValue, L_strSpeedStr, DECIMAL) ;
    // Concatenate "*S" with the speed value string to result a string like that "*S100".
    strcat(L_strSpeedIndc, L_strSpeedStr) ;
    // Concatenate speed value string with "*" to result a string like that "*S100*"
    strcat(L_strSpeedIndc, "*") ;
    // Then send this string through bluetooth to the speed indicator.
    HBluetooth_vSendString(L_strSpeedIndc) ;
}
References DECIMAL, and HBluetooth_vSendString().
Referenced by AACC_vModeON(), AFCW_vModeON(), ANCC_vModeON(), and ATraditional_vModeON().
AMobApp_vCntrlCar()
void AMobApp_vCntrlCar (void)
Definition at line 77 of file Mob_APP_program.c.
{
    c8_t L_c8RecievedState = TRAD_MODE_CHAR ;
    HBluetooth_vSendString("\nCar is ready to be controlled\n") ;
    while(TRUE)
    {
        HBluetooth_vDisableAsynchReceive() ;
        HBluetooth_vSendString("\nSelect one of these modes:\n") ;
        HBluetooth_vSendString("\n1-Traditional Mode\n") ;
        HBluetooth_vSendString("\n2-NCC Mode\n") ;
        HBluetooth_vSendString("\n3-ACC Mode\n") ;
        HBluetooth_vSendString("\n4-FCW Mode\n") ;
        HBluetooth_vSendString("\n5-Exit Mode\n") ;
        L_c8RecievedState = HBluetooth_u8ReceiveByte() ;
        switch(L_c8RecievedState)
        {
            case TRAD_MODE_CHAR : ATraditional_vModeON() ; break ;
            case NCC_MODE_CHAR : ANCC_vModeON() ; break ;
            case ACC_MODE_CHAR : AACC_vModeON() ; break ;
            case FCW_MODE_CHAR : AFCW_vModeON() ; break ;
            default : ATraditional_vModeON() ; break ;
        }
    }
}
References AACC_vModeON(), ACC_MODE_CHAR, AFCW_vModeON(), ANCC_vModeON(), ATraditional_vModeON(), FCW_MODE_CHAR, HBluetooth_u8ReceiveByte(), HBluetooth_vDisableAsynchReceive(), HBluetooth_vSendString(), NCC_MODE_CHAR, TRAD_MODE_CHAR, and TRUE.