COTS/MyRTOS/MyRTOS_interface.h File Reference
#include `MyRTOS_config.h`
Functions
Error_enState RTOS_u8CreateTask (void A_CopyHandler(void), u8_t A_u8Periodicity, u8_t A_u8Priority, u8_t A_u8FirstDelay)
void Scheduler (void)
void RTOS_vStartOS (void)
Error_enState RTOS_u8DeleteTask (u8_t A_u8Priority)
Error_enState RTOS_u8SuspendTask (u8_t A_u8Priority)
Error_enState RTOS_u8ResumeTask (u8_t A_u8Priority)
Function Documentation
RTOS_u8CreateTask()
Error_enState RTOS_u8CreateTask (void A_CopyHandlervoid, u8_t A_u8Periodicity, u8_t A_u8Priority, u8_t A_u8FirstDelay)
Definition at line 36 of file MyRTOS_program.c.
{
    Error_enState L_enuTaskErrorState = NO_ERROR ;
    /* Verify that the priority index within the correct range */
    if((A_u8Priority >= MIN_TASK_NUM) && (A_u8Priority < MAX_TASK_NUM))
    {
        /* Verify that the required priority is free */
        if(SystemTasks[A_u8Priority].TaskHandler == EMPTY)
        {
            SystemTasks[A_u8Priority].TaskHandler = A_CopyHandler ;
            SystemTasks[A_u8Priority].periodicity = A_u8Periodicity ;
            TaskTiming[A_u8Priority] = A_u8FirstDelay ;
            SystemTasks[A_u8Priority].Task_RunningState = RUNNING ;
        }
        else
        {
            /* This task is already reserved */
            L_enuTaskErrorState = TASK_RESERVED_ERROR ;
        }
    }
    else
    {
        /* Wrong priority number */
        L_enuTaskErrorState = PRIORTY_ERROR ;
    }
    return L_enuTaskErrorState ;
}
References EMPTY, MAX_TASK_NUM, MIN_TASK_NUM, NO_ERROR, Task::periodicity, PRIORTY_ERROR, RUNNING, SystemTasks, TASK_RESERVED_ERROR, Task::Task_RunningState, Task::TaskHandler, and TaskTiming.
Scheduler()
void Scheduler (void)
Definition at line 79 of file MyRTOS_program.c.
{
    u8_t L_u8Counter = INITIAL_ZERO ;
    /* Loop on all tasks */
    for(L_u8Counter = MIN_TASK_NUM; L_u8Counter < MAX_TASK_NUM; L_u8Counter++)
    {
        /* Verify that the required priority is reserved */
        if(SystemTasks[L_u8Counter].TaskHandler != EMPTY)
        {
            if(SystemTasks[L_u8Counter].Task_RunningState == RUNNING)
            {
                /* Verify that it is the tick time to execute it */
                if(TaskTiming[L_u8Counter] == 0)
                {
                    /* Run the task */
                    SystemTasks[L_u8Counter].TaskHandler() ;
                    /* Reload the periodicity */
                    TaskTiming[L_u8Counter] = SystemTasks[L_u8Counter].periodicity ;
                }
                else
                {
                    /* Decrement the timing until it reach to the tick time to be executed */
                    TaskTiming[L_u8Counter]-- ;
                }
            }
            else
            {
                /* Do nothing */
            }
        }
        else
        {
            /* Do nothing */
        }
    }
}
References EMPTY, INITIAL_ZERO, MAX_TASK_NUM, MIN_TASK_NUM, Task::periodicity, RUNNING, SystemTasks, Task::TaskHandler, and TaskTiming.
Referenced by RTOS_vStartOS().
RTOS_vStartOS()
void RTOS_vStartOS (void)
Definition at line 206 of file MyRTOS_program.c.
{
    MSysTick_vSetPeriodicInterval(RTOS_TICK_TIME, &Scheduler) ;
}
References MSysTick_vSetPeriodicInterval(), RTOS_TICK_TIME, and Scheduler().
RTOS_u8DeleteTask()
Error_enState RTOS_u8DeleteTask (u8_t A_u8Priority)
Definition at line 128 of file MyRTOS_program.c.
{
    Error_enState L_enuErrorState = NO_ERROR ;
    /* Verify that the required priority is registered */
    if(SystemTasks[A_u8Priority].TaskHandler != EMPTY)
    {
        /* Task exist, execute the removal */
        SystemTasks[A_u8Priority] = Empty_TaskSystem ;
    }
    else
    {
        /* Task not exist */
        L_enuErrorState = TASK_EMPTY_ERROR ;
    }
    return L_enuErrorState ;
}
References EMPTY, Empty_TaskSystem, NO_ERROR, SystemTasks, and TASK_EMPTY_ERROR.
RTOS_u8SuspendTask()
Error_enState RTOS_u8SuspendTask (u8_t A_u8Priority)
Definition at line 154 of file MyRTOS_program.c.
{
    Error_enState L_enuErrorState = NO_ERROR ;
    /* Verify that the required priority is registered */
    if(SystemTasks[A_u8Priority].TaskHandler != EMPTY)
    {
        /* Task exist, suspend it */
        SystemTasks[A_u8Priority].Task_RunningState == SUSPENDED ;
    }
    else
    {
        /* Task not exist */
        L_enuErrorState = TASK_EMPTY_ERROR ;
    }
    return L_enuErrorState ;
}
References EMPTY, NO_ERROR, SUSPENDED, SystemTasks, TASK_EMPTY_ERROR, and Task::Task_RunningState.
RTOS_u8ResumeTask()
Error_enState RTOS_u8ResumeTask (u8_t A_u8Priority)
Definition at line 180 of file MyRTOS_program.c.
{
    Error_enState L_enuErrorState = NO_ERROR ;
    /* Verify that the required priority is registered */
    if(SystemTasks[A_u8Priority].TaskHandler != EMPTY)
    {
        /* Task exist, run it */
        SystemTasks[A_u8Priority].Task_RunningState == RUNNING ;
    }
    else
    {
        /* Task not exist */
        L_enuErrorState = TASK_EMPTY_ERROR ;
    }
    return L_enuErrorState ;
}
References EMPTY, NO_ERROR, RUNNING, SystemTasks, TASK_EMPTY_ERROR, and Task::Task_RunningState.