COTS/APP/NCC/NCC_interface.h File Reference
Functions
void ANCC_vModeON (void)
Function Documentation
ANCC_vModeON()
void ANCC_vModeON (void)
Definition at line 30 of file NCC_program.c.
{
    u32_t L_u32SpeedValue = INITIAL_ZERO ;
    c8_t L_c8RecievedButton = INITIAL_ZERO ;
    HBluetooth_vSendString("\nNCC Mode ON\n") ;
    do
    {
        HCarMove_vForward() ;
        L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
        AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
        L_c8RecievedButton = HBluetooth_u8ReceiveByte() ;
        switch(L_c8RecievedButton)
        {
            case EXIT_MODE_CHAR:
                HCarMove_vStop() ;
                HBluetooth_vSendString(SPEED0_STR) ;
                HBluetooth_vSendString("\nNCC Mode Off\n") ;
            break ;
            case INC_SPEED_CHAR:
                L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                if(L_u32SpeedValue >= SPEED_100_PERCENT)
                {
                    L_u32SpeedValue = SPEED_100_PERCENT ;
                    AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                }
                else
                {
                    L_u32SpeedValue += SPEED_10_PERCENT ;
                    HCarMove_vSpeedRatio(L_u32SpeedValue) ;
                    AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                }
            break ;
            case DEC_SPEED_CHAR:
                L_u32SpeedValue = HCarMove_u32GetCarSpeed() ;
                if(L_u32SpeedValue <= SPEED_0_PERCENT)
                {
                    L_u32SpeedValue = SPEED_0_PERCENT ;
                    AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                }
                else
                {
                    L_u32SpeedValue -= SPEED_10_PERCENT ;
                    HCarMove_vSpeedRatio(L_u32SpeedValue) ;
                    AMobApp_vSendSpeedValue(L_u32SpeedValue) ;
                }
            break ;
            default: /* Do Nothing */ break ;
        }
    }while(L_c8RecievedButton != EXIT_MODE_CHAR) ;
}
References AMobApp_vSendSpeedValue(), DEC_SPEED_CHAR, EXIT_MODE_CHAR, HBluetooth_u8ReceiveByte(), HBluetooth_vSendString(), HCarMove_u32GetCarSpeed(), HCarMove_vForward(), HCarMove_vSpeedRatio(), HCarMove_vStop(), INC_SPEED_CHAR, INITIAL_ZERO, L_u32SpeedValue, SPEED0_STR, SPEED_0_PERCENT, SPEED_100_PERCENT, and SPEED_10_PERCENT.
Referenced by AMobApp_vCntrlCar().