COTS/MCAL/SPI/SPI_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../RCC/MRCC_interface.h`
#include `../GPIO/GPIO_interface.h`
#include `SPI_interface.h`
#include `SPI_private.h`
#include `SPI_config.h`
Functions
void MSPI_vInit (SPI_MemoryMapType *A_SPIx, u8_t A_u8RelationShip, u8_t A_u8DataDirection)
u16_t MSPI_u16Transcieve (SPI_MemoryMapType *A_SPIx, u16_t A_u16Data)
void MSPI_vMasterTransmit (SPI_MemoryMapType *A_SPIx, u16_t A_u16Data)
u16_t MSPI_u16MasterRecieve (SPI_MemoryMapType *A_SPIx)
void MSPI_vSlaveTransmit (SPI_MemoryMapType *A_SPIx, u16_t A_u16Data)
u16_t MSPI_u16SlaveRecieve (SPI_MemoryMapType *A_SPIx)
void MSPI_vDISABLE (SPI_MemoryMapType *A_SPIx, u8_t A_u8RelationShip, u8_t A_u8DataDirection)
void MSPI1_vSetCallBack (void(*Fptr)(void))
void MSPI2_vSetCallBack (void(*Fptr)(void))
void MSPI3_vSetCallBack (void(*Fptr)(void))
void SPI1_IRQHandler (void)
void SPI2_IRQHandler (void)
void SPI3_IRQHandler (void)
Variables
void(* MSPI1_CallBack)(void)
void(* MSPI2_CallBack)(void)
void(* MSPI3_CallBack)(void)
Function Documentation
MSPI_vInit()
void MSPI_vInit (SPI_MemoryMapType * A_SPIx, u8_t A_u8RelationShip, u8_t A_u8DataDirection)
Definition at line 33 of file SPI_program.c.
{
    if(A_SPIx == SPI1)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_SPI1EN) ;
        // PINs configurations.
        MGPIOx_ConfigType MOSI1 =
        {
            .Port = GPIO_PORTA , .Pin = GPIOx_PIN7 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_ConfigType MISO1 =
        {
            .Port = GPIO_PORTA , .Pin = GPIOx_PIN6 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_ConfigType SCK1 =
        {
            .Port = GPIO_PORTA , .Pin = GPIOx_PIN5 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_vInit(&MOSI1) ;
        MGPIOx_vInit(&MISO1) ;
        MGPIOx_vInit(&SCK1) ;
    }
    else if(A_SPIx == SPI2)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB1, APB1ENR_SPI2EN) ;
        // PINs configurations.
        MGPIOx_ConfigType MOSI2 =
        {
            .Port = GPIO_PORTB , .Pin = GPIOx_PIN15 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_ConfigType MISO2 =
        {
            .Port = GPIO_PORTB , .Pin = GPIOx_PIN14 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_ConfigType SCK2 =
        {
            .Port = GPIO_PORTB , .Pin = GPIOx_PIN13 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_vInit(&MOSI2) ;
        MGPIOx_vInit(&MISO2) ;
        MGPIOx_vInit(&SCK2) ;
    }
    else if(A_SPIx == SPI3)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB1, APB1ENR_SPI3EN) ;
        // PINs configurations.
        MGPIOx_ConfigType MOSI3 =
        {
            .Port = GPIO_PORTB , .Pin = GPIOx_PIN5 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_ConfigType MISO3 =
        {
            .Port = GPIO_PORTB , .Pin = GPIOx_PIN4 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_ConfigType SCK3 =
        {
            .Port = GPIO_PORTB , .Pin = GPIOx_PIN3 ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL ,
            .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF5
        } ;
        MGPIOx_vInit(&MOSI3) ;
        MGPIOx_vInit(&MISO3) ;
        MGPIOx_vInit(&SCK3) ;
    }
    if(A_u8RelationShip == SPIx_MSTR)
    {
        // BUAD RATE.
        SPI1->CR1 = (A_SPIx->CR1 & (~(BR_MODE) << 3)) | (BR_MODE << 3) ;
    }
    // CPHA, CPOL.
    #if CPHA_MODE == FIRST_CLK_Captured
    CLR_BIT(A_SPIx->CR1, CPHA) ;
    #elif CPHA_MODE == SECOND_CLK_Captured
    SET_BIT(A_SPIx->CR1, CPHA) ;
    #endif
    #if CPOL_MODE == CLK_IdleAt0
    SET_BIT(A_SPIx->CR1, CPOL) ;
    #elif CPOL_MODE == CLK_IdleAt1
    SET_BIT(A_SPIx->CR1, CPOL) ;
    #endif
    // Data format.
    #if DFF_MODE == EIGHT_BITS
        CLR_BIT(A_SPIx->CR1, DFF) ;
    #elif DFF_MODE == SIXTEEN_BITS
        SET_BIT(A_SPIx->CR1, DFF) ;
    #endif
    // MSB/LSB first.
    #if LSBFIRST_MODE == MSB_First
    CLR_BIT(A_SPIx->CR1, LSBFIRST) ;
    #elif LSBFIRST_MODE == LSB_First
    SET_BIT(A_SPIx->CR1, LSBFIRST) ;
    #endif
    // Select SW slave management.
    switch(A_u8RelationShip)
    {
        case SPIx_MSTR:
            SET_BIT(A_SPIx->CR1, SSM) ;
            SET_BIT(A_SPIx->CR1, SSI) ;
        break ;
        case SPIx_SLAVE:
            SET_BIT(A_SPIx->CR1, SSM) ;
            CLR_BIT(A_SPIx->CR1, SSI) ;
        break ;
    }
    // Select Motorola or TI Mode:
    CLR_BIT(A_SPIx->CR2, FRF) ; // Motorola
    // MASTER/SLAVE Mode.
    switch(A_u8RelationShip)
    {
        case SPIx_MSTR: SET_BIT(A_SPIx->CR1, MSTR) ; break ;
        case SPIx_SLAVE: CLR_BIT(A_SPIx->CR1, MSTR) ; break ;
    }
    // Data direction:
    switch(A_u8RelationShip)
    {
        case SPIx_MSTR:
            switch(A_u8DataDirection)
            {
                case SPIx_FULL_DUPLEX:
                    CLR_BIT(A_SPIx->CR1, BIDIMODE) ;
                    CLR_BIT(A_SPIx->CR1, RXONLY) ;
                break ;
                case SPIx_SIMPLEX :
                    CLR_BIT(A_SPIx->CR1, BIDIMODE) ;
                    #if SIMPLEX_MODE == SIMPLEX_TX
                        CLR_BIT(A_SPIx->CR1, RXONLY) ;
                    #elif SIMPLEX_MODE == SIMPLEX_RX
                        SET_BIT(A_SPIx->CR1, RXONLY) ;
                    #endif
                break ;
                case SPIx_HALF_DUPLEX:
                    #if HALF_DUPLEX_MODE == HALF_DUPLEX_TX
                        SET_BIT(A_SPIx->CR1, BIDIMODE) ;
                        SET_BIT(A_SPIx->CR1, BIDIOE) ;
                    #elif HALF_DUPLEX_MODE == HALF_DUPLEX_RX
                        SET_BIT(A_SPIx->CR1, BIDIMODE) ;
                        CLR_BIT(A_SPIx->CR1, BIDIOE) ;
                    #endif
                break ;
            }
        break;
        case SPIx_SLAVE:
            switch(A_u8DataDirection)
            {
                case SPIx_FULL_DUPLEX:
                    CLR_BIT(A_SPIx->CR1, BIDIMODE) ;
                    CLR_BIT(A_SPIx->CR1, RXONLY) ;
                break ;
                case SPIx_SIMPLEX :
                    CLR_BIT(A_SPIx->CR1, BIDIMODE) ;
                    #if SIMPLEX_MODE == SIMPLEX_TX
                        CLR_BIT(A_SPIx->CR1, RXONLY) ;
                    #elif SIMPLEX_MODE == SIMPLEX_RX
                        SET_BIT(A_SPIx->CR1, RXONLY) ;
                    #endif
                break ;
                case SPIx_HALF_DUPLEX:
                    #if HALF_DUPLEX_MODE == HALF_DUPLEX_TX
                        SET_BIT(A_SPIx->CR1, BIDIMODE) ;
                        SET_BIT(A_SPIx->CR1, BIDIOE) ;
                    #elif HALF_DUPLEX_MODE == HALF_DUPLEX_RX
                        SET_BIT(A_SPIx->CR1, BIDIMODE) ;
                        CLR_BIT(A_SPIx->CR1, BIDIOE) ;
                    #endif
                break ;
            }
        break;
    }
    // Multi-master mode:
    #if MULTI_MSTR_MODE == ENABLE
        CLR_BIT(A_SPIx->CR2, SSOE) ;
    #elif MULTI_MSTR_MODE == DISABLE
        SET_BIT(A_SPIx->CR2, SSOE) ;
    #endif
    // EN/DIS IRQ:
    #if TXNEIE_MODE == ENABLE
        SET_BIT(A_SPIx->CR2, TXEIE) ;
    #elif TXNEIE_MODE == DISABLE
        CLR_BIT(A_SPIx->CR2, TXEIE) ;
    #endif
    #if RXNEIE_MODE == ENABLE
        SET_BIT(A_SPIx->CR2, RXNEIE) ;
    #elif RXNEIE_MODE == DISABLE
        CLR_BIT(A_SPIx->CR2, RXNEIE) ;
    #endif
    // EN/DIS SPI.
    SET_BIT(A_SPIx->CR1, SPE) ;
}
References APB1ENR_SPI2EN, APB1ENR_SPI3EN, APB2ENR_SPI1EN, BIDIMODE, BIDIOE, BR_MODE, CLR_BIT, CPHA, CPOL, SPI_MemoryMapType::CR1, SPI_MemoryMapType::CR2, DFF, FRF, GPIO_PORTA, GPIO_PORTB, GPIOx_AF5, GPIOx_LowSpeed, GPIOx_MODE_AF, GPIOx_NoPull, GPIOx_PIN13, GPIOx_PIN14, GPIOx_PIN15, GPIOx_PIN3, GPIOx_PIN4, GPIOx_PIN5, GPIOx_PIN6, GPIOx_PIN7, GPIOx_PUSHPULL, LSBFIRST, MGPIOx_vInit(), MRCC_vEnablePeriphralCLK(), MSTR, MGPIOx_ConfigType::Port, RCC_APB1, RCC_APB2, RXNEIE, RXONLY, SET_BIT, SPE, SPI1, SPI2, SPI3, SPIx_FULL_DUPLEX, SPIx_HALF_DUPLEX, SPIx_MSTR, SPIx_SIMPLEX, SPIx_SLAVE, SSI, SSM, SSOE, and TXEIE.
Referenced by HTFT_vInit().
MSPI_u16Transcieve()
u16_t MSPI_u16Transcieve (SPI_MemoryMapType * A_SPIx, u16_t A_u16Data)
Definition at line 363 of file SPI_program.c.
{
    SPI1->DR = A_u16Data ;
    // Wait for transmission complete.
    while(GET_BIT(A_SPIx->SR, TXE) == FLAG_CLEARED)
    {
        asm("NOP") ;
    }
    // Wait for the last transmission bit.
    while(GET_BIT(A_SPIx->SR, BSY) == FLAG_SET)
    {
        asm("NOP") ;
    }
    // Wait for reception complete.
    while(GET_BIT(A_SPIx->SR, RXNE) == FLAG_CLEARED)
    {
        asm("NOP") ;
    }
    return A_SPIx->DR ;
}
References BSY, SPI_MemoryMapType::DR, FLAG_CLEARED, FLAG_SET, GET_BIT, RXNE, SPI1, SPI_MemoryMapType::SR, and TXE.
Referenced by HTFT_vWriteCMD(), and HTFT_vWriteData().
MSPI_vMasterTransmit()
void MSPI_vMasterTransmit (SPI_MemoryMapType * A_SPIx, u16_t A_u16Data)
Definition at line 394 of file SPI_program.c.
{
    // Start transmission.
    SPI1->DR = A_u16Data ;
    // Wait for transmission complete.
    while(GET_BIT(A_SPIx->SR, TXE) == FLAG_CLEARED)
    {
        asm("NOP") ;
    }
    // Wait for the last transmission bit.
    while(GET_BIT(A_SPIx->SR, BSY) == FLAG_SET)
    {
        asm("NOP") ;
    }
}
References BSY, FLAG_CLEARED, FLAG_SET, GET_BIT, SPI1, SPI_MemoryMapType::SR, and TXE.
MSPI_u16MasterRecieve()
u16_t MSPI_u16MasterRecieve (SPI_MemoryMapType * A_SPIx)
Definition at line 417 of file SPI_program.c.
{
    // Wait for reception complete.
    while(GET_BIT(A_SPIx->SR, RXNE) == FLAG_CLEARED)
    {
        asm("NOP") ;
    }
    // Return data register.
    return A_SPIx->DR ;
}
References SPI_MemoryMapType::DR, FLAG_CLEARED, GET_BIT, RXNE, and SPI_MemoryMapType::SR.
MSPI_vSlaveTransmit()
void MSPI_vSlaveTransmit (SPI_MemoryMapType * A_SPIx, u16_t A_u16Data)
Definition at line 434 of file SPI_program.c.
{
    // Start transmission.
    SPI1->DR = A_u16Data ;
    // Wait for transmission complete.
    while(GET_BIT(A_SPIx->SR, TXE) == FLAG_CLEARED)
    {
        asm("NOP") ;
    }
    // Wait for the last transmission bit.
    while(GET_BIT(A_SPIx->SR, BSY) == FLAG_SET)
    {
        asm("NOP") ;
    }
}
References BSY, FLAG_CLEARED, FLAG_SET, GET_BIT, SPI1, SPI_MemoryMapType::SR, and TXE.
MSPI_u16SlaveRecieve()
u16_t MSPI_u16SlaveRecieve (SPI_MemoryMapType * A_SPIx)
Definition at line 457 of file SPI_program.c.
{
    // Wait for reception complete.
    while(GET_BIT(A_SPIx->SR, RXNE) == FLAG_CLEARED)
    {
        asm("NOP") ;
    }
    // Return data register.
    return A_SPIx->DR ;
}
References SPI_MemoryMapType::DR, FLAG_CLEARED, GET_BIT, RXNE, and SPI_MemoryMapType::SR.
MSPI_vDISABLE()
void MSPI_vDISABLE (SPI_MemoryMapType * A_SPIx, u8_t A_u8RelationShip, u8_t A_u8DataDirection)
Definition at line 474 of file SPI_program.c.
{
    switch(A_u8DataDirection)
    {
        case SPIx_FULL_DUPLEX:
            // Wait for reception complete.
            while(GET_BIT(A_SPIx->SR, RXNE) == FLAG_CLEARED) ;
            // Wait for transmission complete.
            while(GET_BIT(A_SPIx->SR, TXE) == FLAG_CLEARED) ;
            // Wait for the last transmission bit.
            while(GET_BIT(A_SPIx->SR, BSY) == FLAG_SET) ;
            // Disabling the SPIx.
            CLR_BIT(A_SPIx->CR1, SPE) ;
        break ;
        case SPIx_SIMPLEX :
        #if SIMPLEX_MODE == SIMPLEX_TX
            // Wait for transmission complete.
            while(GET_BIT(A_SPIx->SR, TXE) == FLAG_CLEARED) ;
            // Wait for the last transmission bit.
            while(GET_BIT(A_SPIx->SR, BSY) == FLAG_SET) ;
            // Disabling the SPIx.
            CLR_BIT(A_SPIx->CR1, SPE) ;
        #elif SIMPLEX_MODE == SIMPLEX_RX
            switch(A_u8RelationShip)
            {
                case SPIx_MSTR:
                    // Wait for reception complete.
                    while(GET_BIT(A_SPIx->SR, RXNE) == FLAG_CLEARED) ;
                    // Disabling the SPIx.
                    CLR_BIT(A_SPIx->CR1, SPE) ;
                break ;
                case SPIx_SLAVE:
                    // Disabling the SPIx.
                    CLR_BIT(A_SPIx->CR1, SPE) ;
                    // Wait for the last transmission bit.
                    while(GET_BIT(A_SPIx->SR, BSY) == FLAG_SET) ;
                break ;
            }
        #endif
        break ;
        case SPIx_HALF_DUPLEX:
            #if HALF_DUPLEX_MODE == HALF_DUPLEX_TX
            // Wait for transmission complete.
            while(GET_BIT(A_SPIx->SR, TXE) == FLAG_CLEARED) ;
            // Wait for the last transmission bit.
            while(GET_BIT(A_SPIx->SR, BSY) == FLAG_SET) ;
            // Disabling the SPIx.
            CLR_BIT(A_SPIx->CR1, SPE) ;
            #elif HALF_DUPLEX_MODE == HALF_DUPLEX_RX
                switch(A_u8RelationShip)
                {
                    case SPIx_MSTR:
                        // Wait for reception complete.
                        while(GET_BIT(A_SPIx->SR, RXNE) == FLAG_CLEARED) ;
                        // Disabling the SPIx.
                        CLR_BIT(A_SPIx->CR1, SPE) ;
                    break ;
                    case SPIx_SLAVE:
                        // Disabling the SPIx.
                        CLR_BIT(A_SPIx->CR1, SPE) ;
                        // Wait for the last transmission bit.
                        while(GET_BIT(A_SPIx->SR, BSY) == FLAG_SET) ;
                    break ;
                }
            #endif
        break ;
    }
    if(A_SPIx == SPI1)
    {
        MRCC_vDisablePeriphralCLK(RCC_APB2, APB2ENR_SPI1EN) ;
    }
    else if(A_SPIx == SPI2)
    {
        MRCC_vDisablePeriphralCLK(RCC_APB1, APB1ENR_SPI2EN) ;
    }
    else if(A_SPIx == SPI3)
    {
        MRCC_vDisablePeriphralCLK(RCC_APB1, APB1ENR_SPI3EN) ;
    }
}
References APB1ENR_SPI2EN, APB1ENR_SPI3EN, APB2ENR_SPI1EN, BSY, CLR_BIT, SPI_MemoryMapType::CR1, FLAG_CLEARED, FLAG_SET, GET_BIT, MRCC_vDisablePeriphralCLK(), RCC_APB1, RCC_APB2, RXNE, SPE, SPI1, SPI2, SPI3, SPIx_FULL_DUPLEX, SPIx_HALF_DUPLEX, SPIx_MSTR, SPIx_SIMPLEX, SPIx_SLAVE, SPI_MemoryMapType::SR, and TXE.
MSPI1_vSetCallBack()
void MSPI1_vSetCallBack (void(*)(void) Fptr)
Definition at line 606 of file SPI_program.c.
{
    MSPI1_CallBack = Fptr ;
}
References MSPI1_CallBack.
MSPI2_vSetCallBack()
void MSPI2_vSetCallBack (void(*)(void) Fptr)
Definition at line 614 of file SPI_program.c.
{
    MSPI2_CallBack = Fptr ;
}
References MSPI2_CallBack.
MSPI3_vSetCallBack()
void MSPI3_vSetCallBack (void(*)(void) Fptr)
Definition at line 622 of file SPI_program.c.
{
    MSPI3_CallBack = Fptr ;
}
References MSPI3_CallBack.
SPI1_IRQHandler()
void SPI1_IRQHandler (void)
Definition at line 630 of file SPI_program.c.
{
    // CLEAR FLAGS:
    SPI1->SR = SR_RESET ;
    MSPI1_CallBack() ;
}
References MSPI1_CallBack, SPI1, and SR_RESET.
SPI2_IRQHandler()
void SPI2_IRQHandler (void)
Definition at line 643 of file SPI_program.c.
{
    // CLEAR FLAGS:
    SPI2->SR = SR_RESET ;
    MSPI2_CallBack() ;
}
References MSPI2_CallBack, SPI2, and SR_RESET.
SPI3_IRQHandler()
void SPI3_IRQHandler (void)
Definition at line 656 of file SPI_program.c.
{
    // CLEAR FLAGS:
    SPI3->SR = SR_RESET ;
    MSPI3_CallBack() ;
}
References MSPI3_CallBack, SPI3, and SR_RESET.
Variable Documentation
MSPI1_CallBack
void(* MSPI1_CallBack) (void) (void)
Definition at line 25 of file SPI_program.c.
Referenced by MSPI1_vSetCallBack(), and SPI1_IRQHandler().
MSPI2_CallBack
void(* MSPI2_CallBack) (void) (void)
Definition at line 26 of file SPI_program.c.
Referenced by MSPI2_vSetCallBack(), and SPI2_IRQHandler().
MSPI3_CallBack
void(* MSPI3_CallBack) (void) (void)
Definition at line 27 of file SPI_program.c.
Referenced by MSPI3_vSetCallBack(), and SPI3_IRQHandler().