COTS/HAL/TFT/TFT_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../../MCAL/RCC/MRCC_interface.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `../../MCAL/SysTick/SysTick_interface.h`
#include `../../MCAL/SPI/SPI_interface.h`
#include `TFT_interface.h`
#include `TFT_private.h`
#include `TFT_config.h`
Functions
void HTFT_vWriteCMD (u16_t A_u16CMD)
void HTFT_vWriteData (u16_t A_u16Data)
void HTFT_vResetSequence (void)
void HTFT_vInit (void)
void HTFT_vShowImage (u16_t const *A_u16Image, u32_t A_u32ImageSize)
void HTFT_vSetXPosition (u16_t A_u16XStart, u16_t A_u16XEnd)
void HTFT_vSetYPosition (u16_t A_u16YStart, u16_t A_u16YEnd)
void HTFT_vFillRectangle (u16_t A_u16Color)
void HTFT_vFillBackground (u16_t A_u16Color)
Variables
MGPIOx_ConfigType TFT_A0
MGPIOx_ConfigType TFT_RST
Function Documentation
HTFT_vWriteCMD()
void HTFT_vWriteCMD (u16_t A_u16CMD)
Definition at line 35 of file TFT_program.c.
{
    MGPIOx_vSetPinValue(TFT_A0.Port, TFT_A0.Pin, GPIOx_LOW) ;
    (void)MSPI_u16Transcieve(SPI_SRC, A_u16CMD) ;
}
References GPIOx_LOW, MGPIOx_vSetPinValue(), MSPI_u16Transcieve(), MGPIOx_ConfigType::Pin, MGPIOx_ConfigType::Port, SPI_SRC, and TFT_A0.
Referenced by HTFT_vFillBackground(), HTFT_vFillRectangle(), HTFT_vInit(), HTFT_vSetXPosition(), HTFT_vSetYPosition(), and HTFT_vShowImage().
HTFT_vWriteData()
void HTFT_vWriteData (u16_t A_u16Data)
Definition at line 47 of file TFT_program.c.
{
    MGPIOx_vSetPinValue(TFT_A0.Port, TFT_A0.Pin, GPIOx_HIGH) ;
    (void)MSPI_u16Transcieve(SPI_SRC, A_u16Data) ;
}
References GPIOx_HIGH, MGPIOx_vSetPinValue(), MSPI_u16Transcieve(), MGPIOx_ConfigType::Pin, MGPIOx_ConfigType::Port, SPI_SRC, and TFT_A0.
Referenced by HTFT_vFillBackground(), HTFT_vFillRectangle(), HTFT_vInit(), HTFT_vSetXPosition(), HTFT_vSetYPosition(), and HTFT_vShowImage().
HTFT_vResetSequence()
void HTFT_vResetSequence (void)
Definition at line 59 of file TFT_program.c.
{
    MGPIOx_vSetPinValue(TFT_RST.Port, TFT_RST.Pin, GPIOx_HIGH) ;
    MSysTick_vDelayMicroSec(150) ; //100us
    MGPIOx_vSetPinValue(TFT_RST.Port, TFT_RST.Pin, GPIOx_LOW) ;
    MSysTick_vDelayMicroSec(5) ; //1us
    MGPIOx_vSetPinValue(TFT_RST.Port, TFT_RST.Pin, GPIOx_HIGH) ;
    MSysTick_vDelayMicroSec(150) ; //100us
    MGPIOx_vSetPinValue(TFT_RST.Port, TFT_RST.Pin, GPIOx_LOW) ;
    MSysTick_vDelayMicroSec(5) ; //1us
    MGPIOx_vSetPinValue(TFT_RST.Port, TFT_RST.Pin, GPIOx_HIGH) ;
    MSysTick_vDelayMilliSec(150) ; //120ms
}
References GPIOx_HIGH, GPIOx_LOW, MGPIOx_vSetPinValue(), MSysTick_vDelayMicroSec(), MSysTick_vDelayMilliSec(), MGPIOx_ConfigType::Pin, MGPIOx_ConfigType::Port, and TFT_RST.
Referenced by HTFT_vInit().
HTFT_vInit()
void HTFT_vInit (void)
Definition at line 87 of file TFT_program.c.
{
    // Set pin directions:
    MGPIOx_vInit(&TFT_A0) ;
    MGPIOx_vInit(&TFT_RST) ;
    MSPI_vInit(SPI_SRC, SPI_RELATION, SPI_DATA_DIRECTION) ;
    MSysTick_vInit() ;
    // Rest sequence:
    HTFT_vResetSequence() ;
    // Send SLPOUT CMD (0x11):
    HTFT_vWriteCMD(SLPOUT_CMD) ;
    // Wait 15ms:
    MSysTick_vDelayMilliSec(15) ;
    // Send color mode CMD -> RGB565:
    HTFT_vWriteCMD(COLOR_MODE_CMD) ;
    HTFT_vWriteData(RGB565_CMD) ;
    // DISPON CMD (0X29):
    HTFT_vWriteCMD(DISPON_CMD) ;
}
References COLOR_MODE_CMD, DISPON_CMD, HTFT_vResetSequence(), HTFT_vWriteCMD(), HTFT_vWriteData(), MGPIOx_vInit(), MSPI_vInit(), MSysTick_vDelayMilliSec(), MSysTick_vInit(), RGB565_CMD, SLPOUT_CMD, SPI_DATA_DIRECTION, SPI_RELATION, SPI_SRC, TFT_A0, and TFT_RST.
HTFT_vShowImage()
void HTFT_vShowImage (u16_t const * A_u16Image, u32_t A_u32ImageSize)
Definition at line 119 of file TFT_program.c.
{
    // Set X position:
    HTFT_vWriteCMD(XPOSITION_CMD) ;
    // Xstart: 0, Xend: 127
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(127) ;
    // Set Y position:
    HTFT_vWriteCMD(YPOSITION_CMD) ;
    // Ystart: 0, Yend: 159
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(159) ;
    // Send image data:
    HTFT_vWriteCMD(MEMORY_WRITE_CMD) ;
    for(u16_t PX = INITIAL_ZERO; PX < A_u32ImageSize; PX++)
    {
        HTFT_vWriteData(A_u16Image[PX] >> 8) ; // MSB
        HTFT_vWriteData(A_u16Image[PX] & 0x00FF) ; // LSB
    }
}
References HTFT_vWriteCMD(), HTFT_vWriteData(), INITIAL_ZERO, MEMORY_WRITE_CMD, XPOSITION_CMD, and YPOSITION_CMD.
HTFT_vSetXPosition()
void HTFT_vSetXPosition (u16_t A_u16XStart, u16_t A_u16XEnd)
Definition at line 156 of file TFT_program.c.
{
    CurrentXStart = A_u16XStart ;
    CurrentXEnd = A_u16XEnd ;
    HTFT_vWriteCMD(XPOSITION_CMD) ;
    // Xstart: 0, Xend: 127
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(A_u16XStart) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(A_u16XEnd) ;
}
References HTFT_vWriteCMD(), HTFT_vWriteData(), and XPOSITION_CMD.
HTFT_vSetYPosition()
void HTFT_vSetYPosition (u16_t A_u16YStart, u16_t A_u16YEnd)
Definition at line 175 of file TFT_program.c.
{
    CurrentYStart = A_u16YStart ;
    CurrentYEnd = A_u16YEnd ;
    HTFT_vWriteCMD(YPOSITION_CMD) ;
    // Ystart: 0, Yend: 127
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(A_u16YStart) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(A_u16YEnd) ;
}
References HTFT_vWriteCMD(), HTFT_vWriteData(), and YPOSITION_CMD.
HTFT_vFillRectangle()
void HTFT_vFillRectangle (u16_t A_u16Color)
Definition at line 194 of file TFT_program.c.
{
    u32_t PXLS_Num = (CurrentXEnd-CurrentXStart) * (CurrentYEnd-CurrentYStart) ;
    HTFT_vWriteCMD(MEMORY_WRITE_CMD) ;
    for(u8_t PX = 0; PX < PXLS_Num ; PX++)
    {
        HTFT_vWriteData(A_u16Color >> 8) ; // MSB
        HTFT_vWriteData(A_u16Color & 0x00FF) ; // LSB
    }
}
References HTFT_vWriteCMD(), HTFT_vWriteData(), and MEMORY_WRITE_CMD.
Referenced by HTFT_vFillBackground().
HTFT_vFillBackground()
void HTFT_vFillBackground (u16_t A_u16Color)
Definition at line 214 of file TFT_program.c.
{
    // Set X position:
    HTFT_vWriteCMD(XPOSITION_CMD) ;
    // Xstart: 0, Xend: 127
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(127) ;
    // Set Y position:
    HTFT_vWriteCMD(YPOSITION_CMD) ;
    // Ystart: 0, Yend: 127
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(0) ;
    HTFT_vWriteData(159) ;
    HTFT_vFillRectangle(A_u16Color) ;
}
References HTFT_vFillRectangle(), HTFT_vWriteCMD(), HTFT_vWriteData(), XPOSITION_CMD, and YPOSITION_CMD.
Variable Documentation
TFT_A0
MGPIOx_ConfigType TFT_A0 [extern]
Definition at line 14 of file TFT_Config.c.
Referenced by HTFT_vInit(), HTFT_vWriteCMD(), and HTFT_vWriteData().
TFT_RST
MGPIOx_ConfigType TFT_RST [extern]
Definition at line 22 of file TFT_Config.c.
Referenced by HTFT_vInit(), and HTFT_vResetSequence().