COTS/MCAL/UART/UART_interface.h File Reference
This file contains the interfacing information of UART driver.
Data Structures
struct USART_MemoryMapType
USART declaration structure for its registers.
struct USART_InitType
USART Clock declaration structure for.
struct USART_ClockInitTypeDef
USART Clock declaration structure for its registers.
Macros
#define USART1_BASE_ADDRESS (0x40011000)
#define USART2_BASE_ADDRESS (0x40004400)
#define USART6_BASE_ADDRESS (0x40011400)
#define USART1_REG ((USART_MemoryMapType *)USART1_BASE_ADDRESS)
#define USART2_REG ((USART_MemoryMapType *)USART2_BASE_ADDRESS)
#define USART6_REG ((USART_MemoryMapType *)USART6_BASE_ADDRESS)
#define OVER_SAMPLING_16 (0)
#define OVER_SAMPLING_8 (1)
#define TX_ONLY (0)
#define RX_ONLY (1)
#define TX_RX (2)
#define EVEN_PARITY (0)
#define ODD_PARITY (1)
#define MODE_8BIT (0)
#define MODE_9BIT (1)
#define STOP_BIT_1 (0)
#define STOP_BIT_0_5 (1)
#define STOP_BIT_2 (2)
#define STOP_BIT_1_5 (3)
#define ENABLE 1
#define DISABLE 0
#define __BAUDRATE__ 9600
Functions
void MUSART_vInit (USART_InitType *A_InitStruct, USART_ClockInitTypeDef *A_ClockInitStruct, USART_MemoryMapType *A_USARTx)
Sets a certain pin's output value on a speific port.
void MUSART_vEnable (USART_MemoryMapType *A_USARTx)
Enables the USART peripheral.
void MUSART_vDisable (USART_MemoryMapType *A_USARTx)
Disables the USART peripheral.
void MUSART_vTransmitByte (USART_MemoryMapType *A_USARTx, u8_t A_u8Byte)
Transmits a byte using the USART peripheral.
void MUSART_vTransmitString (USART_MemoryMapType *A_USARTx, c8_t *A_ptrc8String)
Transmits a string using the USART peripheral.
u8_t MUSART_u8ReceiveByteSynchNonBlocking (USART_MemoryMapType *A_USARTx)
Receives a byte using the USART peripheral (non-blocking)
u8_t MUSART_u8ReceiveByteSynchBlocking (USART_MemoryMapType *A_USARTx)
Receives a byte using the USART peripheral (blocking)
u8_t * MUSART_ptrReceiveStringSynchNonBlocking (USART_MemoryMapType *A_USARTx)
Receives a string using the USART peripheral (non-blocking)
void MUSART_vRecieveString (USART_MemoryMapType *A_USARTx, c8_t A_c8YourString[])
Receives a string using the USART peripheral (blocking)
u8_t MUSART_u8CompareString (c8_t *String1, c8_t *String2)
Compares two strings using the USART peripheral.
u8_t MUSART_u8ReadDataRegister (USART_MemoryMapType *A_USARTx)
Reads the status register of the USART peripheral.
void MUSART_vClearFlags (USART_MemoryMapType *A_USARTx)
Clears the status register of the USART peripheral.
void MUSART_vRxIntSetStatus (USART_MemoryMapType *A_USARTx, u8_t A_u8Status)
Set the status of the RX interrupt.
void MUSART1_vSetCallBack (void(*Fptr)(void))
Set UART1 RX callback function.
void MUSART2_vSetCallBack (void(*Fptr)(void))
Set UART2 RX callback function.
void MUSART6_vSetCallBack (void(*Fptr)(void))
Set UART6 RX callback function.
Detailed Description
This file contains the interfacing information of UART driver.
Author
Ali El Bana
Version
1.0
Date
10/14/2022
Definition in file UART_interface.h.
Macro Definition Documentation
ENABLE
#define ENABLE 1
Enable Status
Definition at line 400 of file UART_interface.h.
DISABLE
#define DISABLE 0
Disable Status
Definition at line 406 of file UART_interface.h.
__BAUDRATE__
#define __BAUDRATE__ 9600
Default baud rate of the UART peripheral
Definition at line 412 of file UART_interface.h.
Function Documentation
MUSART_vInit()
void MUSART_vInit (USART_InitType * A_InitStruct, USART_ClockInitTypeDef * A_ClockInitStruct, USART_MemoryMapType * A_USARTx)
Sets a certain pin's output value on a speific port.
Parameters
 in A_InitStruct Pointer to a structure that contains the configuration information for the specified USART peripheral.
 in A_ClockInitStruct Pointer to a structure that contains the configuration information for the specified USART peripheral.
 in A_USARTx Pointer to USARTx registers map
Definition at line 37 of file UART_program.c.
{
    if (A_USARTx == USART1_REG)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_USART1EN);
        /*configer Tx1 as alt fun*/
        MGPIOx_ConfigType TX1 =
            {
                .Port = USART1_PORT, .Pin = TX1_PIN, .Mode = GPIOx_MODE_AF, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_MediumSpeed, .InputType = GPIOx_NoPull, .AF_Type = GPIOx_AF7};
        MGPIOx_vInit(&TX1);
        /*configer Rx1 as alt fun*/
        MGPIOx_ConfigType RX1 =
            {
                .Port = USART1_PORT, .Pin = RX1_PIN, .Mode = GPIOx_MODE_AF, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_MediumSpeed, .InputType = GPIOx_NoPull, .AF_Type = GPIOx_AF7};
        MGPIOx_vInit(&RX1);
    }
    else if (A_USARTx == USART2_REG)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB2, APB1ENR_USART2EN);
        /*configer Tx2 as alt fun*/
        MGPIOx_ConfigType TX2 =
            {
                .Port = USART2_PORT, .Pin = TX2_PIN, .Mode = GPIOx_MODE_AF, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_MediumSpeed, .InputType = GPIOx_NoPull, .AF_Type = GPIOx_AF7};
        MGPIOx_vInit(&TX2);
        /*configer Rx2 as alt fun*/
        MGPIOx_ConfigType RX2 =
            {
                .Port = USART2_PORT, .Pin = RX2_PIN, .Mode = GPIOx_MODE_AF, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_MediumSpeed, .InputType = GPIOx_NoPull, .AF_Type = GPIOx_AF7};
        MGPIOx_vInit(&RX2);
    }
    else if (A_USARTx == USART6_REG)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_USART6EN);
        /*configer Tx6 as alt fun*/
        MGPIOx_ConfigType TX6 =
            {
                .Port = USART6_PORT, .Pin = TX6_PIN, .Mode = GPIOx_MODE_AF, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_MediumSpeed, .InputType = GPIOx_NoPull, .AF_Type = GPIOx_AF7};
        MGPIOx_vInit(&TX6);
        /*configer Rx6 as alt fun*/
        MGPIOx_ConfigType RX6 =
            {
                .Port = USART6_PORT, .Pin = RX6_PIN, .Mode = GPIOx_MODE_AF, .OutputType = GPIOx_PUSHPULL, .OutputSpeed = GPIOx_MediumSpeed, .InputType = GPIOx_NoPull, .AF_Type = GPIOx_AF7};
        MGPIOx_vInit(&RX6);
    }
    // BuadRate/Over-sampling selections:
    switch (A_InitStruct->Oversampling)
    {
    case OVER_SAMPLING_16:
        A_USARTx->BRR_REG = UART_BRR_SAMPLING16(__PCLK__, A_InitStruct->BaudRate);
        break;
    case OVER_SAMPLING_8:
        A_USARTx->BRR_REG = UART_BRR_SAMPLING16(__PCLK__, A_InitStruct->BaudRate);
        break;
    }
    A_USARTx->CR1_REG = (A_InitStruct->Oversampling << MUSART_CR1_OVER8_BIT) |
                        (A_InitStruct->DataWidth << MUSART_CR1_M_BIT) |
                        (A_InitStruct->Parity_Enable << MUSART_CR1_PCE_BIT) |
                        (A_InitStruct->Parity_Selection << MUSART_CR1_PS_BIT);
    switch (A_InitStruct->TransferDirection)
    {
    case TX_ONLY:
        SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_TE_BIT);
        break;
    case RX_ONLY:
        SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_RE_BIT);
        break;
    case TX_RX:
        SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_TE_BIT);
        SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_RE_BIT);
        break;
    }
    A_USARTx->CR2_REG = (A_InitStruct->StopBits << MUSART_CR2_STOP_BIT) |
                        (A_ClockInitStruct->ClockOutput << MUSART_CR2_CLKEN_BIT) |
                        (A_ClockInitStruct->ClockPhase << MUSART_CR2_CPHA_BIT) |
                        (A_ClockInitStruct->ClockPolarity << MUSART_CR2_CPOL_BIT) |
                        (A_ClockInitStruct->LastBitClockPulse << MUSART_CR2_LBCL_BIT);
    A_USARTx->SR_REG = 0; // Clear all the flags.
    SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_UE_BIT); // EN the peripheral.
}
References APB1ENR_USART2EN, APB2ENR_USART1EN, APB2ENR_USART6EN, USART_InitType::BaudRate, USART_MemoryMapType::BRR_REG, USART_ClockInitTypeDef::ClockOutput, USART_ClockInitTypeDef::ClockPhase, USART_ClockInitTypeDef::ClockPolarity, USART_MemoryMapType::CR1_REG, USART_MemoryMapType::CR2_REG, USART_InitType::DataWidth, GPIOx_AF7, GPIOx_MediumSpeed, GPIOx_MODE_AF, GPIOx_NoPull, GPIOx_PUSHPULL, USART_ClockInitTypeDef::LastBitClockPulse, MGPIOx_vInit(), MRCC_vEnablePeriphralCLK(), MUSART_vInit(), OVER_SAMPLING_16, OVER_SAMPLING_8, USART_InitType::Oversampling, USART_InitType::Parity_Enable, USART_InitType::Parity_Selection, MGPIOx_ConfigType::Port, RCC_APB2, SET_BIT, USART_MemoryMapType::SR_REG, USART_InitType::StopBits, USART_InitType::TransferDirection, TX_ONLY, TX_RX, USART1_REG, USART2_REG, and USART6_REG.
Referenced by MUSART_vInit().
MUSART_vEnable()
void MUSART_vEnable (USART_MemoryMapType * A_USARTx)
Enables the USART peripheral.
Parameters
 in A_USARTx Pointer to USARTx registers map
Definition at line 156 of file UART_program.c.
{
    SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_UE_BIT);
}
References USART_MemoryMapType::CR1_REG, MUSART_vEnable(), and SET_BIT.
Referenced by MUSART_vEnable().
MUSART_vDisable()
void MUSART_vDisable (USART_MemoryMapType * A_USARTx)
Disables the USART peripheral.
Parameters
 in A_USARTx Pointer to USARTx registers map
Definition at line 164 of file UART_program.c.
{
    CLR_BIT(A_USARTx->CR1_REG, MUSART_CR1_UE_BIT);
}
References CLR_BIT, USART_MemoryMapType::CR1_REG, and MUSART_vDisable().
Referenced by MUSART_vDisable().
MUSART_vTransmitByte()
void MUSART_vTransmitByte (USART_MemoryMapType * A_USARTx, u8_t A_u8Byte)
Transmits a byte using the USART peripheral.
Parameters
 in A_USARTx Pointer to USARTx registers map
 in A_u8Byte Byte to be transmitted
Definition at line 172 of file UART_program.c.
{
    while (GET_BIT(A_USARTx->SR_REG, MUSART_SR_TXE_BIT) == 0)
        ;
    A_USARTx->DR_REG = A_u8Byte;
    while (GET_BIT(A_USARTx->SR_REG, MUSART_SR_TC_BIT) == 0)
        ;
    // Clear the TC flag:
    CLR_BIT(A_USARTx->SR_REG, MUSART_SR_TC_BIT);
}
References CLR_BIT, USART_MemoryMapType::DR_REG, GET_BIT, MUSART_vTransmitByte(), and USART_MemoryMapType::SR_REG.
Referenced by MUSART_vTransmitByte(), and MUSART_vTransmitString().
MUSART_vTransmitString()
void MUSART_vTransmitString (USART_MemoryMapType * A_USARTx, c8_t * A_ptrc8String)
Transmits a string using the USART peripheral.
Parameters
 in A_USARTx Pointer to USARTx registers map
 in A_ptrc8String Pointer to the string to be transmitted
Definition at line 190 of file UART_program.c.
{
    u8_t loc_u8Iterator = INITIAL_ZERO;
    while (A_ptrc8String[loc_u8Iterator] != '\0')
    {
        MUSART_vTransmitByte(A_USARTx, A_ptrc8String[loc_u8Iterator]);
        loc_u8Iterator++;
    }
}
References INITIAL_ZERO, MUSART_vTransmitByte(), and MUSART_vTransmitString().
Referenced by MUSART_vTransmitString().
MUSART_u8ReceiveByteSynchNonBlocking()
u8_t MUSART_u8ReceiveByteSynchNonBlocking (USART_MemoryMapType * A_USARTx)
Receives a byte using the USART peripheral (non-blocking)
Parameters
 in A_USARTx Pointer to USARTx registers map
Returns
Received byte from the USART peripheral
Definition at line 207 of file UART_program.c.
{
    u8_t loc_u8Data = INITIAL_ZERO;
    u32_t loc_u8TimeOut = INITIAL_ZERO;
    while ((GET_BIT(A_USARTx->SR_REG, MUSART_SR_RXNE_BIT) == 0) && (loc_u8TimeOut < THRESHOLD_VALUE))
    {
        loc_u8TimeOut++;
    }
    if (loc_u8TimeOut == THRESHOLD_VALUE)
    {
        loc_u8Data = 255; // To detect the error.
    }
    else
    {
        loc_u8Data = A_USARTx->DR_REG;
    }
    return loc_u8Data;
}
References USART_MemoryMapType::DR_REG, GET_BIT, INITIAL_ZERO, MUSART_u8ReceiveByteSynchNonBlocking(), and USART_MemoryMapType::SR_REG.
Referenced by MUSART_ptrReceiveStringSynchNonBlocking(), and MUSART_u8ReceiveByteSynchNonBlocking().
MUSART_u8ReceiveByteSynchBlocking()
u8_t MUSART_u8ReceiveByteSynchBlocking (USART_MemoryMapType * A_USARTx)
Receives a byte using the USART peripheral (blocking)
Parameters
 in A_USARTx Pointer to USARTx registers map
Returns
Received byte from the USART peripheral
Definition at line 234 of file UART_program.c.
{
    while (GET_BIT(A_USARTx->SR_REG, MUSART_SR_RXNE_BIT) == 0)
        ;
    return A_USARTx->DR_REG;
}
References USART_MemoryMapType::DR_REG, GET_BIT, MUSART_u8ReceiveByteSynchBlocking(), and USART_MemoryMapType::SR_REG.
Referenced by MUSART_u8ReceiveByteSynchBlocking(), and MUSART_vRecieveString().
MUSART_ptrReceiveStringSynchNonBlocking()
u8_t * MUSART_ptrReceiveStringSynchNonBlocking (USART_MemoryMapType * A_USARTx)
Receives a string using the USART peripheral (non-blocking)
Parameters
 in A_USARTx Pointer to USARTx registers map
Returns
Pointer to the received string from the USART peripheral
Definition at line 246 of file UART_program.c.
{
    u8_t loc_u8Iterator = INITIAL_ZERO;
    u8_t loc_u8DataCome;
    while ((loc_u8DataCome = MUSART_u8ReceiveByteSynchNonBlocking(A_USARTx)) != 13)
    {
        G_u8String[loc_u8Iterator] = loc_u8DataCome;
        loc_u8Iterator++;
    }
    G_u8String[loc_u8Iterator] = '\0';
    return (G_u8String);
}
References INITIAL_ZERO, MUSART_ptrReceiveStringSynchNonBlocking(), and MUSART_u8ReceiveByteSynchNonBlocking().
Referenced by MUSART_ptrReceiveStringSynchNonBlocking().
MUSART_vRecieveString()
void MUSART_vRecieveString (USART_MemoryMapType * A_USARTx, c8_t A_c8YourString[])
Receives a string using the USART peripheral (blocking)
Parameters
 in A_USARTx Pointer to USARTx registers map
 in A_c8YourString Pointer to the string to be transmitted
Definition at line 268 of file UART_program.c.
{
    u32_t L_u32Counter = INITIAL_ZERO;
    A_c8YourString[L_u32Counter] = MUSART_u8ReceiveByteSynchBlocking(A_USARTx);
    while (A_c8YourString[L_u32Counter] != '\0')
    {
        L_u32Counter++;
        A_c8YourString[L_u32Counter] = MUSART_u8ReceiveByteSynchBlocking(A_USARTx);
        if ((A_c8YourString[L_u32Counter] == '\n') || (A_c8YourString[L_u32Counter] == '\r'))
        {
            A_c8YourString[L_u32Counter] = '\0';
        }
    }
}
References INITIAL_ZERO, MUSART_u8ReceiveByteSynchBlocking(), and MUSART_vRecieveString().
Referenced by MUSART_vRecieveString().
MUSART_u8CompareString()
u8_t MUSART_u8CompareString (c8_t * String1, c8_t * String2)
Compares two strings using the USART peripheral.
Parameters
 in String1 Pointer to the first string
 in String2 Pointer to the second string
Returns
SAME_STRING if the strings are equal, DIFFERENT_STRING if not
See also
SAME_STRING DIFFERENT_STRING
Definition at line 292 of file UART_program.c.
{
    u8_t L_u8TheComparingResult = INITIAL_ZERO;
    if (strcmp(String1, String2) == SAME_STRING)
    {
        L_u8TheComparingResult = SAME_STRING;
    }
    else
    {
        L_u8TheComparingResult = DIFFERENT_STRING;
    }
    return L_u8TheComparingResult;
}
References DIFFERENT_STRING, INITIAL_ZERO, MUSART_u8CompareString(), and SAME_STRING.
Referenced by MUSART_u8CompareString().
MUSART_u8ReadDataRegister()
u8_t MUSART_u8ReadDataRegister (USART_MemoryMapType * A_USARTx)
Reads the status register of the USART peripheral.
Parameters
 in A_USARTx Pointer to USARTx registers map
Returns
Status register value
Definition at line 312 of file UART_program.c.
{
    return A_USARTx->DR_REG;
}
References USART_MemoryMapType::DR_REG, and MUSART_u8ReadDataRegister().
Referenced by MUSART_u8ReadDataRegister().
MUSART_vClearFlags()
void MUSART_vClearFlags (USART_MemoryMapType * A_USARTx)
Clears the status register of the USART peripheral.
Parameters
 in A_USARTx Pointer to USARTx registers map
Definition at line 320 of file UART_program.c.
{
    A_USARTx->SR_REG = 0;
}
References MUSART_vClearFlags(), and USART_MemoryMapType::SR_REG.
Referenced by MUSART_vClearFlags().
MUSART_vRxIntSetStatus()
void MUSART_vRxIntSetStatus (USART_MemoryMapType * A_USARTx, u8_t A_u8Status)
Set the status of the RX interrupt.
Parameters
 in A_USARTx Pointer to USARTx registers map
 in A_u8Status Status of the RX interrupt (ENABLE/DISABLE)
See also
ENABLE DISABLE
Definition at line 328 of file UART_program.c.
{
    switch (A_u8Status)
    {
    case ENABLE:
        SET_BIT(A_USARTx->CR1_REG, (MUSART_CR1_RXNEIE_BIT));
        break;
    case DISABLE:
        CLR_BIT(A_USARTx->CR1_REG, (MUSART_CR1_RXNEIE_BIT));
        break;
    }
}
References CLR_BIT, USART_MemoryMapType::CR1_REG, MUSART_vRxIntSetStatus(), and SET_BIT.
Referenced by MUSART_vRxIntSetStatus().
MUSART1_vSetCallBack()
void MUSART1_vSetCallBack (void(*)(void) Fptr)
Set UART1 RX callback function.
Parameters
 in Fptr Pointer to the callback function
Definition at line 347 of file UART_program.c.
{
    MUSART1_CallBack = Fptr;
}
References MUSART1_vSetCallBack().
Referenced by MUSART1_vSetCallBack().
MUSART2_vSetCallBack()
void MUSART2_vSetCallBack (void(*)(void) Fptr)
Set UART2 RX callback function.
Parameters
 in Fptr Pointer to the callback function
Definition at line 355 of file UART_program.c.
{
    MUSART2_CallBack = Fptr;
}
References MUSART2_vSetCallBack().
Referenced by MUSART2_vSetCallBack().
MUSART6_vSetCallBack()
void MUSART6_vSetCallBack (void(*)(void) Fptr)
Set UART6 RX callback function.
Parameters
 in Fptr Pointer to the callback function
Definition at line 363 of file UART_program.c.
{
    MUSART6_CallBack = Fptr;
}
References MUSART6_vSetCallBack().
Referenced by MUSART6_vSetCallBack().