COTS/MCAL/UART/UART_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `string.h`
#include `../RCC/MRCC_interface.h`
#include `../GPIO/GPIO_interface.h`
#include `UART_interface.h`
#include `UART_private.h`
#include `UART_config.h`
Functions
void MUSART_vInit (USART_InitType *A_InitStruct, USART_ClockInitTypeDef *A_ClockInitStruct, USART_MemoryMapType *A_USARTx)
void MUSART_vEnable (USART_MemoryMapType *A_USARTx)
void MUSART_vDisable (USART_MemoryMapType *A_USARTx)
void MUSART_vTransmitByte (USART_MemoryMapType *A_USARTx, u8_t A_u8Byte)
void MUSART_vTransmitString (USART_MemoryMapType *A_USARTx, c8_t *A_ptrc8String)
u8_t MUSART_u8ReceiveByteSynchNonBlocking (USART_MemoryMapType *A_USARTx)
u8_t MUSART_u8ReceiveByteSynchBlocking (USART_MemoryMapType *A_USARTx)
u8_t * MUSART_ptrReceiveStringSynchNonBlocking (USART_MemoryMapType *A_USARTx)
void MUSART_vRecieveString (USART_MemoryMapType *A_USARTx, c8_t A_c8YourString[])
u8_t MUSART_u8CompareString (c8_t *String1, c8_t *String2)
u8_t MUSART_u8ReadDataRegister (USART_MemoryMapType *A_USARTx)
void MUSART_vClearFlags (USART_MemoryMapType *A_USARTx)
void MUSART_vRxIntSetStatus (USART_MemoryMapType *A_USARTx, u8_t A_u8Status)
void MUSART1_vSetCallBack (void(*Fptr)(void))
void MUSART2_vSetCallBack (void(*Fptr)(void))
void MUSART6_vSetCallBack (void(*Fptr)(void))
void USART1_IRQHandler (void)
void USART2_IRQHandler (void)
void USART6_IRQHandler (void)
Variables
u8_t G_u8String [20]
void(* MUSART1_CallBack)(void)
void(* MUSART2_CallBack)(void)
void(* MUSART6_CallBack)(void)
Function Documentation
MUSART_vInit()
void MUSART_vInit (USART_InitType * A_InitStruct, USART_ClockInitTypeDef * A_ClockInitStruct, USART_MemoryMapType * A_USARTx)
Definition at line 37 of file UART_program.c.
{
    if(A_USARTx == USART1_REG)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_USART1EN) ;
        /*configer Tx1 as alt fun*/
        MGPIOx_ConfigType TX1 =
        {
            .Port = USART1_PORT , .Pin = TX1_PIN ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_MediumSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF7
        } ;
        MGPIOx_vInit(&TX1) ;
        /*configer Rx1 as alt fun*/
        MGPIOx_ConfigType RX1 =
        {
            .Port = USART1_PORT , .Pin = RX1_PIN ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_MediumSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF7
        } ;
        MGPIOx_vInit(&RX1) ;
    }
    else if(A_USARTx == USART2_REG)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB2, APB1ENR_USART2EN) ;
        /*configer Tx2 as alt fun*/
        MGPIOx_ConfigType TX2 =
        {
            .Port = USART2_PORT , .Pin = TX2_PIN ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_MediumSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF7
        } ;
        MGPIOx_vInit(&TX2) ;
        /*configer Rx2 as alt fun*/
        MGPIOx_ConfigType RX2 =
        {
            .Port = USART2_PORT , .Pin = RX2_PIN ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_MediumSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF7
        } ;
        MGPIOx_vInit(&RX2) ;
    }
    else if(A_USARTx == USART6_REG)
    {
        MRCC_vEnablePeriphralCLK(RCC_APB2, APB2ENR_USART6EN) ;
        /*configer Tx6 as alt fun*/
        MGPIOx_ConfigType TX6 =
        {
            .Port = USART6_PORT , .Pin = TX6_PIN ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_MediumSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF7
        } ;
        MGPIOx_vInit(&TX6) ;
        /*configer Rx6 as alt fun*/
        MGPIOx_ConfigType RX6 =
        {
            .Port = USART6_PORT , .Pin = RX6_PIN ,
            .Mode = GPIOx_MODE_AF , .OutputType = GPIOx_PUSHPULL,
            .OutputSpeed = GPIOx_MediumSpeed , .InputType = GPIOx_NoPull ,
            .AF_Type = GPIOx_AF7
        } ;
        MGPIOx_vInit(&RX6) ;
    }
    // BuadRate/Over-sampling selections:
    switch(A_InitStruct->Oversampling)
    {
        case OVER_SAMPLING_16:
            A_USARTx->BRR_REG = UART_BRR_SAMPLING16(__PCLK__ , A_InitStruct->BaudRate) ;
        break;
        case OVER_SAMPLING_8:
            A_USARTx->BRR_REG = UART_BRR_SAMPLING16(__PCLK__ , A_InitStruct->BaudRate) ;
        break;
    }
    A_USARTx->CR1_REG = (A_InitStruct->Oversampling << MUSART_CR1_OVER8_BIT) |
                        (A_InitStruct->DataWidth << MUSART_CR1_M_BIT) |
                        (A_InitStruct->Parity_Enable << MUSART_CR1_PCE_BIT) |
                        (A_InitStruct->Parity_Selection << MUSART_CR1_PS_BIT) ;
    switch (A_InitStruct->TransferDirection)
    {
        case TX_ONLY:
            SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_TE_BIT) ;
        break ;
        case RX_ONLY:
            SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_RE_BIT) ;
        break ;
        case TX_RX :
            SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_TE_BIT) ;
            SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_RE_BIT) ;
        break ;
    }
    A_USARTx->CR2_REG = (A_InitStruct->StopBits << MUSART_CR2_STOP_BIT) |
                        (A_ClockInitStruct->ClockOutput << MUSART_CR2_CLKEN_BIT) |
                        (A_ClockInitStruct->ClockPhase << MUSART_CR2_CPHA_BIT) |
                        (A_ClockInitStruct->ClockPolarity << MUSART_CR2_CPOL_BIT) |
                        (A_ClockInitStruct->LastBitClockPulse << MUSART_CR2_LBCL_BIT) ;
    A_USARTx->SR_REG = 0 ; // Clear all the flags.
    SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_UE_BIT) ; // EN the peripheral.
}
References __PCLK__, APB1ENR_USART2EN, APB2ENR_USART1EN, APB2ENR_USART6EN, USART_InitType::BaudRate, USART_MemoryMapType::BRR_REG, USART_ClockInitTypeDef::ClockOutput, USART_ClockInitTypeDef::ClockPhase, USART_ClockInitTypeDef::ClockPolarity, USART_MemoryMapType::CR1_REG, USART_MemoryMapType::CR2_REG, USART_InitType::DataWidth, GPIOx_AF7, GPIOx_MediumSpeed, GPIOx_MODE_AF, GPIOx_NoPull, GPIOx_PUSHPULL, USART_ClockInitTypeDef::LastBitClockPulse, MGPIOx_vInit(), MRCC_vEnablePeriphralCLK(), MUSART_CR1_M_BIT, MUSART_CR1_OVER8_BIT, MUSART_CR1_PCE_BIT, MUSART_CR1_PS_BIT, MUSART_CR1_RE_BIT, MUSART_CR1_TE_BIT, MUSART_CR1_UE_BIT, MUSART_CR2_CLKEN_BIT, MUSART_CR2_CPHA_BIT, MUSART_CR2_CPOL_BIT, MUSART_CR2_LBCL_BIT, MUSART_CR2_STOP_BIT, OVER_SAMPLING_16, OVER_SAMPLING_8, USART_InitType::Oversampling, USART_InitType::Parity_Enable, USART_InitType::Parity_Selection, MGPIOx_ConfigType::Port, RCC_APB2, RX1_PIN, RX2_PIN, RX6_PIN, RX_ONLY, SET_BIT, USART_MemoryMapType::SR_REG, USART_InitType::StopBits, USART_InitType::TransferDirection, TX1_PIN, TX2_PIN, TX6_PIN, TX_ONLY, TX_RX, UART_BRR_SAMPLING16, USART1_PORT, USART1_REG, USART2_PORT, USART2_REG, USART6_PORT, and USART6_REG.
Referenced by HBluetooth_vInit().
MUSART_vEnable()
void MUSART_vEnable (USART_MemoryMapType * A_USARTx)
Definition at line 187 of file UART_program.c.
{
    SET_BIT(A_USARTx->CR1_REG, MUSART_CR1_UE_BIT) ;
}
References USART_MemoryMapType::CR1_REG, MUSART_CR1_UE_BIT, and SET_BIT.
Referenced by HBluetooth_vEnable().
MUSART_vDisable()
void MUSART_vDisable (USART_MemoryMapType * A_USARTx)
Definition at line 195 of file UART_program.c.
{
    CLR_BIT(A_USARTx->CR1_REG, MUSART_CR1_UE_BIT) ;
}
References CLR_BIT, USART_MemoryMapType::CR1_REG, and MUSART_CR1_UE_BIT.
Referenced by HBluetooth_vDisable().
MUSART_vTransmitByte()
void MUSART_vTransmitByte (USART_MemoryMapType * A_USARTx, u8_t A_u8Byte)
Definition at line 203 of file UART_program.c.
{
    while(GET_BIT(A_USARTx->SR_REG, MUSART_SR_TXE_BIT) == 0) ;
    A_USARTx->DR_REG = A_u8Byte ;
    while(GET_BIT(A_USARTx->SR_REG, MUSART_SR_TC_BIT) == 0) ;
    // Clear the TC flag:
    CLR_BIT(A_USARTx->SR_REG, MUSART_SR_TC_BIT) ;
}
References CLR_BIT, USART_MemoryMapType::DR_REG, GET_BIT, MUSART_SR_TC_BIT, MUSART_SR_TXE_BIT, and USART_MemoryMapType::SR_REG.
Referenced by HBluetooth_vSendByte(), and MUSART_vTransmitString().
MUSART_vTransmitString()
void MUSART_vTransmitString (USART_MemoryMapType * A_USARTx, c8_t * A_ptrc8String)
Definition at line 220 of file UART_program.c.
{
    u8_t loc_u8Iterator = INITIAL_ZERO ;
    while(A_ptrc8String[loc_u8Iterator] != '\0')
    {
        MUSART_vTransmitByte(A_USARTx, A_ptrc8String[loc_u8Iterator]) ;
        loc_u8Iterator++ ;
    }
}
References INITIAL_ZERO, and MUSART_vTransmitByte().
Referenced by HBluetooth_vSendString().
MUSART_u8ReceiveByteSynchNonBlocking()
u8_t MUSART_u8ReceiveByteSynchNonBlocking (USART_MemoryMapType * A_USARTx)
Definition at line 239 of file UART_program.c.
{
    u8_t loc_u8Data = INITIAL_ZERO ;
    u32_t loc_u8TimeOut = INITIAL_ZERO ;
    while((GET_BIT(A_USARTx->SR_REG, MUSART_SR_RXNE_BIT) == 0) && (loc_u8TimeOut < THRESHOLD_VALUE))
    {
        loc_u8TimeOut++;
    }
    if (loc_u8TimeOut == THRESHOLD_VALUE)
    {
        loc_u8Data = 255 ; // To detect the error.
    }
    else
    {
        loc_u8Data = A_USARTx->DR_REG ;
    }
    return loc_u8Data ;
}
References USART_MemoryMapType::DR_REG, GET_BIT, INITIAL_ZERO, MUSART_SR_RXNE_BIT, USART_MemoryMapType::SR_REG, and THRESHOLD_VALUE.
Referenced by MUSART_ptrReceiveStringSynchNonBlocking().
MUSART_u8ReceiveByteSynchBlocking()
u8_t MUSART_u8ReceiveByteSynchBlocking (USART_MemoryMapType * A_USARTx)
Definition at line 267 of file UART_program.c.
{
    while(GET_BIT(A_USARTx->SR_REG, MUSART_SR_RXNE_BIT) == 0) ;
    return A_USARTx->DR_REG ;
}
References USART_MemoryMapType::DR_REG, GET_BIT, MUSART_SR_RXNE_BIT, and USART_MemoryMapType::SR_REG.
Referenced by HBluetooth_u8ReceiveByte(), and MUSART_vRecieveString().
MUSART_ptrReceiveStringSynchNonBlocking()
u8_t * MUSART_ptrReceiveStringSynchNonBlocking (USART_MemoryMapType * A_USARTx)
Definition at line 279 of file UART_program.c.
{
    u8_t loc_u8Iterator = INITIAL_ZERO ;
    u8_t loc_u8DataCome ;
    while((loc_u8DataCome = MUSART_u8ReceiveByteSynchNonBlocking(A_USARTx)) != 13)
    {
        G_u8String[ loc_u8Iterator ] = loc_u8DataCome ;
        loc_u8Iterator++;
    }
    G_u8String[loc_u8Iterator] = '\0' ;
    return(G_u8String) ;
}
References G_u8String, INITIAL_ZERO, and MUSART_u8ReceiveByteSynchNonBlocking().
MUSART_vRecieveString()
void MUSART_vRecieveString (USART_MemoryMapType * A_USARTx, c8_t A_c8YourString[])
Definition at line 302 of file UART_program.c.
{
    u32_t L_u32Counter = INITIAL_ZERO ;
    A_c8YourString[L_u32Counter] = MUSART_u8ReceiveByteSynchBlocking(A_USARTx) ;
    while(A_c8YourString[L_u32Counter] != '\0')
    {
        L_u32Counter++ ;
        A_c8YourString[L_u32Counter] = MUSART_u8ReceiveByteSynchBlocking(A_USARTx) ;
        if((A_c8YourString[L_u32Counter] == '\n') || (A_c8YourString[L_u32Counter] == '\r'))
        {
            A_c8YourString[L_u32Counter] = '\0' ;
        }
    }
}
References INITIAL_ZERO, and MUSART_u8ReceiveByteSynchBlocking().
Referenced by HBluetooth_vReceiveString().
MUSART_u8CompareString()
u8_t MUSART_u8CompareString (c8_t * String1, c8_t * String2)
Definition at line 328 of file UART_program.c.
{
    u8_t L_u8TheComparingResult = INITIAL_ZERO ;
    if(strcmp(String1, String2) == SAME_STRING)
    {
        L_u8TheComparingResult = SAME_STRING ;
    }
    else
    {
        L_u8TheComparingResult = DIFFERENT_STRING ;
    }
    return L_u8TheComparingResult ;
}
References DIFFERENT_STRING, INITIAL_ZERO, and SAME_STRING.
Referenced by HBluetooth_u8CompStrings().
MUSART_u8ReadDataRegister()
u8_t MUSART_u8ReadDataRegister (USART_MemoryMapType * A_USARTx)
Definition at line 349 of file UART_program.c.
{
    return A_USARTx->DR_REG ;
}
References USART_MemoryMapType::DR_REG.
Referenced by HBluetooth_u8GetDataRegister().
MUSART_vClearFlags()
void MUSART_vClearFlags (USART_MemoryMapType * A_USARTx)
Definition at line 357 of file UART_program.c.
{
    A_USARTx->SR_REG = 0 ;
}
References USART_MemoryMapType::SR_REG.
MUSART_vRxIntSetStatus()
void MUSART_vRxIntSetStatus (USART_MemoryMapType * A_USARTx, u8_t A_u8Status)
Definition at line 365 of file UART_program.c.
{
    switch(A_u8Status)
    {
        case ENABLE : SET_BIT(A_USARTx->CR1_REG, (MUSART_CR1_RXNEIE_BIT)); break ;
        case DISABLE: CLR_BIT(A_USARTx->CR1_REG, (MUSART_CR1_RXNEIE_BIT)); break ;
    }
}
References CLR_BIT, USART_MemoryMapType::CR1_REG, DISABLE, ENABLE, MUSART_CR1_RXNEIE_BIT, and SET_BIT.
Referenced by HBluetooth_vDisableAsynchReceive(), and HBluetooth_vEnableAsynchReceive().
MUSART1_vSetCallBack()
void MUSART1_vSetCallBack (void(*)(void) Fptr)
Definition at line 382 of file UART_program.c.
{
    MUSART1_CallBack = Fptr ;
}
References MUSART1_CallBack.
Referenced by HBluetooth_u8AsynchReceiveByte().
MUSART2_vSetCallBack()
void MUSART2_vSetCallBack (void(*)(void) Fptr)
Definition at line 390 of file UART_program.c.
{
    MUSART2_CallBack = Fptr ;
}
References MUSART2_CallBack.
MUSART6_vSetCallBack()
void MUSART6_vSetCallBack (void(*)(void) Fptr)
Definition at line 398 of file UART_program.c.
{
    MUSART6_CallBack = Fptr ;
}
References MUSART6_CallBack.
USART1_IRQHandler()
void USART1_IRQHandler (void)
Definition at line 406 of file UART_program.c.
{
    if(MUSART1_CallBack != NULL)
    {
        MUSART1_CallBack() ;
    }
}
References MUSART1_CallBack, and NULL.
USART2_IRQHandler()
void USART2_IRQHandler (void)
Definition at line 419 of file UART_program.c.
{
    USART2_REG -> SR_REG = 0 ;
    MUSART2_CallBack() ;
}
References MUSART2_CallBack, and USART2_REG.
USART6_IRQHandler()
void USART6_IRQHandler (void)
Definition at line 431 of file UART_program.c.
{
    USART6_REG->SR_REG = 0 ;
    MUSART6_CallBack() ;
}
References MUSART6_CallBack, and USART6_REG.
Variable Documentation
G_u8String
u8_t G_u8String[20]
Definition at line 28 of file UART_program.c.
Referenced by MUSART_ptrReceiveStringSynchNonBlocking().
MUSART1_CallBack
void(* MUSART1_CallBack) (void) (void)
Definition at line 30 of file UART_program.c.
Referenced by MUSART1_vSetCallBack(), and USART1_IRQHandler().
MUSART2_CallBack
void(* MUSART2_CallBack) (void) (void)
Definition at line 31 of file UART_program.c.
Referenced by MUSART2_vSetCallBack(), and USART2_IRQHandler().
MUSART6_CallBack
void(* MUSART6_CallBack) (void) (void)
Definition at line 32 of file UART_program.c.
Referenced by MUSART6_vSetCallBack(), and USART6_IRQHandler().