COTS/HAL/UltraSonic/UltraSonic_interface.h File Reference
This file is a header file that contains the Ultrasonic sensor functions prototypes.
Data Structures
struct HULTSNC_ConfigType
Ultrasonic Configurations.
Functions
void HULTSNC_vInit (HULTSNC_ConfigType *TRIG_psCfg)
This function is responsible for initializing the ultrasonic sensor.
void HULTSNC_vTrigger (HULTSNC_ConfigType *TRIG_psCfg)
This function is responsible for triggering the ultrasonic sensor.
f32_t HULTSNC_f32GetDistance (void)
This function is responsible for getting the distance measured by the ultrasonic sensor.
Detailed Description
This file is a header file that contains the Ultrasonic sensor functions prototypes.
Version
1.0
Date
02/24/2023
Author
Ali El Bana
Definition in file UltraSonic_interface.h.
Function Documentation
HULTSNC_vInit()
void HULTSNC_vInit (HULTSNC_ConfigType * TRIG_psCfg)
This function is responsible for initializing the ultrasonic sensor.
Parameters
TRIG_psCfg pointer to a struct that holds the trigger pin configurations
Definition at line 28 of file UltraSonic_program.c.
{
    VAR(MGPIOx_ConfigType) TRIG_Cfg =
    {
        .Port = TRIG_psCfg->u8Port, .Pin = TRIG_psCfg->u8Pin ,
        .Mode = GPIOx_MODE_OUTPUT , .OutputType = GPIOx_PUSHPULL ,
        .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull
    } ;
    MGPIOx_vInit(&TRIG_Cfg) ;
    MTIM1_vSetPrescalerValue(7) ;
    MTIM1_vSetAutoReloadValue(10000) ;
    MTIM1_vReadPWM() ;
}
References GPIOx_LowSpeed, GPIOx_MODE_OUTPUT, GPIOx_NoPull, GPIOx_PUSHPULL, HULTSNC_vInit(), MGPIOx_vInit(), HULTSNC_ConfigType::u8Pin, HULTSNC_ConfigType::u8Port, and VAR.
Referenced by HDCM_vMotorSpeedCntrl(), and HULTSNC_vInit().
HULTSNC_vTrigger()
void HULTSNC_vTrigger (HULTSNC_ConfigType * TRIG_psCfg)
This function is responsible for triggering the ultrasonic sensor.
Parameters
TRIG_psCfg pointer to a struct that holds the trigger pin configurations
Definition at line 51 of file UltraSonic_program.c.
{
    MGPIOx_vSetResetAtomic(TRIG_psCfg->u8Port, TRIG_psCfg->u8Pin, GPIOx_LOW) ;
    MSysTick_vDelayMicroSec(2) ;
    MGPIOx_vSetResetAtomic(TRIG_psCfg->u8Port, TRIG_psCfg->u8Pin, GPIOx_HIGH) ;
    MSysTick_vDelayMicroSec(10) ;
    MGPIOx_vSetResetAtomic(TRIG_psCfg->u8Port, TRIG_psCfg->u8Pin, GPIOx_LOW) ;
}
References GPIOx_HIGH, GPIOx_LOW, HULTSNC_vTrigger(), MGPIOx_vSetResetAtomic(), MSysTick_vDelayMicroSec(), HULTSNC_ConfigType::u8Pin, and HULTSNC_ConfigType::u8Port.
Referenced by HULTSNC_vTrigger().
HULTSNC_f32GetDistance()
f32_t HULTSNC_f32GetDistance (void)
This function is responsible for getting the distance measured by the ultrasonic sensor.
Returns
distance measured by the ultrasonic sensor
Definition at line 69 of file UltraSonic_program.c.
{
    f32_t L_f32PulseTime = MTIM1_u16GetCaptureReg2Value() ;
    f32_t L_f32Period = MTIM1_u16GetCaptureReg1Value() ;
    f32_t L_f32Distance = INITIAL_ZERO ;
    L_f32Distance = (float)(L_f32PulseTime * 0.0174) ;
    return L_f32Distance ;
}
References HULTSNC_f32GetDistance(), and INITIAL_ZERO.
Referenced by HULTSNC_f32GetDistance().