COTS/HAL/UltraSonic/UltraSonic_program.c File Reference
#include `../../LIB/LSTD_TYPES.h`
#include `../../LIB/LSTD_COMPILER.h`
#include `../../LIB/LSTD_VALUES.h`
#include `../../LIB/LSTD_BITMATH.h`
#include `../../MCAL/RCC/MRCC_interface.h`
#include `../../MCAL/GPIO/GPIO_interface.h`
#include `../../MCAL/SysTick/SysTick_interface.h`
#include `../../MCAL/TIM1/TIM1_interface.h`
#include `UltraSonic_interface.h`
#include `UltraSonic_private.h`
#include `UltraSonic_config.h`
Functions
void HULTSNC_vInit (HULTSNC_ConfigType *TRIG_psCfg)
void HULTSNC_vTrigger (HULTSNC_ConfigType *TRIG_psCfg)
f32_t HULTSNC_f32GetDistance (void)
Function Documentation
HULTSNC_vInit()
void HULTSNC_vInit (HULTSNC_ConfigType * TRIG_psCfg)
Definition at line 28 of file UltraSonic_program.c.
{
    VAR(MGPIOx_ConfigType) TRIG_Cfg =
    {
        .Port = TRIG_psCfg->u8Port, .Pin = TRIG_psCfg->u8Pin ,
        .Mode = GPIOx_MODE_OUTPUT , .OutputType = GPIOx_PUSHPULL ,
        .OutputSpeed = GPIOx_LowSpeed , .InputType = GPIOx_NoPull
    } ;
    MGPIOx_vInit(&TRIG_Cfg) ;
    MTIM1_vSetPrescalerValue(7) ;
    MTIM1_vSetAutoReloadValue(10000) ;
    MTIM1_vReadPWM() ;
}
References GPIOx_LowSpeed, GPIOx_MODE_OUTPUT, GPIOx_NoPull, GPIOx_PUSHPULL, MGPIOx_vInit(), MTIM1_vReadPWM(), MTIM1_vSetAutoReloadValue(), MTIM1_vSetPrescalerValue(), HULTSNC_ConfigType::u8Pin, HULTSNC_ConfigType::u8Port, and VAR.
HULTSNC_vTrigger()
void HULTSNC_vTrigger (HULTSNC_ConfigType * TRIG_psCfg)
Definition at line 51 of file UltraSonic_program.c.
{
    MGPIOx_vSetResetAtomic(TRIG_psCfg->u8Port, TRIG_psCfg->u8Pin, GPIOx_LOW) ;
    MSysTick_vDelayMicroSec(2) ;
    MGPIOx_vSetResetAtomic(TRIG_psCfg->u8Port, TRIG_psCfg->u8Pin, GPIOx_HIGH) ;
    MSysTick_vDelayMicroSec(10) ;
    MGPIOx_vSetResetAtomic(TRIG_psCfg->u8Port, TRIG_psCfg->u8Pin, GPIOx_LOW) ;
}
References GPIOx_HIGH, GPIOx_LOW, MGPIOx_vSetResetAtomic(), MSysTick_vDelayMicroSec(), HULTSNC_ConfigType::u8Pin, and HULTSNC_ConfigType::u8Port.
HULTSNC_f32GetDistance()
f32_t HULTSNC_f32GetDistance (void)
Definition at line 69 of file UltraSonic_program.c.
{
    f32_t L_f32PulseTime = MTIM1_u16GetCaptureReg2Value() ;
    f32_t L_f32Period = MTIM1_u16GetCaptureReg1Value() ;
    f32_t L_f32Distance = INITIAL_ZERO ;
    L_f32Distance = (float)(L_f32PulseTime * 0.0174) ;
    return L_f32Distance ;
}
References INITIAL_ZERO, L_f32Distance, MTIM1_u16GetCaptureReg1Value(), and MTIM1_u16GetCaptureReg2Value().
Referenced by AACC_vModeON(), and AFCW_vModeON().