var modules =
[
    [ "DC Motor Directions", "group__motor__directions.html", "group__motor__directions" ],
    [ "DC Motor Rotation Directions", "group__motor__rotation__direction.html", "group__motor__rotation__direction" ],
    [ "Bit Manipulation Math Macros", "group__bitmath.html", "group__bitmath" ],
    [ "Bit Group Manipulation Math Macros", "group__bitmathgroup.html", "group__bitmathgroup" ],
    [ "Compiler standard macros", "group__compiler.html", "group__compiler" ],
    [ "Utilities macros", "group__utilities.html", "group__utilities" ],
    [ "Standard types", "group__typedefs.html", "group__typedefs" ],
    [ "Standard values", "group__standardvalues.html", "group__standardvalues" ],
    [ "Interrupt line IDs", "group__interrupt__lines.html", "group__interrupt__lines" ],
    [ "Interrupt trigger status", "group__interrupt__trigger__status.html", "group__interrupt__trigger__status" ],
    [ "EXTI Memory Addresses", "group__exti__memory__addresses.html", "group__exti__memory__addresses" ],
    [ "EXTI Registers", "group__exti__registers.html", "group__exti__registers" ],
    [ "EXTI Lines Status", "group__exti__line__status.html", "group__exti__line__status" ],
    [ "EXTI Line Settings", "group__exti__line__settings.html", "group__exti__line__settings" ],
    [ "SYSCFG Memory Addresses", "group__syscfg__memory__addresses.html", "group__syscfg__memory__addresses" ],
    [ "SYSCFG Memory Registers", "group__syscfg__memory__registers.html", "group__syscfg__memory__registers" ],
    [ "GPIO Modes", "group__gpio__modes.html", "group__gpio__modes" ],
    [ "GPIO Ports", "group__gpio__ports.html", "group__gpio__ports" ],
    [ "GPIO Output Types", "group__gpio__output__types.html", "group__gpio__output__types" ],
    [ "GPIO PIN Speed", "group__gpio__pin__speed.html", "group__gpio__pin__speed" ],
    [ "GPIO Pull Types", "group__gpio__pull__types.html", "group__gpio__pull__types" ],
    [ "GPIO Output Values", "group__gpio__output__values.html", "group__gpio__output__values" ],
    [ "GPIO Output PINs", "group__gpio__output__pins.html", "group__gpio__output__pins" ],
    [ "GPIO Alternate Functions", "group__gpio__alternate__functions.html", "group__gpio__alternate__functions" ],
    [ "GPIO Addresses", "group__gpio__addresses.html", "group__gpio__addresses" ],
    [ "GPIO Registers", "group__gpio__registers.html", "group__gpio__registers" ],
    [ "Interrupt priority grouping", "group__interrupt__prioty__grouping.html", "group__interrupt__prioty__grouping" ],
    [ "Group priorities", "group__group__prioty.html", "group__group__prioty" ],
    [ "Sub-Group priorities", "group__sub__group__prioty.html", "group__sub__group__prioty" ],
    [ "NVIC Vector Table", "group__vector__table.html", "group__vector__table" ],
    [ "NVIC Addresses", "group__nvic__addresses.html", "group__nvic__addresses" ],
    [ "NVIC Registers", "group__nvic__registers.html", "group__nvic__registers" ],
    [ "NVIC Settable Priorities", "group__nvic__settable__priorities.html", "group__nvic__settable__priorities" ],
    [ "ID options", "group___bus.html", "group___bus" ],
    [ "ID options", "group___peripheral.html", "group___peripheral" ],
    [ "Systick Interval Mode Configuration", "group__interval__mode.html", "group__interval__mode" ],
    [ "Delay Units", "group__delay__units.html", "group__delay__units" ],
    [ "Systick Addresses", "group__systick__addresses.html", "group__systick__addresses" ],
    [ "Systick Registers", "group__systick__registers.html", "group__systick__registers" ],
    [ "Systick Register Bits Positions", "group__systick__register__bits.html", "group__systick__register__bits" ],
    [ "Systick Clock Sources", "group__systick__clock__sources.html", "group__systick__clock__sources" ],
    [ "Systick Exception (Interrupt) Status", "group__systick__exception__request__enable.html", "group__systick__exception__request__enable" ]
];